/**
 * lib/agent-executor.ts — Runs agent tasks in isolated tmux sessions.
 * Generates per-agent shell scripts and manages execution lifecycle.
 */
import { Agent, ToolChoice } from '@/store/types';
import { toolChoiceToLabel } from './agent-tool-router';

const HOME = '/data/data/com.termux/files/home';
const SHELLY_DIR = `${HOME}/.shelly`;
const AGENTS_DIR = `${SHELLY_DIR}/agents`;
const TMP_DIR = `${SHELLY_DIR}/tmp`;
const LOCKS_DIR = `${AGENTS_DIR}/locks`;
const LOGS_DIR = `${AGENTS_DIR}/logs`;
const ENV_FILE = `${AGENTS_DIR}/.env`;
const MAX_CONCURRENT = 2;

const DEFAULT_TIMEOUT_SEC = 600; // 10 minutes

/**
 * Generate a per-agent script: run-agent-{id}.sh
 * All values pre-computed in TypeScript, embedded as bash string literals.
 */
export function generateRunScript(agent: Agent): string {
  const agentId = agent.id;
  const resultFile = `${TMP_DIR}/agent-result-${agentId}.md`;
  const lockFile = `${LOCKS_DIR}/${agentId}.pid`;
  const logDir = `${LOGS_DIR}/${agentId}`;
  const toolLabel = toolChoiceToLabel(agent.tool);

  const slug = agent.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const outputDir = agent.outputPath.replace(/^~/, HOME);

  const escapedPrompt = agent.prompt.replace(/'/g, "'\\''");

  const toolCommand = generateToolCommand(agent.tool, escapedPrompt);

  return `#!/bin/bash
# run-agent-${agentId}.sh — Auto-generated by Shelly for agent: ${agent.name}
# Do not edit manually.
set -euo pipefail

AGENT_ID='${agentId}'
RESULT_FILE='${resultFile}'
LOCK_FILE='${lockFile}'
LOG_DIR='${logDir}'
TIMEOUT=${DEFAULT_TIMEOUT_SEC}
OUTPUT_DIR='${outputDir}'
SLUG='${slug}'
TOOL_LABEL='${toolLabel}'
ENV_FILE='${ENV_FILE}'
LOCKS_DIR='${LOCKS_DIR}'
MAX_CONCURRENT=${MAX_CONCURRENT}

START_TIME=$(date +%s)

# Source environment
[ -f "$ENV_FILE" ] && source "$ENV_FILE"
export PATH="/data/data/com.termux/files/usr/bin:$PATH"
export HOME="${HOME}"

# Create directories
mkdir -p '${TMP_DIR}' '${LOCKS_DIR}' "$LOG_DIR"

# Global concurrency check
ACTIVE_COUNT=$(find "$LOCKS_DIR" -name '*.pid' -exec sh -c 'kill -0 $(cat "{}") 2>/dev/null && echo 1' \\; | wc -l)
if [ "$ACTIVE_COUNT" -ge "$MAX_CONCURRENT" ]; then
  echo '{"status":"skipped","error":"global concurrency limit reached"}' > "$LOG_DIR/$(date +%s).json"
  exit 0
fi

# Per-agent concurrency lock
if [ -f "$LOCK_FILE" ]; then
  OLD_PID=$(cat "$LOCK_FILE")
  if kill -0 "$OLD_PID" 2>/dev/null; then
    echo '{"status":"skipped","error":"previous run still active"}' > "$LOG_DIR/$(date +%s).json"
    exit 0
  fi
  rm -f "$LOCK_FILE"
fi

# Acquire lock
echo $$ > "$LOCK_FILE"
cleanup() {
  rm -f "$LOCK_FILE"
}
trap cleanup EXIT

# Execute tool
${toolCommand}

# Check result
END_TIME=$(date +%s)
DURATION=$(( (END_TIME - START_TIME) * 1000 ))

if [ -f "$RESULT_FILE" ] && [ -s "$RESULT_FILE" ]; then
  PREVIEW=$(head -c 500 "$RESULT_FILE" | tr '\\n' ' ' | tr '"' "'")
  STATUS="success"

  # Copy to output directory
  mkdir -p "$OUTPUT_DIR"
  DATE=$(date +%Y-%m-%d)
  cp "$RESULT_FILE" "$OUTPUT_DIR/$DATE-$SLUG.md"
else
  PREVIEW=""
  STATUS="error"
fi

# Log run result
TS=$(date +%s)
cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"$STATUS","outputPreview":"$PREVIEW","durationMs":$DURATION,"toolUsed":"$TOOL_LABEL"}
LOGEOF

# Prune old logs (keep last 30)
ls -t "$LOG_DIR"/*.json 2>/dev/null | tail -n +31 | xargs rm -f 2>/dev/null || true

# Cleanup temp
rm -f "$RESULT_FILE"
`;
}

function generateToolCommand(tool: ToolChoice, escapedPrompt: string): string {
  const resultVar = '"$RESULT_FILE"';
  switch (tool.type) {
    case 'cli':
      return `timeout "$TIMEOUT" ${tool.cli} --print '${escapedPrompt}' > ${resultVar} 2>&1 || true`;
    case 'local':
      return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
echo '${escapedPrompt}' > "$PROMPT_FILE"
PROMPT_JSON=$(jq -Rs '.' < "$PROMPT_FILE")
timeout "$TIMEOUT" curl -s http://127.0.0.1:8080/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -d "{\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":$PROMPT_JSON}],\\"max_tokens\\":4096}" \\
  | jq -r '.choices[0].message.content // "Error: no response"' > ${resultVar} 2>&1 || true
rm -f "$PROMPT_FILE"`;
    case 'perplexity':
      return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
echo '${escapedPrompt}' > "$PROMPT_FILE"
PROMPT_JSON=$(jq -Rs '.' < "$PROMPT_FILE")
timeout "$TIMEOUT" curl -s https://api.perplexity.ai/chat/completions \\
  -H "Authorization: Bearer $PERPLEXITY_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d "{\\"model\\":\\"sonar\\",\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":$PROMPT_JSON}]}" \\
  | jq -r '.choices[0].message.content // "Error: no response"' > ${resultVar} 2>&1 || true
rm -f "$PROMPT_FILE"`;
    case 'auto':
      return `timeout "$TIMEOUT" gemini --print '${escapedPrompt}' > ${resultVar} 2>&1 || true`;
  }
}

export function getScriptPath(agentId: string): string {
  return `${AGENTS_DIR}/run-agent-${agentId}.sh`;
}

export function generateInstallCommands(agent: Agent): string[] {
  const scriptPath = getScriptPath(agent.id);
  return [
    `mkdir -p ${AGENTS_DIR} ${TMP_DIR} ${LOCKS_DIR} ${LOGS_DIR}/${agent.id}`,
    `chmod +x '${scriptPath}'`,
  ];
}

export function generateRunNowCommand(agentId: string): string {
  const sessionName = `shelly-agent-${agentId}`;
  const scriptPath = getScriptPath(agentId);
  return `tmux new-session -d -s "${sessionName}" "bash '${scriptPath}'" 2>/dev/null || tmux send-keys -t "${sessionName}" "bash '${scriptPath}'" Enter`;
}

export function generateStopCommand(agentId: string): string {
  const sessionName = `shelly-agent-${agentId}`;
  return `tmux kill-session -t "${sessionName}" 2>/dev/null; rm -f '${LOCKS_DIR}/${agentId}.pid'`;
}
