/**
 * lib/agent-executor.ts — Runs agent tasks in isolated tmux sessions.
 * Generates per-agent shell scripts and manages execution lifecycle.
 */
import { Agent, AgentRouteDecision, ToolChoice } from '@/store/types';
import { resolveAgentRoute, toolChoiceToLabel } from './agent-tool-router';
import { requiresApiKeyEnv, resolveForAutonomous } from './agent-credential-policy';
import { getHomePath } from '@/lib/home-path';
import { evaluateAgentActionCommand } from './agent-action-safety';

const MAX_CONCURRENT = 2;

const DEFAULT_TIMEOUT_SEC = 600; // 10 minutes
const AGENT_SCRIPT_VERSION = 8;
const LOCAL_MODEL_LIGHT = 'Qwen3.5-0.8B-Q4_K_M';
const LOCAL_MODEL_BALANCED = 'Qwen3.5-2B-Q4_K_M';
const LOCAL_MODEL_QUALITY = 'Qwen3.5-4B-Q4_K_M';

type ToolCommandOptions = {
  autonomous: boolean;
};

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function paths() {
  const home = getHomePath();
  const shellyDir = `${home}/.shelly`;
  const agentsDir = `${shellyDir}/agents`;
  const tmpDir = `${shellyDir}/tmp`;
  const locksDir = `${agentsDir}/locks`;
  const logsDir = `${agentsDir}/logs`;
  return {
    home,
    shellyDir,
    agentsDir,
    tmpDir,
    locksDir,
    logsDir,
    envFile: `${agentsDir}/.env`,
  };
}

export function selectAutonomousLocalModel(prompt: string): string {
  const lower = prompt.toLowerCase();
  if (/\b4b\b|高品質|品質確認|quality|deep|精査|推敲/.test(lower)) {
    return LOCAL_MODEL_QUALITY;
  }
  if (
    /記事|下書き|draft|essay|longform|要約|summarize|比較|compare|評価|eval|検証|review/.test(lower) ||
    prompt.length > 1200
  ) {
    return LOCAL_MODEL_BALANCED;
  }
  if (/fallback|安定|軽量/.test(lower)) {
    return LOCAL_MODEL_LIGHT;
  }
  return LOCAL_MODEL_LIGHT;
}

/**
 * Generate a per-agent script: run-agent-{id}.sh
 * All values pre-computed in TypeScript, embedded as bash string literals.
 */
export function generateRunScript(agent: Agent, opts: { suppressAction?: boolean; suppressErrorNotification?: boolean } = {}): string {
  const { home, tmpDir, locksDir, logsDir, envFile } = paths();
  const agentId = agent.id;
  const resultFile = `${tmpDir}/agent-result-${agentId}.md`;
  const lockFile = `${locksDir}/${agentId}.pid`;
  const logDir = `${logsDir}/${agentId}`;

  const routeResolution = resolveAgentRoute(agent);

  // Autonomous runs are OAuth/local only (Spec A §4): resolve `auto`→codex and
  // refuse api-key backends — there is no key in the autonomous agent path
  // (use OAuth-Codex/local, or the credential broker). Fail-closed.
  let tool: ToolChoice = routeResolution.tool;
  if (agent.autonomous) {
    const resolved = resolveForAutonomous(tool);
    if (!resolved) {
      return refusalScript(agentId, resultFile, logDir, routeResolution.decision, tool.type);
    }
    tool = resolved;
  }
  if (agent.autonomous && tool.type === 'local' && !tool.model) {
    tool = { ...tool, model: selectAutonomousLocalModel(agent.prompt) };
  }

  const toolLabel = toolChoiceToLabel(tool);
  const routeDecision = {
    ...routeResolution.decision,
    toolType: tool.type,
    toolLabel,
    route: tool.type === 'local' ? 'on-device' : tool.type === 'ab-article-eval' ? 'hybrid' : 'cloud',
  };
  const routeDecisionJson = JSON.stringify(routeDecision);
  const apiKeyEnvScrub = requiresApiKeyEnv(tool)
    ? ''
    : 'unset PERPLEXITY_API_KEY GEMINI_API_KEY CEREBRAS_API_KEY GROQ_API_KEY\n';

  const slug = agent.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const outputDir = agent.outputPath.replace(/^~/, home).replace(/^\$HOME/, home);
  // Orchestration: non-final steps suppress the action so only the FINAL step
  // drafts/notifies once (otherwise a 3-step chain fires 3 approval prompts).
  const actionType = opts.suppressAction ? '__suppressed__' : (agent.action?.type ?? 'draft');
  const actionWebhookUrl = actionType === 'webhook' ? agent.action?.webhookUrl ?? '' : '';
  const actionCommand = actionType === 'cli' ? agent.action?.command ?? '' : '';
  const actionCommandSafety = evaluateAgentActionCommand(actionCommand);

  const escapedPrompt = agent.prompt.replace(/'/g, "'\\''");

  const toolCommand = generateToolCommand(tool, escapedPrompt, agent.prompt, {
    autonomous: agent.autonomous === true,
  });
  const auditMirrorSdcardEligible = agent.autonomous === true && tool.type === 'cli';

  return `#!/bin/bash
# run-agent-${agentId}.sh — Auto-generated by Shelly for agent: ${agent.name}
# Do not edit manually.
SHELLY_AGENT_SCRIPT_VERSION=${AGENT_SCRIPT_VERSION}
set -euo pipefail

AGENT_ID=${shellQuote(agentId)}
AGENT_NAME=${shellQuote(agent.name)}
RESULT_FILE=${shellQuote(resultFile)}
LOCK_FILE=${shellQuote(lockFile)}
LOG_DIR=${shellQuote(logDir)}
TIMEOUT=${DEFAULT_TIMEOUT_SEC}
OUTPUT_DIR=${shellQuote(outputDir)}
SLUG=${shellQuote(slug)}
TOOL_LABEL=${shellQuote(toolLabel)}
ROUTE_DECISION_JSON=${shellQuote(routeDecisionJson)}
ENV_FILE=${shellQuote(envFile)}
LOCKS_DIR=${shellQuote(locksDir)}
TMP_DIR=${shellQuote(tmpDir)}
MAX_CONCURRENT=${MAX_CONCURRENT}
AUDIT_MIRROR_SDCARD_ELIGIBLE=${auditMirrorSdcardEligible ? '1' : '0'}
ACTION_TYPE=${shellQuote(actionType)}
ACTION_WEBHOOK_URL=${shellQuote(actionWebhookUrl)}
ACTION_COMMAND=${shellQuote(actionCommand)}
ACTION_COMMAND_SAFETY_LEVEL=${shellQuote(actionCommandSafety.level)}
ACTION_COMMAND_SAFETY_REASON=${shellQuote(actionCommandSafety.reason)}
ACTION_COMMAND_AUTO_APPROVABLE=${actionCommandSafety.autoApprovable ? '1' : '0'}
ACTION_NOTIFY_FILE="$LOG_DIR/native-result-notification.json"
ACTION_APPROVAL_DIR="$HOME/.shelly/agents/action-approvals"
ACTION_APPROVAL_REPLY_DIR="$HOME/.shelly/agents/action-approval-replies"
ACTION_RUN_ID="$AGENT_ID-$(date +%s)-$$"
ACTION_APPROVAL_REQUEST_FILE="$ACTION_APPROVAL_DIR/action-$ACTION_RUN_ID.json"
ACTION_APPROVAL_REPLY_FILE="$ACTION_APPROVAL_REPLY_DIR/action-$ACTION_RUN_ID.reply.json"
ACTION_APPROVAL_REQUEST_SHA256=""
ACTION_APPROVAL_TIMEOUT_SECONDS="\${SHELLY_AGENT_ACTION_APPROVAL_TIMEOUT_SECONDS:-120}"
ACTION_DISPATCH_STATUS=""
ACTION_DISPATCH_MESSAGE=""
REGISTRY_LOCK=""
REGISTRY_LOCK_ACQUIRED=0
BACKEND_ERROR_FILE="$RESULT_FILE.backend-error"
LOCAL_LLM_HEARTBEAT_PID=""
LOCAL_LLM_ACTIVE_MARKER=""
FINISH_RAN=0
SUPPRESS_ERROR_NOTIFICATION=${opts.suppressErrorNotification ? '1' : '0'}

START_TIME=$(date +%s)

export HOME="${home}"
export PATH="$HOME/.local/bin:$PATH"

cleanup() {
  local_llm_stop_activity_heartbeat 2>/dev/null || true
  if [ "\${REGISTRY_LOCK_ACQUIRED:-0}" = "1" ] && [ -n "\${REGISTRY_LOCK:-}" ] && [ -d "$REGISTRY_LOCK" ]; then
    rmdir "$REGISTRY_LOCK" 2>/dev/null || true
  fi
  rm -f "$LOCK_FILE"
}
shelly_app_binary_path() {
  name="$1"
  if [ -n "\${SHELLY_LIB_DIR:-}" ] && [ -f "$SHELLY_LIB_DIR/$name" ]; then
    printf '%s\\n' "$SHELLY_LIB_DIR/$name"
    return 0
  fi
  resolved=$(command -v "$name" 2>/dev/null || true)
  case "$resolved" in
    /*)
      printf '%s\\n' "$resolved"
      return 0
      ;;
  esac
  return 1
}
shelly_run_app_binary() {
  name="$1"
  shift
  binary=$(shelly_app_binary_path "$name") || return 127
  binary_dir="\${binary%/*}"
  if [ -x /system/bin/linker64 ]; then
    LD_LIBRARY_PATH="\${SHELLY_LD_LIBRARY_PATH:-\${SHELLY_LIB_DIR:-$binary_dir}}" /system/bin/linker64 "$binary" "$@"
    return $?
  fi
  "$binary" "$@"
}
shelly_timeout_app_binary() {
  seconds="$1"
  shift
  name="$1"
  shift
  binary=$(shelly_app_binary_path "$name") || return 127
  binary_dir="\${binary%/*}"
  if [ -x /system/bin/linker64 ]; then
    if command -v timeout >/dev/null 2>&1; then
      LD_LIBRARY_PATH="\${SHELLY_LD_LIBRARY_PATH:-\${SHELLY_LIB_DIR:-$binary_dir}}" timeout "$seconds" /system/bin/linker64 "$binary" "$@"
    else
      LD_LIBRARY_PATH="\${SHELLY_LD_LIBRARY_PATH:-\${SHELLY_LIB_DIR:-$binary_dir}}" /system/bin/linker64 "$binary" "$@"
    fi
    return $?
  fi
  if command -v timeout >/dev/null 2>&1; then
    timeout "$seconds" "$binary" "$@"
  else
    "$binary" "$@"
  fi
}
shelly_node() {
  shelly_run_app_binary node "$@"
}
shelly_curl() {
  shelly_run_app_binary curl "$@"
}
node_usable() {
  shelly_node -e 'process.exit(0)' >/dev/null 2>&1 || return 1
}
python3_usable() {
  command -v python3 >/dev/null 2>&1 || return 1
  python3 -c 'import sys' >/dev/null 2>&1 || return 1
}
json_escape_text() {
  text="$1"
  if node_usable; then
    if SHELLY_JSON_TEXT="$text" shelly_node -e 'const s = process.env.SHELLY_JSON_TEXT || ""; process.stdout.write(JSON.stringify(s).slice(1, -1));' 2>/dev/null; then
      return 0
    fi
  fi
  text=\${text//\\\\/\\\\\\\\}
  text=\${text//\\"/\\\\\\"}
  text=\${text//$'\\n'/ }
  text=\${text//$'\\r'/ }
  text=\${text//$'\\t'/ }
  printf '%s' "$text"
}
write_failure_log() {
  code="$1"
  line="$2"
  END_TIME=$(date +%s)
  DURATION=$(( (END_TIME - START_TIME) * 1000 ))
  TS=$(date +%s)
  PREVIEW=$(printf 'Agent script failed before producing a result. exit=%s line=%s. PATH=%s' "$code" "$line" "$PATH" | head -c 500 | tr '\\n' ' ')
  PREVIEW_JSON=$(json_escape_text "$PREVIEW")
  TOOL_LABEL_JSON=$(json_escape_text "$TOOL_LABEL")
  cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"error","outputPreview":"$PREVIEW_JSON","durationMs":$DURATION,"toolUsed":"$TOOL_LABEL_JSON","errorMessage":"$PREVIEW_JSON"}
LOGEOF
  if [ -n "\${ROUTE_DECISION_JSON:-}" ]; then
    tmp_log="$LOG_DIR/$TS.json.tmp"
    cat > "$tmp_log" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"error","outputPreview":"$PREVIEW_JSON","durationMs":$DURATION,"toolUsed":"$TOOL_LABEL_JSON","errorMessage":"$PREVIEW_JSON","routeDecision":$ROUTE_DECISION_JSON}
LOGEOF
    mv "$tmp_log" "$LOG_DIR/$TS.json"
  fi
}
finish() {
  code="\${1:-$?}"
  if [ "\${FINISH_RAN:-0}" = "1" ]; then
    return 0
  fi
  FINISH_RAN=1
  trap - EXIT
  if [ "$code" -ne 0 ]; then
    write_failure_log "$code" "\${BASH_LINENO[0]:-unknown}" || true
  fi
  mirror_driver_audit_to_app_private || true
  mirror_driver_audit_to_sdcard || true
  cleanup
  return 0
}

mirror_driver_audit_to_app_private() {
  audit_file="$LOG_DIR/agent-driver-audit.jsonl"
  [ -s "$audit_file" ] || return 0
  audit_dir="$HOME/.shelly/agents/audits"
  mkdir -p "$audit_dir" 2>/dev/null || true
  cp "$audit_file" "$audit_dir/$AGENT_ID-agent-driver-audit.jsonl" 2>/dev/null || true
}

mirror_driver_audit_to_sdcard() {
  # Debug-only B2 verification aid. Keep disabled by default; audit JSONL may
  # contain escalation commands and should not be mirrored to shared storage
  # unless an operator explicitly opts in for on-device verification.
  [ "\${AUDIT_MIRROR_SDCARD_ELIGIBLE:-0}" = "1" ] || return 0
  case "\${SHELLY_AGENT_AUDIT_MIRROR_SDCARD:-}" in
    1|true|TRUE|yes|YES|on|ON) ;;
    *) return 0 ;;
  esac
  audit_file="$LOG_DIR/agent-driver-audit.jsonl"
  [ -s "$audit_file" ] || return 0
  cp "$audit_file" "/sdcard/b2-autonomous-audit-$AGENT_ID.jsonl" 2>/dev/null || true
}

json_string_file() {
  file="$1"
  if node_usable; then
    if shelly_node -e 'const fs = require("fs"); const file = process.argv[1]; process.stdout.write(JSON.stringify(fs.readFileSync(file, "utf8")));' "$file" 2>/dev/null; then
      return 0
    fi
  fi
  printf '"'
  while IFS= read -r line || [ -n "$line" ]; do
    line=\${line//$'\\r'/ }
    line=\${line//$'\\t'/ }
    line=\${line//\\\\/\\\\\\\\}
    line=\${line//\\"/\\\\\\"}
    printf '%s\\\\n' "$line"
  done < "$file"
  printf '"'
}

# Strip the autonomous driver's structured telemetry (AUDIT/GATE/protocol/STDERR/
# escalation) from a result file so the user-facing preview shows real content,
# never the internal driver_start JSON. Backends that write a plain answer
# (local/perplexity/gemini) have no such lines, so this is a harmless no-op for
# them. Whitespace-collapsed and length-capped for a notification body.
clean_result_preview() {
  file="$1"
  [ -f "$file" ] || return 0
  sed -E '/^(AUDIT|AUDIT_FALLBACK|GATE|C->S|S->C|STDERR|ESCALATE|ESCALATE_RESOLVED) /d' "$file" 2>/dev/null \
    | head -c 500 | tr '\\n' ' '
}

write_native_notification_request() {
  status="$1"
  preview="$2"
  status_json=$(json_escape_text "$status")
  preview_json=$(json_escape_text "$preview")
  agent_json=$(json_escape_text "$AGENT_ID")
  agent_name_json=$(json_escape_text "$AGENT_NAME")
  tool_label_json=$(json_escape_text "$TOOL_LABEL")
  tmp="$ACTION_NOTIFY_FILE.tmp"
  cat > "$tmp" << NOTIFYEOF
{"agentId":"$agent_json","agentName":"$agent_name_json","toolLabel":"$tool_label_json","status":"$status_json","preview":"$preview_json","timestamp":$(date +%s)}
NOTIFYEOF
  mv "$tmp" "$ACTION_NOTIFY_FILE"
}

write_webhook_payload() {
  out_file="$1"
  status="$2"
  preview="$3"
  result_file="$4"
  agent_json=$(json_escape_text "$AGENT_ID")
  status_json=$(json_escape_text "$status")
  preview_json=$(json_escape_text "$preview")
  tool_json=$(json_escape_text "$TOOL_LABEL")
  result_json=$(json_string_file "$result_file")
  cat > "$out_file" << PAYLOADEOF
{"agentId":"$agent_json","status":"$status_json","preview":"$preview_json","toolUsed":"$tool_json","timestamp":$(date +%s),"result":$result_json}
PAYLOADEOF
}

webhook_destination_host() {
  url="$1"
  if node_usable; then
    if SHELLY_WEBHOOK_URL="$url" shelly_node -e 'try { const u = new URL(process.env.SHELLY_WEBHOOK_URL || ""); if (u.protocol !== "https:" || !u.hostname) process.exit(1); process.stdout.write(u.host || u.hostname); } catch (_) { process.exit(1); }' 2>/dev/null; then
      return 0
    fi
  fi
  case "$url" in
    https://*) ;;
    *) return 1 ;;
  esac
  host=$(printf '%s' "$url" | sed -E 's#^[a-zA-Z][a-zA-Z0-9+.-]*://##; s#/.*$##')
  [ -n "$host" ] || return 1
  printf '%s' "$host"
}

sha256_file() {
  file="$1"
  if node_usable; then
    if shelly_node - "$file" <<'NODEEOF' 2>/dev/null
const fs = require('fs');
const crypto = require('crypto');
const file = process.argv[2];
process.stdout.write(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'));
NODEEOF
    then
      return 0
    fi
  fi
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
    return 0
  fi
  return 1
}

json_field_file() {
  file="$1"
  field="$2"
  if node_usable; then
    if shelly_node - "$file" "$field" <<'NODEEOF' 2>/dev/null
const fs = require('fs');
const [file, field] = process.argv.slice(2);
const value = JSON.parse(fs.readFileSync(file, 'utf8'))[field];
if (typeof value === 'string') process.stdout.write(value);
NODEEOF
    then
      return 0
    fi
  fi
  sed -nE "s/.*\\\"$field\\\"[[:space:]]*:[[:space:]]*\\\"([^\\\"]*)\\\".*/\\1/p" "$file" 2>/dev/null | head -n 1
}

write_action_approval_request() {
  approval_type="$1"
  preview="$2"
  result_file="$3"
  destination_host="\${4:-}"
  payload_path="\${5:-}"
  mkdir -p "$ACTION_APPROVAL_DIR" "$ACTION_APPROVAL_REPLY_DIR" "$LOG_DIR"
  preview_json=$(json_escape_text "$preview")
  agent_json=$(json_escape_text "$AGENT_ID")
  agent_name_json=$(json_escape_text "$AGENT_NAME")
  tool_label_json=$(json_escape_text "$TOOL_LABEL")
  approval_type_json=$(json_escape_text "$approval_type")
  destination_json=$(json_escape_text "$destination_host")
  command_json=$(json_escape_text "$ACTION_COMMAND")
  safety_level_json=$(json_escape_text "$ACTION_COMMAND_SAFETY_LEVEL")
  safety_reason_json=$(json_escape_text "$ACTION_COMMAND_SAFETY_REASON")
  payload_path_json=$(json_escape_text "$payload_path")
  result_path_json=$(json_escape_text "$result_file")
  ts_seconds=$(date +%s)
  expires_at=$(( (ts_seconds + ACTION_APPROVAL_TIMEOUT_SECONDS) * 1000 ))
  tmp="$ACTION_APPROVAL_REQUEST_FILE.tmp"
  cat > "$tmp" << APPROVALEOF
{"runId":"$ACTION_RUN_ID","agentId":"$agent_json","agentName":"$agent_name_json","toolLabel":"$tool_label_json","actionType":"$approval_type_json","preview":"$preview_json","destinationHost":"$destination_json","command":"$command_json","safetyLevel":"$safety_level_json","safetyReason":"$safety_reason_json","payloadPath":"$payload_path_json","resultPath":"$result_path_json","ts":"$(date -Iseconds)","expiresAt":$expires_at}
APPROVALEOF
  mv "$tmp" "$ACTION_APPROVAL_REQUEST_FILE"
  ACTION_APPROVAL_REQUEST_SHA256="$(sha256_file "$ACTION_APPROVAL_REQUEST_FILE" || true)"
}

wait_action_approval() {
  approval_type="$1"
  deadline=$(( $(date +%s) + ACTION_APPROVAL_TIMEOUT_SECONDS ))
  while [ "$(date +%s)" -le "$deadline" ]; do
    if [ -s "$ACTION_APPROVAL_REPLY_FILE" ]; then
      reply_run_id="$(json_field_file "$ACTION_APPROVAL_REPLY_FILE" "runId")"
      reply_decision="$(json_field_file "$ACTION_APPROVAL_REPLY_FILE" "decision")"
      reply_request_sha="$(json_field_file "$ACTION_APPROVAL_REPLY_FILE" "requestSha256")"
      if [ "$reply_run_id" != "$ACTION_RUN_ID" ] ||
        [ -z "$ACTION_APPROVAL_REQUEST_SHA256" ] ||
        [ "$reply_request_sha" != "$ACTION_APPROVAL_REQUEST_SHA256" ]; then
        rm -f "$ACTION_APPROVAL_REPLY_FILE" "$ACTION_APPROVAL_REQUEST_FILE" 2>/dev/null || true
        ACTION_DISPATCH_STATUS="error"
        ACTION_DISPATCH_MESSAGE="$approval_type action approval reply did not match the pending request."
        write_native_notification_request "error" "$ACTION_DISPATCH_MESSAGE" || true
        return 1
      fi
      if [ "$reply_decision" = "accept" ]; then
        rm -f "$ACTION_APPROVAL_REPLY_FILE" "$ACTION_APPROVAL_REQUEST_FILE" 2>/dev/null || true
        return 0
      fi
      rm -f "$ACTION_APPROVAL_REPLY_FILE" "$ACTION_APPROVAL_REQUEST_FILE" 2>/dev/null || true
      ACTION_DISPATCH_STATUS="skipped"
      ACTION_DISPATCH_MESSAGE="$approval_type action was declined."
      write_native_notification_request "skipped" "$ACTION_DISPATCH_MESSAGE" || true
      return 1
    fi
    sleep 1
  done
  rm -f "$ACTION_APPROVAL_REQUEST_FILE" 2>/dev/null || true
  ACTION_DISPATCH_STATUS="skipped"
  ACTION_DISPATCH_MESSAGE="$approval_type action approval timed out."
  write_native_notification_request "skipped" "$ACTION_DISPATCH_MESSAGE" || true
  return 1
}

register_source_urls() {
  result_file="$1"
  REGISTRY_LOCK="$SOURCE_REGISTRY_FILE.lock"
  REGISTRY_LOCK_ACQUIRED=0
  lock_attempt=0
  until mkdir "$REGISTRY_LOCK" 2>/dev/null; do
    lock_attempt=$((lock_attempt + 1))
    if [ "$lock_attempt" -ge 30 ]; then
      break
    fi
    sleep 1
  done
  if [ "$lock_attempt" -lt 30 ]; then
    REGISTRY_LOCK_ACQUIRED=1
  fi
  { grep -Eo 'https?://[^][ )<>"'"'"']+' "$result_file" 2>/dev/null || true; } | sed 's/[.,;)]$//' | sort -u | while read -r url; do
    [ -n "$url" ] || continue
    if ! awk -F '\\t' -v url="$url" '$4 == url { found=1 } END { exit found ? 0 : 1 }' "$SOURCE_REGISTRY_FILE"; then
      printf '%s\\t%s\\t%s\\t%s\\n' "$(date -Iseconds)" "$AGENT_ID" "$TOOL_LABEL" "$url" >> "$SOURCE_REGISTRY_FILE"
    fi
  done
  if [ "$REGISTRY_LOCK_ACQUIRED" = "1" ] && [ -d "$REGISTRY_LOCK" ]; then
    rmdir "$REGISTRY_LOCK" 2>/dev/null || true
    REGISTRY_LOCK_ACQUIRED=0
    REGISTRY_LOCK=""
  fi
}

save_draft_result() {
  result_file="$1"
  mkdir -p "$OUTPUT_DIR"
  DATE=$(date +%Y-%m-%d)
  SAVED_FILE="$OUTPUT_DIR/$DATE-$SLUG.md"
  cp "$result_file" "$SAVED_FILE"

  if [ -n "\${OBSIDIAN_VAULT_PATH:-}" ] && [ -d "$OBSIDIAN_VAULT_PATH" ]; then
    OBSIDIAN_TARGET="90_Log/Agent_Output"
    case "$OUTPUT_DIR" in
      *drafts/substack*) OBSIDIAN_TARGET="50_Drafts/Substack" ;;
      *drafts/x*) OBSIDIAN_TARGET="50_Drafts/X" ;;
      *drafts/articles*) OBSIDIAN_TARGET="50_Drafts/Substack" ;;
      *sources*) OBSIDIAN_TARGET="20_Literature/Papers" ;;
      *images/prompts*) OBSIDIAN_TARGET="60_Experiments/Image_Prompts" ;;
      *evals*) OBSIDIAN_TARGET="90_Log/Agent_Evals" ;;
    esac
    mkdir -p "$OBSIDIAN_VAULT_PATH/$OBSIDIAN_TARGET"
    cp "$SAVED_FILE" "$OBSIDIAN_VAULT_PATH/$OBSIDIAN_TARGET/$DATE-$SLUG.md"
  fi

  register_source_urls "$result_file"
}

dispatch_agent_action() {
  result_file="$1"
  preview="$2"
  ACTION_DISPATCH_STATUS=""
  ACTION_DISPATCH_MESSAGE=""

  case "$ACTION_TYPE" in
    __suppressed__)
      # Orchestration non-final step: still save the draft result for the next
      # step to read, but DO NOT request approval or fire a notification.
      save_draft_result "$result_file" 2>/dev/null || true
      return 0
      ;;
    ""|draft)
      write_action_approval_request "draft" "$preview" "$result_file"
      wait_action_approval "draft" || return 1
      save_draft_result "$result_file"
      # Post ONE readable completion card after the draft is saved, so an approved
      # draft run gives the user closure (matching the notify action). The preview
      # is already telemetry-stripped. Orchestration non-final steps never reach
      # here (they use the __suppressed__ branch above), so a chain still ends with
      # a single completion, not one per step.
      write_native_notification_request "success" "$preview" || true
      return 0
      ;;
    notify)
      write_action_approval_request "notify" "$preview" "$result_file"
      wait_action_approval "notify" || return 1
      write_native_notification_request "success" "$preview"
      return 0
      ;;
    webhook)
      if [ -z "$ACTION_WEBHOOK_URL" ]; then
        ACTION_DISPATCH_STATUS="error"
        ACTION_DISPATCH_MESSAGE="Webhook action is missing an https URL."
        write_native_notification_request "error" "$ACTION_DISPATCH_MESSAGE" || true
        return 1
      fi
      case "$ACTION_WEBHOOK_URL" in
        https://*) ;;
        *)
          ACTION_DISPATCH_STATUS="error"
          ACTION_DISPATCH_MESSAGE="Webhook action requires an https URL."
          write_native_notification_request "error" "$ACTION_DISPATCH_MESSAGE" || true
          return 1
          ;;
      esac
      if ! webhook_host="$(webhook_destination_host "$ACTION_WEBHOOK_URL" 2>/dev/null)"; then
        ACTION_DISPATCH_STATUS="error"
        ACTION_DISPATCH_MESSAGE="Webhook action URL is invalid."
        write_native_notification_request "error" "$ACTION_DISPATCH_MESSAGE" || true
        return 1
      fi
      webhook_payload="$LOG_DIR/webhook-payload-$(date +%s).json"
      webhook_response="$LOG_DIR/webhook-response-$(date +%s).txt"
      webhook_error="$LOG_DIR/webhook-error-$(date +%s).txt"
      write_webhook_payload "$webhook_payload" "success" "$preview" "$result_file"
      write_action_approval_request "webhook" "$preview" "$result_file" "$webhook_host" "$webhook_payload"
      wait_action_approval "webhook" || return 1
      set +e
      HTTP_TIMEOUT_SECONDS="\${WEBHOOK_TIMEOUT_SECONDS:-30}" http_post_json "$ACTION_WEBHOOK_URL" "$webhook_payload" "$webhook_response" "$webhook_error"
      webhook_rc=$?
      set -e
      if [ "$webhook_rc" -ne 0 ]; then
        ACTION_DISPATCH_STATUS="error"
        ACTION_DISPATCH_MESSAGE="Webhook dispatch failed with exit $webhook_rc: $(head -c 240 "$webhook_error" 2>/dev/null | tr '\\n' ' ')"
        write_native_notification_request "error" "$ACTION_DISPATCH_MESSAGE" || true
        return 1
      fi
      ACTION_DISPATCH_MESSAGE="Webhook delivered to $webhook_host"
      return 0
      ;;
    cli)
      if [ -z "$ACTION_COMMAND" ]; then
        ACTION_DISPATCH_STATUS="error"
        ACTION_DISPATCH_MESSAGE="CLI action is missing a command."
        write_native_notification_request "error" "$ACTION_DISPATCH_MESSAGE" || true
        return 1
      fi
      write_action_approval_request "cli" "$preview" "$result_file"
      wait_action_approval "cli" || return 1
      cli_output="$LOG_DIR/cli-action-output-$(date +%s).txt"
      set +e
      bash -lc "$ACTION_COMMAND" > "$cli_output" 2>&1
      cli_rc=$?
      set -e
      {
        printf '\\n## CLI action\\n\\n'
        printf 'Safety: %s - %s\\n\\n' "$ACTION_COMMAND_SAFETY_LEVEL" "$ACTION_COMMAND_SAFETY_REASON"
        printf 'Command:\\n\\n\`\`\`sh\\n%s\\n\`\`\`\\n\\n' "$ACTION_COMMAND"
        printf 'Exit code: %s\\n\\n' "$cli_rc"
        printf 'Output:\\n\\n\`\`\`text\\n'
        head -c 4000 "$cli_output" 2>/dev/null || true
        printf '\\n\`\`\`\\n'
      } >> "$result_file"
      if [ "$cli_rc" -ne 0 ]; then
        ACTION_DISPATCH_STATUS="error"
        ACTION_DISPATCH_MESSAGE="CLI action failed with exit $cli_rc."
        write_native_notification_request "error" "$ACTION_DISPATCH_MESSAGE" || true
        return 1
      fi
      ACTION_DISPATCH_MESSAGE="CLI action completed."
      return 0
      ;;
    *)
      ACTION_DISPATCH_STATUS="error"
      ACTION_DISPATCH_MESSAGE="Unknown agent action: $ACTION_TYPE"
      write_native_notification_request "error" "$ACTION_DISPATCH_MESSAGE" || true
      return 1
      ;;
  esac
}

http_post_json() {
  url="$1"
  body_file="$2"
  out_file="$3"
  err_file="$4"
  if node_usable; then
    shelly_node - "$url" "$body_file" > "$out_file" 2> "$err_file" <<'NODEEOF'
const fs = require('fs');
const http = require('http');
const https = require('https');

const [urlText, bodyFile] = process.argv.slice(2);
const body = fs.readFileSync(bodyFile);
const url = new URL(urlText);
const isHttps = url.protocol === 'https:';
const client = isHttps ? https : http;
const timeoutSeconds = Number(process.env.HTTP_TIMEOUT_SECONDS || '0');
const headers = {
  'Content-Type': 'application/json',
  'Content-Length': String(body.length),
};
if (process.env.HTTP_AUTH_HEADER) {
  headers.Authorization = process.env.HTTP_AUTH_HEADER;
}
if (process.env.HTTP_EXTRA_HEADERS) {
  for (const line of process.env.HTTP_EXTRA_HEADERS.split('\\n')) {
    const idx = line.indexOf(':');
    if (idx > 0) {
      headers[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
    }
  }
}

const req = client.request({
  method: 'POST',
  protocol: url.protocol,
  hostname: url.hostname,
  port: url.port || (isHttps ? 443 : 80),
  path: url.pathname + url.search,
  headers,
}, (res) => {
  res.setEncoding('utf8');
  res.on('data', (chunk) => process.stdout.write(chunk));
  res.on('end', () => {
    process.exitCode = res.statusCode && res.statusCode >= 400 ? 22 : 0;
  });
});

req.on('error', (err) => {
  console.error(err && err.message ? err.message : String(err));
  process.exitCode = 1;
});
if (Number.isFinite(timeoutSeconds) && timeoutSeconds > 0) {
  req.setTimeout(timeoutSeconds * 1000, () => {
    req.destroy(new Error('request timed out'));
  });
}
req.write(body);
req.end();
NODEEOF
    return $?
  fi

  echo "No HTTP client available: node is missing or unavailable." > "$err_file"
  return 127
}

http_get_ok() {
  url="$1"
  err_file="$2"
  timeout_seconds="\${3:-5}"
  if node_usable; then
    HTTP_TIMEOUT_SECONDS="$timeout_seconds" shelly_node - "$url" > /dev/null 2> "$err_file" <<'NODEEOF'
const http = require('http');
const https = require('https');

const url = new URL(process.argv[2]);
const isHttps = url.protocol === 'https:';
const client = isHttps ? https : http;
const timeoutSeconds = Number(process.env.HTTP_TIMEOUT_SECONDS || '5');

const req = client.request({
  method: 'GET',
  protocol: url.protocol,
  hostname: url.hostname,
  port: url.port || (isHttps ? 443 : 80),
  path: url.pathname + url.search,
}, (res) => {
  res.resume();
  res.on('end', () => {
    process.exitCode = res.statusCode && res.statusCode < 500 ? 0 : 22;
  });
});

req.on('error', (err) => {
  console.error(err && err.message ? err.message : String(err));
  process.exitCode = 1;
});
req.setTimeout(timeoutSeconds * 1000, () => {
  req.destroy(new Error('request timed out'));
});
req.end();
NODEEOF
    return $?
  fi

  echo "No HTTP client available: node is missing or unavailable." > "$err_file"
  return 127
}

http_get_text() {
  url="$1"
  out_file="$2"
  err_file="$3"
  timeout_seconds="\${4:-5}"
  if node_usable; then
    HTTP_TIMEOUT_SECONDS="$timeout_seconds" shelly_node - "$url" > "$out_file" 2> "$err_file" <<'NODEEOF'
const http = require('http');
const https = require('https');

const url = new URL(process.argv[2]);
const isHttps = url.protocol === 'https:';
const client = isHttps ? https : http;
const timeoutSeconds = Number(process.env.HTTP_TIMEOUT_SECONDS || '5');

const req = client.request({
  method: 'GET',
  protocol: url.protocol,
  hostname: url.hostname,
  port: url.port || (isHttps ? 443 : 80),
  path: url.pathname + url.search,
}, (res) => {
  res.setEncoding('utf8');
  res.on('data', (chunk) => process.stdout.write(chunk));
  res.on('end', () => {
    process.exitCode = res.statusCode && res.statusCode < 500 ? 0 : 22;
  });
});

req.on('error', (err) => {
  console.error(err && err.message ? err.message : String(err));
  process.exitCode = 1;
});
req.setTimeout(timeoutSeconds * 1000, () => {
  req.destroy(new Error('request timed out'));
});
req.end();
NODEEOF
    return $?
  fi

  echo "No HTTP client available: node is missing or unavailable." > "$err_file"
  return 127
}

local_llm_is_loopback_url() {
  case "$1" in
    http://127.0.0.1|http://127.0.0.1:*|http://localhost|http://localhost:*) return 0 ;;
    *) return 1 ;;
  esac
}

local_llm_ready() {
  base_url="$1"
  timeout_seconds="\${2:-5}"
  err_file="\${3:-$TMP_DIR/local-llm-ready.err}"
  http_get_ok "\${base_url%/}/health" "$err_file" "$timeout_seconds" && return 0
  http_get_ok "\${base_url%/}/v1/models" "$err_file" "$timeout_seconds" && return 0
  return 1
}

local_llm_server_matches_model() {
  base_url="$1"
  expected_model="$2"
  timeout_seconds="\${3:-5}"
  err_file="\${4:-$TMP_DIR/local-llm-models.err}"
  out_file="$TMP_DIR/local-llm-models-$AGENT_ID.json"
  [ -n "$expected_model" ] || return 1
  if ! http_get_text "\${base_url%/}/v1/models" "$out_file" "$err_file" "$timeout_seconds"; then
    return 1
  fi
  EXPECTED_MODEL="$expected_model" shelly_node - "$out_file" <<'NODEEOF'
const fs = require('fs');

function normalize(value) {
  const base = String(value || '').split(/[\\/]/).pop() || '';
  return base.replace(/\.gguf$/i, '').toLowerCase().replace(/[^a-z0-9]+/g, '');
}

const expected = normalize(process.env.EXPECTED_MODEL);
if (!expected) process.exit(1);

let parsed;
try {
  parsed = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
} catch (_) {
  process.exit(1);
}

const ids = [];
if (Array.isArray(parsed?.data)) {
  for (const item of parsed.data) {
    if (item?.id) ids.push(item.id);
    if (item?.root) ids.push(item.root);
    if (item?.name) ids.push(item.name);
  }
}
if (parsed?.model) ids.push(parsed.model);

const ok = ids
  .map(normalize)
  .filter(Boolean)
  .some((id) => id === expected);
process.exit(ok ? 0 : 1);
NODEEOF
}

local_llm_port() {
  base_url="$1"
  port=$(printf '%s\\n' "$base_url" | sed -n 's#^http://127\\.0\\.0\\.1:\\([0-9][0-9]*\\).*#\\1#p; s#^http://localhost:\\([0-9][0-9]*\\).*#\\1#p' | head -n 1)
  printf '%s' "\${port:-8080}"
}

local_llm_touch_activity() {
  activity_file="\${LLAMA_SERVER_ACTIVITY:-$HOME/models/llama-server.activity}"
  mkdir -p "$(dirname "$activity_file")" 2>/dev/null || true
  touch "$activity_file" 2>/dev/null || true
}

local_llm_start_activity_heartbeat() {
  interval="\${1:-10}"
  case "$interval" in ''|*[!0-9]*) interval=10 ;; esac
  active_dir="\${LLAMA_SERVER_ACTIVE_DIR:-$HOME/models/llama-server.active}"
  mkdir -p "$active_dir" 2>/dev/null || true
  LOCAL_LLM_ACTIVE_MARKER="$active_dir/agent-$AGENT_ID-$$-$RANDOM.active"
  : > "$LOCAL_LLM_ACTIVE_MARKER" 2>/dev/null || true
  local_llm_touch_activity
  (
    parent_pid=$$
    trap 'rm -f "$LOCAL_LLM_ACTIVE_MARKER" 2>/dev/null || true' EXIT INT TERM
    while kill -0 "$parent_pid" 2>/dev/null; do
      touch "$LOCAL_LLM_ACTIVE_MARKER" 2>/dev/null || true
      local_llm_touch_activity
      sleep "$interval"
    done
  ) >/dev/null 2>&1 &
  LOCAL_LLM_HEARTBEAT_PID=$!
}

local_llm_stop_activity_heartbeat() {
  heartbeat_pid="\${1:-\${LOCAL_LLM_HEARTBEAT_PID:-}}"
  active_marker="\${2:-\${LOCAL_LLM_ACTIVE_MARKER:-}}"
  if [ -n "$heartbeat_pid" ] && kill -0 "$heartbeat_pid" 2>/dev/null; then
    kill "$heartbeat_pid" 2>/dev/null || true
  fi
  [ -n "$active_marker" ] && rm -f "$active_marker" 2>/dev/null || true
  LOCAL_LLM_HEARTBEAT_PID=""
  LOCAL_LLM_ACTIVE_MARKER=""
  local_llm_touch_activity
}

local_llm_cleanup_stale_active_users() {
  active_dir="\${LLAMA_SERVER_ACTIVE_DIR:-$HOME/models/llama-server.active}"
  [ -d "$active_dir" ] || return 0
  find "$active_dir" -type f -name '*.active' -mmin +5 -delete 2>/dev/null || true
}

local_llm_wait_for_no_active_users() {
  active_dir="\${LLAMA_SERVER_ACTIVE_DIR:-$HOME/models/llama-server.active}"
  wait_seconds="\${LOCAL_LLM_RESTART_WAIT_SECONDS:-120}"
  case "$wait_seconds" in ''|*[!0-9]*) wait_seconds=0 ;; esac
  [ "$wait_seconds" -gt 0 ] || return 0
  [ -d "$active_dir" ] || return 0
  _wait_i=0
  while [ "$_wait_i" -lt "$wait_seconds" ]; do
    local_llm_cleanup_stale_active_users
    active_count="$(find "$active_dir" -type f -name '*.active' 2>/dev/null | wc -l | tr -d ' ')"
    [ "\${active_count:-0}" = "0" ] && return 0
    sleep 1
    _wait_i=$((_wait_i + 1))
  done
  local_llm_cleanup_stale_active_users
  active_count="$(find "$active_dir" -type f -name '*.active' 2>/dev/null | wc -l | tr -d ' ')"
  if [ "\${active_count:-0}" != "0" ]; then
    return 1
  fi
  return 0
}

local_llm_runtime_profile() {
  model_name="$(printf '%s' "\${1:-}" | tr '[:upper:]' '[:lower:]')"
  case "$model_name" in
    *0.8b*|*0-8b*) printf '8192 2 1800\\n' ;;
    *1.7b*|*1-7b*) printf '8192 3 1800\\n' ;;
    *2b*) printf '8192 4 1800\\n' ;;
    *4b*) printf '4096 4 900\\n' ;;
    *9b*|*8b*) printf '4096 3 600\\n' ;;
    *) printf '4096 3 900\\n' ;;
  esac
}

local_llm_stop_watcher() {
  watcher_pid_file="\${LLAMA_SERVER_WATCHER_PID:-$HOME/models/llama-server-watcher.pid}"
  if [ -f "$watcher_pid_file" ]; then
    watcher_pid="$(cat "$watcher_pid_file" 2>/dev/null || true)"
    if [ -n "$watcher_pid" ] && kill -0 "$watcher_pid" 2>/dev/null; then
      kill "$watcher_pid" 2>/dev/null || true
    fi
    rm -f "$watcher_pid_file"
  fi
}

local_llm_stop_server() {
  pid_file="\${1:-$HOME/models/llama-server.pid}"
  local_llm_wait_for_no_active_users || return 1
  local_llm_stop_watcher
  if [ -f "$pid_file" ]; then
    server_pid="$(cat "$pid_file" 2>/dev/null || true)"
    if [ -n "$server_pid" ] && kill -0 "$server_pid" 2>/dev/null; then
      kill "$server_pid" 2>/dev/null || true
      sleep 1
      kill -0 "$server_pid" 2>/dev/null && kill -9 "$server_pid" 2>/dev/null || true
    fi
    rm -f "$pid_file"
  fi
  old_pid="$(ps -Af 2>/dev/null | grep -F llama-server | grep -v grep | awk '{print $2}' | head -n1)"
  if [ -n "$old_pid" ]; then
    kill "$old_pid" 2>/dev/null || true
    sleep 1
    kill -0 "$old_pid" 2>/dev/null && kill -9 "$old_pid" 2>/dev/null || true
  fi
}

local_llm_start_idle_watcher() {
  server_pid="$1"
  idle_timeout="$2"
  pid_file="$3"
  log_file="$4"
  activity_file="\${LLAMA_SERVER_ACTIVITY:-$HOME/models/llama-server.activity}"
  active_dir="\${LLAMA_SERVER_ACTIVE_DIR:-$HOME/models/llama-server.active}"
  watcher_pid_file="\${LLAMA_SERVER_WATCHER_PID:-$HOME/models/llama-server-watcher.pid}"
  case "$idle_timeout" in ''|*[!0-9]*) idle_timeout=0 ;; esac
  [ "$idle_timeout" -gt 0 ] || return 0
  local_llm_touch_activity
  (
    while kill -0 "$server_pid" 2>/dev/null; do
      find "$active_dir" -type f -name '*.active' -mmin +5 -delete 2>/dev/null || true
      active_count="$(find "$active_dir" -type f -name '*.active' 2>/dev/null | wc -l | tr -d ' ')"
      if [ "\${active_count:-0}" != "0" ]; then
        sleep 15
        continue
      fi
      now="$(date +%s)"
      last="$(stat -c %Y "$activity_file" 2>/dev/null || echo "$now")"
      case "$last" in ''|*[!0-9]*) last="$now" ;; esac
      if [ $((now - last)) -ge "$idle_timeout" ]; then
        echo "llama-server idle timeout after $idle_timeout seconds" >> "$log_file" 2>/dev/null || true
        kill "$server_pid" 2>/dev/null || true
        sleep 1
        kill -0 "$server_pid" 2>/dev/null && kill -9 "$server_pid" 2>/dev/null || true
        rm -f "$pid_file"
        break
      fi
      sleep 15
    done
  ) >/dev/null 2>&1 &
  echo $! > "$watcher_pid_file"
}

find_llama_server_bin() {
  if [ -n "\${LLAMA_SERVER_BIN:-}" ] && [ -x "$LLAMA_SERVER_BIN" ]; then
    printf '%s\\n' "$LLAMA_SERVER_BIN"
    return 0
  fi
  # T3: prefer the app-installed REAL ELF via its .realpath metadata. The
  # $HOME/.local/bin/llama-server entry is a wrapper SCRIPT (not an ELF), so the
  # linker64 launch below needs the real binary; direct-exec of the wrapper in
  # the agent's exec context fails to resolve shared libs (cold-start blocker C).
  if [ -s "$HOME/.local/bin/llama-server.realpath" ]; then
    _real_bin="$(cat "$HOME/.local/bin/llama-server.realpath" 2>/dev/null || true)"
    if [ -x "$_real_bin" ]; then
      printf '%s\\n' "$_real_bin"
      return 0
    fi
  fi
  if command -v llama-server >/dev/null 2>&1; then
    command -v llama-server
    return 0
  fi
  for candidate in "$HOME/.local/bin/llama-server" "$HOME/bin/llama-server"; do
    if [ -x "$candidate" ]; then
      printf '%s\\n' "$candidate"
      return 0
    fi
  done
  return 1
}

local_llm_normalize_model_token() {
  value="\${1:-}"
  value="\${value##*/}"
  value="\${value%.gguf}"
  printf '%s' "$value" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g'
}

local_llm_path_matches_model() {
  path_token="$(local_llm_normalize_model_token "\${1:-}")"
  model_token="$(local_llm_normalize_model_token "\${2:-}")"
  [ -n "$path_token" ] || return 1
  [ -n "$model_token" ] || return 0
  [ "$path_token" = "$model_token" ] && return 0
  case "$path_token" in *"$model_token"*) return 0 ;; esac
  case "$model_token" in *"$path_token"*) return 0 ;; esac
  return 1
}

download_file_node() {
  url="$1"
  out_file="$2"
  err_file="$3"
  if ! node_usable; then
    echo "node is required for download" > "$err_file"
    return 127
  fi
  shelly_node - "$url" "$out_file" > /dev/null 2> "$err_file" <<'NODEEOF'
const fs = require('fs');
const http = require('http');
const https = require('https');

const [urlText, outFile] = process.argv.slice(2);

function download(urlText, redirects) {
  const url = new URL(urlText);
  const client = url.protocol === 'https:' ? https : http;
  const req = client.get(url, {
    headers: { 'User-Agent': 'Shelly-local-llm-installer/1' },
  }, (res) => {
    if ([301, 302, 303, 307, 308].includes(res.statusCode || 0) && res.headers.location) {
      res.resume();
      if (redirects <= 0) {
        console.error('too many redirects');
        process.exit(1);
        return;
      }
      download(new URL(res.headers.location, url).toString(), redirects - 1);
      return;
    }
    if (!res.statusCode || res.statusCode >= 400) {
      console.error('download failed: HTTP ' + res.statusCode);
      res.resume();
      process.exit(1);
      return;
    }
    const tmp = outFile + '.part';
    const file = fs.createWriteStream(tmp);
    res.pipe(file);
    file.on('finish', () => {
      file.close(() => {
        fs.renameSync(tmp, outFile);
      });
    });
    file.on('error', (err) => {
      console.error(err && err.message ? err.message : String(err));
      try { fs.unlinkSync(tmp); } catch (_) {}
      process.exit(1);
    });
  });
  req.on('error', (err) => {
    console.error(err && err.message ? err.message : String(err));
    process.exit(1);
  });
  req.setTimeout(120000, () => req.destroy(new Error('download timed out')));
}

download(urlText, 5);
NODEEOF
}

extract_zip_file() {
  zip_file="$1"
  dest_dir="$2"
  err_file="$3"
  mkdir -p "$dest_dir"
  if command -v unzip >/dev/null 2>&1; then
    unzip -o "$zip_file" -d "$dest_dir" > /dev/null 2> "$err_file"
    return $?
  fi
  if python3_usable; then
    if python3 - "$zip_file" "$dest_dir" > /dev/null 2> "$err_file" <<'PYEOF'
import sys
import zipfile

zip_file, dest_dir = sys.argv[1], sys.argv[2]
with zipfile.ZipFile(zip_file) as z:
    z.extractall(dest_dir)
PYEOF
    then
      return 0
    else
      return $?
    fi
  fi
  echo "unzip or python3 is required to extract llama-server" > "$err_file"
  return 127
}

extract_archive_file() {
  archive_file="$1"
  dest_dir="$2"
  err_file="$3"
  mkdir -p "$dest_dir"
  case "$archive_file" in
    *.zip) extract_zip_file "$archive_file" "$dest_dir" "$err_file"; return $? ;;
  esac
  if command -v tar >/dev/null 2>&1; then
    tar -xzf "$archive_file" -C "$dest_dir" > /dev/null 2> "$err_file"
    return $?
  fi
  if python3_usable; then
    if python3 - "$archive_file" "$dest_dir" > /dev/null 2> "$err_file" <<'PYEOF'
import sys
import tarfile

archive_file, dest_dir = sys.argv[1], sys.argv[2]
with tarfile.open(archive_file, "r:*") as t:
    t.extractall(dest_dir)
PYEOF
    then
      return 0
    else
      return $?
    fi
  fi
  echo "tar or python3 is required to extract llama-server archive" > "$err_file"
  return 127
}

resolve_llama_server_download_url() {
  err_file="$TMP_DIR/llama-server-release-$AGENT_ID.err"
  if [ -n "\${LLAMA_SERVER_DOWNLOAD_URL:-}" ]; then
    printf '%s\\n' "$LLAMA_SERVER_DOWNLOAD_URL"
    return 0
  fi
  if ! node_usable; then
    echo "node is required to resolve latest llama-server release" > "$err_file"
    return 127
  fi
  shelly_node - > "$TMP_DIR/llama-server-url-$AGENT_ID.txt" 2> "$err_file" <<'NODEEOF'
const https = require('https');

const req = https.get('https://api.github.com/repos/ggml-org/llama.cpp/releases/latest', {
  headers: { 'User-Agent': 'Shelly-local-llm-installer/1' },
}, (res) => {
  let body = '';
  res.setEncoding('utf8');
  res.on('data', (chunk) => body += chunk);
  res.on('end', () => {
    if (!res.statusCode || res.statusCode >= 400) {
      console.error('release lookup failed: HTTP ' + res.statusCode);
      process.exit(1);
      return;
    }
    const release = JSON.parse(body);
    const assets = Array.isArray(release.assets) ? release.assets : [];
    const asset = assets.find((a) => /bin-android-arm64\\.(tar\\.gz|tgz|zip)$/i.test(a.name || ''));
    if (!asset || !asset.browser_download_url) {
      console.error('release lookup failed: android arm64 llama.cpp asset not found');
      process.exit(1);
      return;
    }
    process.stdout.write(asset.browser_download_url);
  });
});
req.setTimeout(8000, () => {
  req.destroy(new Error('release lookup timed out'));
});
req.on('error', (err) => {
  console.error('release lookup failed: ' + (err && err.message ? err.message : String(err)));
  process.exit(1);
});
NODEEOF
  if [ ! -s "$TMP_DIR/llama-server-url-$AGENT_ID.txt" ]; then
    return 1
  fi
  cat "$TMP_DIR/llama-server-url-$AGENT_ID.txt"
}

install_llama_server_bin() {
  err_file="$TMP_DIR/llama-server-install-$AGENT_ID.err"
  mkdir -p "$HOME/.local/bin" "$TMP_DIR"
  extract_dir="$TMP_DIR/llama-server-android-arm64"
  rm -rf "$extract_dir"
  mkdir -p "$extract_dir"

  url=$(resolve_llama_server_download_url || true)
  if [ -z "$url" ]; then
    echo "auto-install failed: could not resolve latest Android arm64 llama-server asset: $(head -c 300 "$TMP_DIR/llama-server-release-$AGENT_ID.err" 2>/dev/null | tr '\\n' ' ')"
    return 1
  fi
  case "$url" in
    *.zip) archive_file="$TMP_DIR/llama-server-android-arm64.zip" ;;
    *.tgz) archive_file="$TMP_DIR/llama-server-android-arm64.tgz" ;;
    *) archive_file="$TMP_DIR/llama-server-android-arm64.tar.gz" ;;
  esac
  if ! download_file_node "$url" "$archive_file" "$err_file"; then
    echo "auto-install failed: could not download llama-server from $url: $(head -c 300 "$err_file" 2>/dev/null | tr '\\n' ' ')"
    return 1
  fi
  if ! extract_archive_file "$archive_file" "$extract_dir" "$err_file"; then
    echo "auto-install failed: could not extract llama-server archive: $(head -c 300 "$err_file" 2>/dev/null | tr '\\n' ' ')"
    return 1
  fi

  extracted=$(find "$extract_dir" -type f -name 'llama-server' 2>/dev/null | head -n 1 || true)
  if [ -z "$extracted" ]; then
    echo "auto-install failed: llama-server binary was not found inside downloaded archive"
    return 1
  fi

  install_dir="$HOME/.local/llama.cpp"
  install_tmp="$HOME/.local/llama.cpp.tmp"
  rm -rf "$install_tmp"
  mkdir -p "$install_tmp"
  cp -R "$extract_dir"/. "$install_tmp"/
  installed_binary=$(find "$install_tmp" -type f -name 'llama-server' 2>/dev/null | head -n 1 || true)
  if [ -z "$installed_binary" ]; then
    echo "auto-install failed: llama-server binary disappeared during install copy"
    return 1
  fi
  chmod +x "$installed_binary"
  rm -rf "$install_dir"
  mv "$install_tmp" "$install_dir"
  installed_binary=$(find "$install_dir" -type f -name 'llama-server' 2>/dev/null | head -n 1 || true)
  binary_dir=$(dirname "$installed_binary")
  lib_dirs=$(find "$install_dir" -type f -name '*.so*' -exec dirname {} \\; 2>/dev/null | sort -u | tr '\\n' ':' || true)

cat > "$HOME/.local/bin/llama-server" <<WRAPPEREOF
#!/system/bin/sh
cd "$binary_dir" || exit 1
export LD_LIBRARY_PATH="\${lib_dirs}\${binary_dir}:\${install_dir}:\${install_dir}/lib:\\\${LD_LIBRARY_PATH:-}"
unset LD_PRELOAD
if [ -x /system/bin/linker64 ]; then
  exec /system/bin/linker64 "$installed_binary" "\\$@"
fi
exec "$installed_binary" "\\$@"
WRAPPEREOF
  chmod +x "$HOME/.local/bin/llama-server"
  printf '%s\\n' "$HOME/.local/bin/llama-server"
}

find_local_llm_model() {
  model_name="\${1:-Qwen3.5-0.8B-Q4_K_M}"
  if [ -n "\${LOCAL_LLM_MODEL_PATH:-}" ] &&
    [ -f "$LOCAL_LLM_MODEL_PATH" ] &&
    local_llm_path_matches_model "$LOCAL_LLM_MODEL_PATH" "$model_name"; then
    printf '%s\\n' "$LOCAL_LLM_MODEL_PATH"
    return 0
  fi

  case "$model_name" in
    *.gguf) model_file="$model_name" ;;
    *) model_file="$model_name.gguf" ;;
  esac

  for dir in "$HOME/models" "$HOME" "$HOME/.local/share/shelly/models" "/sdcard/Download" "/sdcard/models" "/sdcard/llama" "/sdcard/Documents/models" "/sdcard/Models"; do
    [ -d "$dir" ] || continue
    if [ -f "$dir/$model_file" ]; then
      printf '%s\\n' "$dir/$model_file"
      return 0
    fi
  done

  search_pattern='Qwen3.*0[._-]*8B.*Q4_K_M\\|Qwen3.*Q4_K_M.*0[._-]*8B'
  case "$(printf '%s' "$model_name" | tr '[:upper:]' '[:lower:]')" in
    *0.8b*) search_pattern='Qwen3.*0[._-]*8B.*Q4_K_M\\|Qwen3.*Q4_K_M.*0[._-]*8B' ;;
    *1.7b*) search_pattern='Qwen3.*1[._-]*7B.*Q4_K_M\\|Qwen3.*Q4_K_M.*1[._-]*7B' ;;
    *2b*) search_pattern='Qwen3.*2B.*Q4_K_M\\|Qwen3.*Q4_K_M.*2B' ;;
    *8b*) search_pattern='Qwen3.*8B.*Q4_K_M\\|Qwen3.*Q4_K_M.*8B' ;;
    *4b*) search_pattern='Qwen3.*4B.*Q4_K_M\\|Qwen3.*Q4_K_M.*4B' ;;
  esac

  for dir in "$HOME/models" "$HOME" "/sdcard/Download" "/sdcard/models" "/sdcard/llama" "/sdcard/Documents/models" "/sdcard/Models"; do
    [ -d "$dir" ] || continue
    found=$(find "$dir" -maxdepth 2 -type f -name '*.gguf' 2>/dev/null | grep -i "$search_pattern" | head -n 1 || true)
    if [ -n "$found" ]; then
      printf '%s\\n' "$found"
      return 0
    fi
  done

  # T1: installed-aware fallback. The requested tier is not present; rather than
  # fail (which blocks ALL autostart — root cause B), use the first installed
  # Qwen Q4_K_M model. llama.cpp serves whatever it loads regardless of the
  # request's model field, and the caller re-derives the alias + readiness check
  # from the returned path, so a tier substitution is safe.
  for dir in "$HOME/models" "$HOME" "$HOME/.local/share/shelly/models" "/sdcard/Download" "/sdcard/models" "/sdcard/llama" "/sdcard/Documents/models" "/sdcard/Models"; do
    [ -d "$dir" ] || continue
    found=$(find "$dir" -maxdepth 2 -type f -name '*.gguf' 2>/dev/null | grep -iE 'qwen3?[._-].*q4_k_m' | head -n 1 || true)
    if [ -n "$found" ]; then
      printf '%s\\n' "$found"
      return 0
    fi
  done

  return 1
}

# Remove a stale local-LLM start lock so a lock leaked by a killed starter cannot
# permanently block autostart (root cause A). Stale = holder PID dead, or no live
# holder and older than a short just-created grace window. The lock dir holds
# owner.pid written by the acquirer.
local_llm_clear_stale_start_lock() {
  _ld="$1"
  [ -d "$_ld" ] || return 0
  _owner="$(cat "$_ld/owner.pid" 2>/dev/null || true)"
  if [ -n "$_owner" ] && kill -0 "$_owner" 2>/dev/null; then
    return 0
  fi
  _now="$(date +%s 2>/dev/null || echo 0)"
  _mtime="$(stat -c %Y "$_ld" 2>/dev/null || echo 0)"
  if [ -z "$_owner" ] && [ "$_now" -gt 0 ] && [ "$_mtime" -gt 0 ] && [ "$((_now - _mtime))" -lt 20 ]; then
    return 0
  fi
  rm -rf "$_ld" 2>/dev/null || true
}

ensure_local_llm_server() {
  base_url="$1"
  model_name="\${2:-Qwen3.5-0.8B-Q4_K_M}"
  reason_file="$TMP_DIR/local-llm-start-$AGENT_ID.reason"
  : > "$reason_file"

  if local_llm_ready "$base_url" 3 "$TMP_DIR/local-llm-ready-$AGENT_ID.err"; then
    # Reuse ANY already-running local server, regardless of which model tier it
    # serves. llama.cpp serves its loaded model irrespective of the request's
    # "model" field, so a mismatch is harmless. Restarting a healthy in-app-started
    # server was the root cause of on-device failures: the in-app "Start" launches
    # llama-server through a linker64 + LLAMA_LIB_PATH wrapper, but the agent's own
    # start exec's the binary directly and cannot relaunch it — so a tier mismatch
    # (scorer wants 0.8B, user has 2B running) made the agent kill the working
    # server and fail to bring it back. Reusing whatever is up is strictly better
    # than a dead server.
    local_llm_touch_activity
    return 0
  fi

  if ! local_llm_is_loopback_url "$base_url"; then
    echo "auto-start skipped: LOCAL_LLM_URL is not loopback ($base_url)" > "$reason_file"
    return 1
  fi
  if [ "\${LOCAL_LLM_AUTOSTART:-1}" = "0" ]; then
    echo "auto-start disabled: LOCAL_LLM_AUTOSTART=0" > "$reason_file"
    return 1
  fi

  lock_dir="$LOCKS_DIR/local-llm-server-start.lock"
  local_llm_clear_stale_start_lock "$lock_dir"
  lock_acquired=0
  _i=0
	while [ "$_i" -lt 30 ]; do
	  if mkdir "$lock_dir" 2>/dev/null; then
	    lock_acquired=1
	    break
	  fi
	  if local_llm_ready "$base_url" 3 "$TMP_DIR/local-llm-ready-$AGENT_ID.err"; then
	    # Another starter won the race and a server is up — reuse it (any tier; see
	    # the top reuse path). Consistent with not killing a healthy server.
	    local_llm_touch_activity
	    return 0
	  fi
	  sleep 1
	  _i=$((_i + 1))
	done
  if [ "$lock_acquired" != "1" ]; then
    echo "auto-start skipped: could not acquire start lock $lock_dir (held by a live starter)" > "$reason_file"
    return 1
  fi
  echo $$ > "$lock_dir/owner.pid" 2>/dev/null || true

  if local_llm_ready "$base_url" 3 "$TMP_DIR/local-llm-ready-$AGENT_ID.err"; then
    # Server came up while we held the lock — reuse it (any tier).
    local_llm_touch_activity
    rm -rf "$lock_dir" 2>/dev/null || true
    return 0
  fi

  server_bin=$(find_llama_server_bin || true)
  if [ -z "$server_bin" ]; then
    if [ "\${LOCAL_LLM_INSTALL_LLAMA_SERVER:-0}" != "1" ]; then
      echo "auto-start failed: llama-server binary not found in PATH, $HOME/.local/bin, or $HOME/bin" > "$reason_file"
      rm -rf "$lock_dir" 2>/dev/null || true
      return 1
    fi
    install_result=$(install_llama_server_bin || true)
    server_bin=$(find_llama_server_bin || true)
    if [ -z "$server_bin" ]; then
      echo "auto-start failed: llama-server binary not found and auto-install did not produce an executable. $install_result" > "$reason_file"
      rm -rf "$lock_dir" 2>/dev/null || true
      return 1
    fi
  fi

  model_path=$(find_local_llm_model "$model_name" || true)
  if [ -z "$model_path" ]; then
    echo "auto-start failed: GGUF model not found for $model_name. Set LOCAL_LLM_MODEL_PATH or place it under $HOME/models or /sdcard/Download." > "$reason_file"
    rm -rf "$lock_dir" 2>/dev/null || true
    return 1
  fi

  port=$(local_llm_port "$base_url")
  log_file="\${LLAMA_SERVER_LOG:-$HOME/models/llama-server.log}"
  pid_file="\${LLAMA_SERVER_PID:-$HOME/models/llama-server.pid}"
  mkdir -p "$(dirname "$log_file")" "$(dirname "$pid_file")"
  if ! local_llm_stop_server "$pid_file"; then
    echo "auto-start skipped: another local LLM request is still active; refusing to restart llama-server" > "$reason_file"
    rm -rf "$lock_dir" 2>/dev/null || true
    return 1
  fi
  alias_name="\${model_path##*/}"
  alias_name="\${alias_name%.gguf}"
  # T1: if find_local_llm_model fell back to a different installed tier, the
  # readiness check below must match the model we actually load (alias_name),
  # NOT the requested model_name — else the just-started 2B server would be
  # rejected for not being the requested 8B and the start would "time out".
  _req_norm="$(printf '%s' "$model_name" | tr 'A-Z' 'a-z' | tr -cd 'a-z0-9')"
  _got_norm="$(printf '%s' "$alias_name" | tr 'A-Z' 'a-z' | tr -cd 'a-z0-9')"
  if [ "$_req_norm" != "$_got_norm" ]; then
    echo "note: requested model $model_name is not installed; using installed $alias_name" >> "$reason_file"
  fi
  profile="$(local_llm_runtime_profile "$alias_name")"
  set -- $profile
  default_ctx_size="$1"
  default_threads="$2"
  default_idle_timeout="$3"
  ctx_size="\${LOCAL_LLM_CTX_SIZE:-$default_ctx_size}"
  threads="\${LOCAL_LLM_THREADS:-$default_threads}"
  idle_timeout="\${LOCAL_LLM_IDLE_TIMEOUT_SECONDS:-$default_idle_timeout}"
  local_llm_touch_activity

  # T3: app-installed llama.cpp needs its shared libs on LD_LIBRARY_PATH and a
  # linker64 launch (the same mechanism as the in-app Start). Without it the
  # agent's exec context can't resolve the .so files and cold-start fails
  # (blocker C). Self-contained binaries (PATH / agent-installed wrapper) have an
  # empty llama_lib_path and fall through to a plain exec.
  # The binary's OWN dir holds all its .so files (libggml*, libllama-server-impl,
  # …). Put that absolute dir FIRST on LD_LIBRARY_PATH so lib resolution never
  # depends on the find succeeding in the agent's exec context (where it returned
  # empty, dropping to a libless plain exec → "CANNOT LINK EXECUTABLE … library
  # not found"). The find still contributes any sibling lib dirs. Trigger the
  # linker64 path whenever the binary lives under .local/llama.cpp.
  server_dir="$(dirname "$server_bin")"
  llama_lib_path="$(find "$HOME/.local/llama.cpp" -type f \\( -name '*.so' -o -name '*.so.*' \\) -exec dirname {} \\; 2>/dev/null | sort -u | tr '\\n' ':')"
  use_linker64=0
  case "$server_bin" in "$HOME/.local/llama.cpp"/*) use_linker64=1 ;; esac
  if [ -n "$llama_lib_path" ]; then use_linker64=1; fi
  if [ "$use_linker64" = 1 ] && [ -x /system/bin/linker64 ]; then
    (
      cd "$server_dir" 2>/dev/null || true
      # The agent exec context sets LD_PRELOAD=libexec_wrapper.so (shelly-exec.c);
      # inherited into the linker64 launch it breaks llama-server's own .so
      # resolution ("library libllama-server-impl.so not found"). The in-app Start
      # unsets it for the same reason — mirror that.
      unset LD_PRELOAD
      export LD_LIBRARY_PATH="$server_dir:\${llama_lib_path}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
      nohup /system/bin/nice -n 5 /system/bin/linker64 "$server_bin" --model "$model_path" --alias "$alias_name" --host 127.0.0.1 --port "$port" --ctx-size "$ctx_size" --threads "$threads" --log-disable \${LLAMA_SERVER_EXTRA_ARGS:-} > "$log_file" 2>&1 &
      echo $! > "$pid_file"
    )
  else
    nohup /system/bin/nice -n 5 "$server_bin" --model "$model_path" --alias "$alias_name" --host 127.0.0.1 --port "$port" --ctx-size "$ctx_size" --threads "$threads" --log-disable \${LLAMA_SERVER_EXTRA_ARGS:-} > "$log_file" 2>&1 &
    echo $! > "$pid_file"
  fi

  ready_seconds="\${LOCAL_LLM_START_TIMEOUT_SECONDS:-90}"
  _i=0
  while [ "$_i" -lt "$ready_seconds" ]; do
    if local_llm_ready "$base_url" 3 "$TMP_DIR/local-llm-ready-$AGENT_ID.err" &&
      local_llm_server_matches_model "$base_url" "$alias_name" 3 "$TMP_DIR/local-llm-models-$AGENT_ID.err"; then
      local_llm_touch_activity
      local_llm_start_idle_watcher "$(cat "$pid_file" 2>/dev/null || true)" "$idle_timeout" "$pid_file" "$log_file"
      rm -rf "$lock_dir" 2>/dev/null || true
      return 0
    fi
    sleep 1
    _i=$((_i + 1))
  done

  {
    echo "auto-start failed: llama-server did not become ready within $ready_seconds seconds"
    echo "server: $server_bin"
    echo "model: $model_path"
    echo "endpoint: $base_url"
    echo "log: $log_file"
    echo "log tail:"
    tail -n 40 "$log_file" 2>/dev/null || true
  } > "$reason_file"
  rm -rf "$lock_dir" 2>/dev/null || true
  return 1
}

extract_ai_content() {
  file="$1"
  if node_usable; then
    if shelly_node - "$file" <<'NODEEOF'
const fs = require('fs');

const file = process.argv[2];
const text = fs.readFileSync(file, 'utf8');
let data;
try {
  data = JSON.parse(text);
} catch (_) {
  process.stdout.write(text);
  process.exit(0);
}

let content;
try {
  content = data?.choices?.[0]?.message?.content;
} catch (_) {}
if (!content) {
  try {
    content = data?.choices?.[0]?.text;
  } catch (_) {}
}
if (!content) {
  try {
    const parts = data?.candidates?.[0]?.content?.parts || [];
    content = parts.map((part) => part && part.text ? part.text : '').filter(Boolean).join('\\n');
  } catch (_) {}
}

const err = data?.error || data?.message;
if (content) {
  process.stdout.write(content);
} else if (err) {
  process.stdout.write('API error: ' + (typeof err === 'string' ? err : JSON.stringify(err)));
  process.exit(2);
} else {
  process.stdout.write(text);
}
NODEEOF
    then
      return 0
    else
      rc=$?
      if [ "$rc" -eq 2 ]; then
        return 2
      fi
    fi
  fi
  if python3_usable; then
    if python3 - "$file" <<'PYEOF'
import json
import sys

path = sys.argv[1]
text = open(path, "r", encoding="utf-8", errors="replace").read()
try:
    data = json.loads(text)
except Exception:
    sys.stdout.write(text)
    raise SystemExit(0)

content = None
try:
    content = data.get("choices", [{}])[0].get("message", {}).get("content")
except Exception:
    content = None
if not content:
    try:
        content = data.get("choices", [{}])[0].get("text")
    except Exception:
        content = None
if not content:
    try:
        parts = data.get("candidates", [{}])[0].get("content", {}).get("parts", [])
        content = "\\n".join(part.get("text", "") for part in parts if part.get("text"))
    except Exception:
        content = None

err = data.get("error") or data.get("message")
if content:
    sys.stdout.write(content)
elif err:
    sys.stdout.write("API error: " + (err if isinstance(err, str) else json.dumps(err, ensure_ascii=False)))
    raise SystemExit(2)
else:
    sys.stdout.write(text)
PYEOF
    then
      return 0
    else
      rc=$?
      if [ "$rc" -eq 2 ]; then
        return 2
      fi
    fi
  fi
  if grep -q '"error"' "$file" 2>/dev/null; then
    printf 'API error response: '
    head -c 4000 "$file"
    return 2
  fi
  cat "$file"
}
local_context_fallback() {
  local reason="$1"
  echo "# Local Context Fallback"
  echo
  echo "Local LLM was unavailable, so Shelly saved a local-context digest instead of failing silently."
  echo
  echo "- reason: $reason"
  echo "- script version: \${SHELLY_AGENT_SCRIPT_VERSION:-unknown}"
  echo "- auto-install llama-server: \${LOCAL_LLM_INSTALL_LLAMA_SERVER:-0}"
  echo "- expected endpoint: \${LOCAL_URL%/}/v1/chat/completions"
  echo "- expected model: \${LOCAL_MODEL:-unknown}"
  echo "- PATH head: $(printf '%s' "$PATH" | cut -d: -f1-4)"
  echo
  echo "## Candidate Hooks"
  if [ -s "\${LOCAL_CONTEXT_FILE:-}" ]; then
    grep -E '^(###|####|- |[0-9a-f]{7,12} )' "$LOCAL_CONTEXT_FILE" 2>/dev/null | head -n 80 || true
  else
    echo "- No local context file was generated."
  fi
  echo
  echo "## Next Fix"
  echo "Start the same local OpenAI-compatible Qwen server used by the AI pane, or set LOCAL_LLM_URL / LOCAL_LLM_MODEL in ~/.shelly/agents/.env."
}

# Create directories before installing the failure trap so JSON logs have a target.
mkdir -p '${tmpDir}' '${locksDir}' "$LOG_DIR"
trap finish EXIT

# Source environment
[ -f "$ENV_FILE" ] && source "$ENV_FILE"
${apiKeyEnvScrub}

PROJECT_DIR="\${SHELLY_CONTENT_PROJECT:-$HOME/projects/shelly-content-studio}"
SOURCE_REGISTRY_FILE="\${SOURCE_REGISTRY_FILE:-$PROJECT_DIR/sources/source-registry.tsv}"
mkdir -p "$(dirname "$SOURCE_REGISTRY_FILE")"
touch "$SOURCE_REGISTRY_FILE"
SOURCE_CONTEXT=""
if [ -s "$SOURCE_REGISTRY_FILE" ]; then
  SOURCE_CONTEXT=$(printf '\\n\\nKnown source URLs already used. Avoid duplicates unless essential:\\n'; tail -n 120 "$SOURCE_REGISTRY_FILE" | awk -F '\\t' '{ if ($4 != "") print "- " $4 " (" $1 ", " $2 ")" }')
fi
LOCAL_CONTEXT_FILE="$TMP_DIR/local-context-$AGENT_ID.txt"
{
  echo
  echo "## Local project context"
  if [ -f "$PROJECT_DIR/AI_CONTEXT.md" ]; then
    echo
    echo "### AI_CONTEXT.md"
    head -c 8000 "$PROJECT_DIR/AI_CONTEXT.md" || true
    echo
  fi
  for dir in "$PROJECT_DIR/drafts/x" "$PROJECT_DIR/sources/x" "$PROJECT_DIR/drafts/articles" "\${OBSIDIAN_VAULT_PATH:-/sdcard/Documents/ObsidianVault}/30_Build_Log" "\${OBSIDIAN_VAULT_PATH:-/sdcard/Documents/ObsidianVault}/90_Log/Agent_Output"; do
    [ -d "$dir" ] || continue
    echo
    echo "### Recent files: $dir"
    find "$dir" -type f -name '*.md' 2>/dev/null | sort | tail -n 6 | while read -r file; do
      echo
      echo "#### $file"
      head -c 3000 "$file" || true
      echo
    done
  done
  for repo in "$HOME/hw" "$HOME/projects/shelly-content-studio"; do
    [ -d "$repo/.git" ] || continue
    echo
    echo "### Recent git log: $repo"
    git -C "$repo" log --oneline -8 2>/dev/null || true
    echo
    echo "### Current git status: $repo"
    git -C "$repo" status --short 2>/dev/null || true
  done
} > "$LOCAL_CONTEXT_FILE"
if [ -s "$LOCAL_CONTEXT_FILE" ]; then
  SOURCE_CONTEXT="$SOURCE_CONTEXT\\n\\n$(head -c 20000 "$LOCAL_CONTEXT_FILE")"
fi

# Global concurrency check
ACTIVE_COUNT=$(find "$LOCKS_DIR" -name '*.pid' -exec sh -c 'kill -0 $(cat "{}") 2>/dev/null && echo 1' \\; | wc -l)
if [ "$ACTIVE_COUNT" -ge "$MAX_CONCURRENT" ]; then
  TS=$(date +%s)
  TOOL_LABEL_JSON=$(json_escape_text "$TOOL_LABEL")
  cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"skipped","outputPreview":"global concurrency limit reached","durationMs":0,"toolUsed":"$TOOL_LABEL_JSON","routeDecision":$ROUTE_DECISION_JSON}
LOGEOF
  exit 0
fi

# Per-agent concurrency lock
if [ -f "$LOCK_FILE" ]; then
  OLD_PID=$(cat "$LOCK_FILE")
  if kill -0 "$OLD_PID" 2>/dev/null; then
    TS=$(date +%s)
    TOOL_LABEL_JSON=$(json_escape_text "$TOOL_LABEL")
    cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"skipped","outputPreview":"previous run still active","durationMs":0,"toolUsed":"$TOOL_LABEL_JSON","routeDecision":$ROUTE_DECISION_JSON}
LOGEOF
    exit 0
  fi
  rm -f "$LOCK_FILE"
fi

# Acquire lock
echo $$ > "$LOCK_FILE"

# Execute tool
rm -f "$BACKEND_ERROR_FILE"
${toolCommand}

# Check result
END_TIME=$(date +%s)
DURATION=$(( (END_TIME - START_TIME) * 1000 ))

if [ -f "$RESULT_FILE" ] && [ -s "$RESULT_FILE" ] && [ ! -f "$BACKEND_ERROR_FILE" ]; then
  PREVIEW=$(clean_result_preview "$RESULT_FILE")
  STATUS="success"
  ERROR_MESSAGE=""

  if ! dispatch_agent_action "$RESULT_FILE" "$PREVIEW"; then
    STATUS="\${ACTION_DISPATCH_STATUS:-error}"
    ERROR_MESSAGE="\${ACTION_DISPATCH_MESSAGE:-agent action dispatch failed}"
    PREVIEW="$ERROR_MESSAGE"
  fi
else
  if [ -f "$RESULT_FILE" ] && [ -s "$RESULT_FILE" ]; then
    PREVIEW=$(clean_result_preview "$RESULT_FILE")
  else
    PREVIEW="Agent produced no output. Check backend configuration and required commands. Tool=$TOOL_LABEL PATH=$PATH"
  fi
  ERROR_MESSAGE="$PREVIEW"
  STATUS="error"
  # ③b-2: a NON-final escalation attempt fails silently (no error notification) so
  # the user only sees the final outcome — the next tool's success, or the last
  # tool's failure. The TS run loop sets this for every attempt but the last.
  if [ "\${SUPPRESS_ERROR_NOTIFICATION:-0}" != "1" ]; then
    write_native_notification_request "error" "$PREVIEW" || true
  fi
fi

# Log run result
TS=$(date +%s)
PREVIEW_JSON=$(json_escape_text "$PREVIEW")
TOOL_LABEL_JSON=$(json_escape_text "$TOOL_LABEL")
ERROR_MESSAGE_JSON=$(json_escape_text "$ERROR_MESSAGE")
cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"$STATUS","outputPreview":"$PREVIEW_JSON","durationMs":$DURATION,"toolUsed":"$TOOL_LABEL_JSON","errorMessage":"$ERROR_MESSAGE_JSON","routeDecision":$ROUTE_DECISION_JSON}
LOGEOF

# Prune old logs (keep last 30)
ls -t "$LOG_DIR"/*.json 2>/dev/null | tail -n +31 | xargs rm -f 2>/dev/null || true

# Cleanup temp
rm -f "$RESULT_FILE" "$BACKEND_ERROR_FILE"
finish 0
`;
}

/**
 * Fail-closed script for an autonomous agent whose tool has no autonomous form
 * (an api-key backend — no key allowed in the autonomous path). Records the
 * refusal and exits non-zero so the run is logged as a failure, not silent.
 */
function refusalScript(
  agentId: string,
  resultFile: string,
  logDir: string,
  decision: AgentRouteDecision,
  toolType: string,
): string {
  const msg = `autonomous mode does not allow the '${toolType}' backend — no API keys in the autonomous agent path (Spec A). Use OAuth-Codex/local, or route via the credential broker.`;
  const toolLabel = toolChoiceToLabel({ type: toolType as ToolChoice['type'] } as ToolChoice);
  const routeDecisionJson = JSON.stringify({ ...decision, toolType, toolLabel });
  return `#!/bin/bash
# run-agent-${agentId}.sh — Shelly autonomous-mode refusal
SHELLY_AGENT_SCRIPT_VERSION=${AGENT_SCRIPT_VERSION}
ROUTE_DECISION_JSON=${shellQuote(routeDecisionJson)}
echo ${shellQuote(`[REFUSED] ${msg}`)} >&2
mkdir -p "$(dirname ${shellQuote(resultFile)})"
mkdir -p ${shellQuote(logDir)}
echo ${shellQuote(`[REFUSED] ${msg}`)} > ${shellQuote(resultFile)}
TS=$(date +%s)
cat > ${shellQuote(`${logDir}`)}/$TS.json << LOGEOF
{"agentId":${shellQuote(JSON.stringify(agentId))},"timestamp":\${TS}000,"status":"error","outputPreview":${shellQuote(JSON.stringify(`[REFUSED] ${msg}`))},"durationMs":0,"toolUsed":${shellQuote(JSON.stringify(toolLabel))},"errorMessage":${shellQuote(JSON.stringify(`[REFUSED] ${msg}`))},"routeDecision":$ROUTE_DECISION_JSON}
LOGEOF
exit 1
`;
}

function generateToolCommand(
  tool: ToolChoice,
  escapedPrompt: string,
  rawPrompt: string,
  options: ToolCommandOptions = { autonomous: false },
): string {
  const resultVar = '"$RESULT_FILE"';
  switch (tool.type) {
    case 'cli':
      return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
DRIVER_CWD="$PROJECT_DIR"
[ -d "$DRIVER_CWD" ] || DRIVER_CWD="$HOME"
if node_usable && [ -f "$HOME/.shelly-agent-driver.js" ]; then
  shelly_timeout_app_binary "$TIMEOUT" node "$HOME/.shelly-agent-driver.js" \\
    --cwd "$DRIVER_CWD" \\
    --approval-policy untrusted \\
    --agent-id "$AGENT_ID" \\
    --escalation-public-key-sha256 "\${SHELLY_AGENT_ESCALATION_PUBLIC_KEY_SHA256:-}" \\
    --audit-log "$LOG_DIR/agent-driver-audit.jsonl" \\
    --prompt-file "$PROMPT_FILE" > ${resultVar} 2>&1 || true
  mirror_driver_audit_to_app_private || true
  mirror_driver_audit_to_sdcard || true
else
  echo 'Shelly agent driver or bundled node is unavailable. Update Shelly runtime, then retry.' > ${resultVar}
fi
rm -f "$PROMPT_FILE"`;
    case 'gemini-api':
      return geminiApiCommand(escapedPrompt, resultVar, tool.model);
    case 'local':
      const localModel = (tool.model || (options.autonomous ? selectAutonomousLocalModel(rawPrompt) : LOCAL_MODEL_LIGHT)).replace(/"/g, '\\"');
      const localModelAssignment = options.autonomous
        ? `LOCAL_MODEL="\${SHELLY_AGENT_LOCAL_MODEL:-${localModel}}"`
        : `LOCAL_MODEL="\${LOCAL_LLM_MODEL:-${localModel}}"`;
      return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
	REQUEST_FILE="$HOME/.shelly/tmp/agent-request-$AGENT_ID.json"
	${localModelAssignment}
	# Cap the combined prompt + injected context so it cannot overflow the local
	# model's context window. The instruction (printed first) is always preserved;
	# only the trailing project/source context is truncated. A real run sent 7806
	# tokens into a small window and was rejected ("exceeds context size").
	# The cap is tier-aware: the small "work" tiers (0.8B/1.7B/2B) have an 8192
	# window, the heavier 4B/9B tiers only 4096, so they get a smaller char budget.
	# With a 2048 response reserve, ~16000 chars (~5k tokens) fits 8192 and ~7000
	# chars fits 4096. Genuinely large tasks escalate to a cloud backend (bigger
	# window) rather than being silently truncated to uselessness.
	# Match the small tiers FIRST: "0.8B" ends in the literal "8B", so a bare
	# *8[bB]* heavy-tier glob would false-match 0.8B and starve it. Mirror the
	# ordering in local_llm_runtime_profile, which lists 0.8b before 8b.
	case "$LOCAL_MODEL" in
	  *0.8[bB]*|*0-8[bB]*|*1.7[bB]*|*1-7[bB]*|*2[bB]*) LOCAL_PROMPT_MAX_CHARS="\${LOCAL_LLM_PROMPT_MAX_CHARS:-16000}" ;;
	  *4[bB]*|*8[bB]*|*9[bB]*) LOCAL_PROMPT_MAX_CHARS="\${LOCAL_LLM_PROMPT_MAX_CHARS:-7000}" ;;
	  *) LOCAL_PROMPT_MAX_CHARS="\${LOCAL_LLM_PROMPT_MAX_CHARS:-16000}" ;;
	esac
	# Write to a regular file first, THEN truncate by reading that file. Piping the
	# producers directly into "head -c" would SIGPIPE the printf writers once head
	# closes the pipe early (large context > pipe buffer) → exit 141 → under
	# 'set -euo pipefail' the whole run aborts BEFORE the fallback. Reading a
	# regular file with head has no producer to signal, so it is abort-safe.
	{ printf '%s\\n' '${escapedPrompt}'; printf '%s\\n' "$SOURCE_CONTEXT"; } > "$PROMPT_FILE.full"
	head -c "$LOCAL_PROMPT_MAX_CHARS" "$PROMPT_FILE.full" > "$PROMPT_FILE"
	rm -f "$PROMPT_FILE.full"
	PROMPT_JSON=$(json_string_file "$PROMPT_FILE")
	LOCAL_URL="\${LOCAL_LLM_URL:-http://127.0.0.1:8080}"
	printf '{\\"model\\":\\"%s\\",\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":%s}],\\"max_tokens\\":2048}' "$LOCAL_MODEL" "$PROMPT_JSON" > "$REQUEST_FILE"
		if ! ensure_local_llm_server "$LOCAL_URL" "$LOCAL_MODEL"; then
		  START_REASON=$(head -c 800 "$TMP_DIR/local-llm-start-$AGENT_ID.reason" 2>/dev/null | tr '\\n' ' ')
		  local_context_fallback "local llm start failed: $START_REASON" > ${resultVar}
		  touch "$BACKEND_ERROR_FILE"
		else
		  local_llm_start_activity_heartbeat 10
		  set +e
		  HTTP_TIMEOUT_SECONDS="$TIMEOUT" http_post_json "\${LOCAL_URL%/}/v1/chat/completions" "$REQUEST_FILE" "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
		  LOCAL_EXIT=$?
		  set -e
		  local_llm_stop_activity_heartbeat
		  if [ "$LOCAL_EXIT" -ne 0 ] || [ ! -s "$RESULT_FILE.response.json" ]; then
		    START_REASON=$(head -c 800 "$TMP_DIR/local-llm-start-$AGENT_ID.reason" 2>/dev/null | tr '\\n' ' ')
		    local_context_fallback "http exit=$LOCAL_EXIT $START_REASON $(head -c 240 "$RESULT_FILE.stderr" 2>/dev/null | tr '\\n' ' ')" > ${resultVar}
		    touch "$BACKEND_ERROR_FILE"
		  else
		    extract_ai_content "$RESULT_FILE.response.json" > ${resultVar} 2>> "$RESULT_FILE.stderr" || { touch "$BACKEND_ERROR_FILE"; [ -s ${resultVar} ] || cat "$RESULT_FILE.stderr" > ${resultVar}; }
		  fi
		fi
		rm -f "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
		rm -f "$PROMPT_FILE" "$REQUEST_FILE"`;
    case 'perplexity':
      const perplexityModel = tool.model || 'sonar';
		      return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
		REQUEST_FILE="$HOME/.shelly/tmp/agent-request-$AGENT_ID.json"
		printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
		PROMPT_JSON=$(json_string_file "$PROMPT_FILE")
		MODEL='${perplexityModel.replace(/'/g, "'\\''")}'
		if [ -z "\${PERPLEXITY_API_KEY:-}" ]; then
		  echo 'Perplexity API key is not set. Add PERPLEXITY_API_KEY to ~/.shelly/agents/.env.' > ${resultVar}
		  touch "$BACKEND_ERROR_FILE"
		else
		printf '{\\"model\\":\\"%s\\",\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":%s}]}' "$MODEL" "$PROMPT_JSON" > "$REQUEST_FILE"
		set +e
		HTTP_AUTH_HEADER="Bearer $PERPLEXITY_API_KEY" HTTP_TIMEOUT_SECONDS="$TIMEOUT" http_post_json "https://api.perplexity.ai/chat/completions" "$REQUEST_FILE" "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
		API_EXIT=$?
		set -e
		if [ "$API_EXIT" -ne 0 ] || [ ! -s "$RESULT_FILE.response.json" ]; then
		  touch "$BACKEND_ERROR_FILE"
		  echo "Perplexity API call failed with exit $API_EXIT: $(head -c 240 "$RESULT_FILE.stderr" 2>/dev/null | tr '\\n' ' ')" > ${resultVar}
		else
		  extract_ai_content "$RESULT_FILE.response.json" > ${resultVar} 2>> "$RESULT_FILE.stderr" || { touch "$BACKEND_ERROR_FILE"; [ -s ${resultVar} ] || cat "$RESULT_FILE.stderr" > ${resultVar}; }
		fi
		rm -f "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
		fi
		rm -f "$PROMPT_FILE" "$REQUEST_FILE"`;
    case 'cerebras':
      // Free-tier cloud tier of the ③ ladder (OpenAI-compatible). Used after
      // local when local can't fit/handle the task, BEFORE Codex (quota-preserving).
      return openAiCompatApiCommand(escapedPrompt, resultVar, {
        keyVar: 'CEREBRAS_API_KEY',
        envModelVar: 'CEREBRAS_MODEL',
        keyHint: 'Add CEREBRAS_API_KEY in Settings → API Keys (free tier at cloud.cerebras.ai).',
        url: 'https://api.cerebras.ai/v1/chat/completions',
        model: tool.model || 'qwen-3-235b-a22b-instruct-2507',
        label: 'Cerebras',
      });
    case 'groq':
      return openAiCompatApiCommand(escapedPrompt, resultVar, {
        keyVar: 'GROQ_API_KEY',
        envModelVar: 'GROQ_MODEL',
        keyHint: 'Add GROQ_API_KEY in Settings → API Keys (free tier at console.groq.com).',
        url: 'https://api.groq.com/openai/v1/chat/completions',
        model: tool.model || 'llama-3.3-70b-versatile',
        label: 'Groq',
      });
    case 'ab-article-eval':
      return articleEvalCommand(rawPrompt, resultVar, tool.localModel, tool.codexCmd);
    case 'auto':
      return `if [ -n "\${GEMINI_API_KEY:-}" ]; then
  ${geminiApiCommand(escapedPrompt, resultVar)}
elif command -v codex >/dev/null 2>&1; then
  PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
  printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
  timeout "$TIMEOUT" codex exec "$(cat "$PROMPT_FILE")" > ${resultVar} 2>&1 || true
  rm -f "$PROMPT_FILE"
else
  echo 'No background agent backend is configured. Add a Gemini API key, install Codex, or choose Local LLM/Perplexity explicitly.' > ${resultVar}
fi`;
  }
}

function articleEvalCommand(rawPrompt: string, resultVar: string, localModel?: string, codexCmd?: string): string {
  const promptMarker = `SHELLY_AB_PROMPT_${Math.random().toString(36).slice(2)}`;
  const localModelValue = (localModel || LOCAL_MODEL_BALANCED).replace(/"/g, '\\"');
  const codexCmdValue = (codexCmd || 'codex').replace(/"/g, '\\"');
  return `PROJECT_DIR="\${SHELLY_CONTENT_PROJECT:-$HOME/projects/shelly-content-studio}"
LOCAL_URL="\${LOCAL_LLM_URL:-http://127.0.0.1:8080}"
LOCAL_MODEL="\${SHELLY_AGENT_ARTICLE_EVAL_LOCAL_MODEL:-${localModelValue}}"
CODEX_CMD="\${CODEX_CMD:-${codexCmdValue}}"
RUN_TS=$(date +%Y%m%d-%H%M%S)
RUN_DIR="$PROJECT_DIR/evals/$RUN_TS-$SLUG"
mkdir -p "$RUN_DIR"

cat > "$RUN_DIR/user-request.md" <<'${promptMarker}'
${rawPrompt}
${promptMarker}

{
  echo '# Project Context'
  if [ -f "$PROJECT_DIR/AI_CONTEXT.md" ]; then cat "$PROJECT_DIR/AI_CONTEXT.md"; fi
  echo
  echo '# Recent Sources'
  for dir in "$PROJECT_DIR/sources" "\${OBSIDIAN_VAULT_PATH:-/sdcard/Documents/ObsidianVault}/20_Literature/Papers" "\${OBSIDIAN_VAULT_PATH:-/sdcard/Documents/ObsidianVault}/30_Build_Log"; do
    [ -d "$dir" ] || continue
    find "$dir" -type f -name '*.md' 2>/dev/null | sort | tail -n 8 | while read -r file; do
      echo
      echo "## Source: $file"
      head -c 6000 "$file" || true
      echo
    done
  done
} > "$RUN_DIR/context.md"

cat > "$RUN_DIR/prompt.md" <<'PROMPTEOF'
あなたは日本語のSubstack記事の編集者です。

目的:
STEAM x AIを、AI導入論ではなく「AIを理解したうえで基礎学力を再定義する議論」として記事化してください。

必須観点:
- 語彙力
- 読解力
- 想像力 / 創造力
- 判断力 / 批判的思考
- 公教育で長く重視されてきた基礎学力との接続

制約:
- 事実と解釈を分ける
- 引用元やURLが文脈に含まれる場合は活用する
- 過剰な断定やAI万能論を避ける
- 日本語で、公開前の下書きとして使える密度にする

PROMPTEOF
{
  echo
  echo '# User Request'
  cat "$RUN_DIR/user-request.md"
  echo
  cat "$RUN_DIR/context.md"
} >> "$RUN_DIR/prompt.md"

PROMPT_JSON=$(json_string_file "$RUN_DIR/prompt.md")
LOCAL_REQUEST_FILE="$RUN_DIR/local-request.json"
printf '{\\"model\\":\\"%s\\",\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":%s}],\\"temperature\\":0.7,\\"max_tokens\\":4096}' "$LOCAL_MODEL" "$PROMPT_JSON" > "$LOCAL_REQUEST_FILE"

LOCAL_START=$(date +%s)
if ensure_local_llm_server "$LOCAL_URL" "$LOCAL_MODEL"; then
  local_llm_start_activity_heartbeat 10
  set +e
  HTTP_TIMEOUT_SECONDS="$TIMEOUT" http_post_json "\${LOCAL_URL%/}/v1/chat/completions" "$LOCAL_REQUEST_FILE" "$RUN_DIR/local.response.json" "$RUN_DIR/local.stderr.log"
  LOCAL_EXIT=$?
  set -e
  local_llm_stop_activity_heartbeat
else
  LOCAL_EXIT=127
  START_REASON=$(head -c 800 "$TMP_DIR/local-llm-start-$AGENT_ID.reason" 2>/dev/null | tr '\\n' ' ')
  echo "Local LLM start failed: $START_REASON" > "$RUN_DIR/local.stderr.log"
fi
LOCAL_END=$(date +%s)
if [ "$LOCAL_EXIT" -eq 0 ]; then
  extract_ai_content "$RUN_DIR/local.response.json" > "$RUN_DIR/local-qwen.md" 2>> "$RUN_DIR/local.stderr.log" || true
else
  echo "Local LLM failed with exit $LOCAL_EXIT" > "$RUN_DIR/local-qwen.md"
fi

CODEX_START=$(date +%s)
set +e
if command -v "$CODEX_CMD" >/dev/null 2>&1; then
  timeout "$TIMEOUT" "$CODEX_CMD" exec "$(cat "$RUN_DIR/prompt.md")" > "$RUN_DIR/codex.md" 2> "$RUN_DIR/codex.stderr.log"
  CODEX_EXIT=$?
else
  echo "Codex CLI not found: $CODEX_CMD" > "$RUN_DIR/codex.md"
  echo "Codex CLI not found: $CODEX_CMD" > "$RUN_DIR/codex.stderr.log"
  CODEX_EXIT=127
fi
set -e
CODEX_END=$(date +%s)

local_bytes=$(wc -c < "$RUN_DIR/local-qwen.md" | tr -d ' ')
codex_bytes=$(wc -c < "$RUN_DIR/codex.md" | tr -d ' ')
local_headings=$(grep -c '^#' "$RUN_DIR/local-qwen.md" 2>/dev/null || true)
codex_headings=$(grep -c '^#' "$RUN_DIR/codex.md" 2>/dev/null || true)
local_links=$(grep -Eo 'https?://[^ )]+' "$RUN_DIR/local-qwen.md" 2>/dev/null | wc -l | tr -d ' ')
codex_links=$(grep -Eo 'https?://[^ )]+' "$RUN_DIR/codex.md" 2>/dev/null | wc -l | tr -d ' ')

cat > "$RUN_DIR/metrics.json" <<METRICSEOF
{"agentId":"$AGENT_ID","timestamp":"$RUN_TS","localModel":"$LOCAL_MODEL","codexCmd":"$CODEX_CMD","localExit":$LOCAL_EXIT,"codexExit":$CODEX_EXIT,"localDurationSec":$((LOCAL_END - LOCAL_START)),"codexDurationSec":$((CODEX_END - CODEX_START)),"localBytes":$local_bytes,"codexBytes":$codex_bytes,"localHeadings":$local_headings,"codexHeadings":$codex_headings,"localLinks":$local_links,"codexLinks":$codex_links}
METRICSEOF

cat > "$RUN_DIR/eval.md" <<EVALEOF
# A/B Evaluation

## Metrics
\`\`\`json
$(cat "$RUN_DIR/metrics.json")
\`\`\`

## Quick Read
- Qwen/local output: $RUN_DIR/local-qwen.md
- Codex output: $RUN_DIR/codex.md
- Prompt: $RUN_DIR/prompt.md
- Context: $RUN_DIR/context.md

## Manual Rubric
- Thesis alignment: AI-era STEAM = foundational academic ability
- Source faithfulness
- Japanese readability
- Article structure
- Originality
- Publishability
EVALEOF

cat > ${resultVar} <<RESULTEOF
# Qwen3 local vs Codex A/B Article Eval

Run directory: $RUN_DIR

## Verdict Stub
Review \`eval.md\`, \`local-qwen.md\`, and \`codex.md\`.

## Metrics
\`\`\`json
$(cat "$RUN_DIR/metrics.json")
\`\`\`

## Local Qwen Preview
$(head -n 40 "$RUN_DIR/local-qwen.md")

## Codex Preview
$(head -n 40 "$RUN_DIR/codex.md")
RESULTEOF`;
}

/**
 * OpenAI-compatible chat-completions backend (Cerebras / Groq). Mirrors the
 * perplexity flow: source key from env, POST, extract content, fail-closed if no
 * key (graceful error + BACKEND_ERROR_FILE so the ladder can escalate). The key
 * is read from env (synced from Settings) and never logged.
 */
function openAiCompatApiCommand(
  escapedPrompt: string,
  resultVar: string,
  opts: { keyVar: string; envModelVar: string; keyHint: string; url: string; model: string; label: string },
): string {
  const model = opts.model.replace(/"/g, '\\"');
  const keyHint = opts.keyHint.replace(/'/g, "'\\''");
  const url = opts.url.replace(/"/g, '\\"');
  const label = opts.label.replace(/"/g, '\\"');
  return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
	REQUEST_FILE="$HOME/.shelly/tmp/agent-request-$AGENT_ID.json"
	printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
	PROMPT_JSON=$(json_string_file "$PROMPT_FILE")
	MODEL="\${${opts.envModelVar}:-${model}}"
	if [ -z "\${${opts.keyVar}:-}" ]; then
	  echo '${keyHint}' > ${resultVar}
	  touch "$BACKEND_ERROR_FILE"
	else
	printf '{\\"model\\":\\"%s\\",\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":%s}]}' "$MODEL" "$PROMPT_JSON" > "$REQUEST_FILE"
	set +e
	HTTP_AUTH_HEADER="Bearer $${opts.keyVar}" HTTP_TIMEOUT_SECONDS="$TIMEOUT" http_post_json "${url}" "$REQUEST_FILE" "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
	API_EXIT=$?
	set -e
	if [ "$API_EXIT" -ne 0 ] || [ ! -s "$RESULT_FILE.response.json" ]; then
	  touch "$BACKEND_ERROR_FILE"
	  echo "${label} API call failed with exit $API_EXIT: $(head -c 240 "$RESULT_FILE.stderr" 2>/dev/null | tr '\\n' ' ')" > ${resultVar}
	else
	  extract_ai_content "$RESULT_FILE.response.json" > ${resultVar} 2>> "$RESULT_FILE.stderr" || { touch "$BACKEND_ERROR_FILE"; [ -s ${resultVar} ] || cat "$RESULT_FILE.stderr" > ${resultVar}; }
	fi
	rm -f "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
	fi
	rm -f "$PROMPT_FILE" "$REQUEST_FILE"`;
}

function geminiApiCommand(escapedPrompt: string, resultVar: string, model?: string): string {
  const defaultModel = model || 'gemini-2.0-flash';
  return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
REQUEST_FILE="$HOME/.shelly/tmp/agent-request-$AGENT_ID.json"
printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
PROMPT_JSON=$(json_string_file "$PROMPT_FILE")
MODEL="\${GEMINI_MODEL:-${defaultModel.replace(/"/g, '\\"')}}"
if [ -z "\${GEMINI_API_KEY:-}" ]; then
  echo 'Gemini API key is not set. Add it in Settings before running background agents.' > ${resultVar}
  touch "$BACKEND_ERROR_FILE"
else
  printf '{\\"contents\\":[{\\"role\\":\\"user\\",\\"parts\\":[{\\"text\\":%s}]}],\\"generationConfig\\":{\\"maxOutputTokens\\":4096,\\"temperature\\":0.7}}' "$PROMPT_JSON" > "$REQUEST_FILE"
  set +e
  HTTP_EXTRA_HEADERS="x-goog-api-key: $GEMINI_API_KEY" HTTP_TIMEOUT_SECONDS="$TIMEOUT" http_post_json "https://generativelanguage.googleapis.com/v1beta/models/$MODEL:generateContent" "$REQUEST_FILE" "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
  API_EXIT=$?
  set -e
  if [ "$API_EXIT" -ne 0 ] || [ ! -s "$RESULT_FILE.response.json" ]; then
    touch "$BACKEND_ERROR_FILE"
    echo "Gemini API call failed with exit $API_EXIT: $(head -c 240 "$RESULT_FILE.stderr" 2>/dev/null | tr '\\n' ' ')" > ${resultVar}
  else
    extract_ai_content "$RESULT_FILE.response.json" > ${resultVar} 2>> "$RESULT_FILE.stderr" || { touch "$BACKEND_ERROR_FILE"; [ -s ${resultVar} ] || cat "$RESULT_FILE.stderr" > ${resultVar}; }
  fi
  rm -f "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
fi
rm -f "$PROMPT_FILE" "$REQUEST_FILE"`;
}

export function getScriptPath(agentId: string): string {
  return `${paths().agentsDir}/run-agent-${agentId}.sh`;
}

export function generateInstallCommands(agent: Agent): string[] {
  const { agentsDir, tmpDir, locksDir, logsDir } = paths();
  const scriptPath = getScriptPath(agent.id);
  return [
    `mkdir -p '${agentsDir}' '${tmpDir}' '${locksDir}' '${logsDir}/${agent.id}'`,
    `chmod +x '${scriptPath}'`,
  ];
}

export function generateStopCommand(agentId: string): string {
  const pidFile = `${paths().locksDir}/${agentId}.pid`;
  return `pid_file=${shellQuote(pidFile)}; if [ -f "$pid_file" ]; then pid="$(cat "$pid_file")"; kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true; sleep 1; kill -KILL -- "-$pid" 2>/dev/null || kill -KILL "$pid" 2>/dev/null || true; rm -f "$pid_file"; fi`;
}
