/**
 * lib/agent-output-writer.ts — Saves agent results to user-specified locations.
 * Handles template rendering and directory creation.
 */
import { Agent } from '@/store/types';

const DEFAULT_TEMPLATE = `---
date: {{date}}
agent: {{agent_name}}
tool: {{tool_used}}
---

# {{agent_name}} — {{date}}

{{content}}

---
*Generated by Shelly Background Agent at {{timestamp}}*
`;

export interface OutputContext {
  date: string;        // YYYY-MM-DD
  timestamp: string;   // ISO 8601
  agentName: string;
  toolUsed: string;
  content: string;
}

export function renderTemplate(template: string | null, ctx: OutputContext): string {
  const tmpl = template || DEFAULT_TEMPLATE;
  return tmpl
    .replace(/\{\{date\}\}/g, ctx.date)
    .replace(/\{\{timestamp\}\}/g, ctx.timestamp)
    .replace(/\{\{agent_name\}\}/g, ctx.agentName)
    .replace(/\{\{tool_used\}\}/g, ctx.toolUsed)
    .replace(/\{\{content\}\}/g, ctx.content);
}

export function generateFilename(agent: Agent): string {
  const date = new Date().toISOString().slice(0, 10);
  const slug = agent.name
    .toLowerCase()
    .replace(/[^a-z0-9\u3040-\u9fff]+/g, '-')
    .replace(/^-|-$/g, '');
  return `${date}-${slug}.md`;
}
