/**
 * lib/theme-engine.ts — JSON-based theme system
 *
 * Built-in themes + custom theme loading.
 * WezTerm-inspired theming with full color control.
 */
import { create } from 'zustand';
import AsyncStorage from '@react-native-async-storage/async-storage';

// ── Theme Definition ─────────────────────────────────────────────────────────

export interface ThemeColors {
  /** Main background */
  background: string;
  /** Card/surface background */
  surface: string;
  /** Elevated surface (modals, menus) */
  surfaceAlt: string;
  /** Primary foreground text */
  foreground: string;
  /** Muted/secondary text */
  muted: string;
  /** Accent color (buttons, highlights) */
  accent: string;
  /** Border color */
  border: string;
  /** Success color */
  success: string;
  /** Warning color */
  warning: string;
  /** Error color */
  error: string;
  /** Shell prompt color */
  prompt: string;
  /** Command text color */
  command: string;
  /** Inactive tab/element color */
  inactive: string;

  // ── ANSI Terminal Colors ─────────────────────────────────────────
  ansiBlack: string;
  ansiRed: string;
  ansiGreen: string;
  ansiYellow: string;
  ansiBlue: string;
  ansiMagenta: string;
  ansiCyan: string;
  ansiWhite: string;
  ansiBrightBlack: string;
  ansiBrightRed: string;
  ansiBrightGreen: string;
  ansiBrightYellow: string;
  ansiBrightBlue: string;
  ansiBrightMagenta: string;
  ansiBrightCyan: string;
  ansiBrightWhite: string;
}

export interface Theme {
  id: string;
  name: string;
  author?: string;
  type: 'dark' | 'light';
  colors: ThemeColors;
}

// ── Built-in Themes ──────────────────────────────────────────────────────────

const DEFAULT_ANSI = {
  ansiBlack: '#000000',
  ansiRed: '#FF5555',
  ansiGreen: '#50FA7B',
  ansiYellow: '#F1FA8C',
  ansiBlue: '#BD93F9',
  ansiMagenta: '#FF79C6',
  ansiCyan: '#8BE9FD',
  ansiWhite: '#F8F8F2',
  ansiBrightBlack: '#6272A4',
  ansiBrightRed: '#FF6E6E',
  ansiBrightGreen: '#69FF94',
  ansiBrightYellow: '#FFFFA5',
  ansiBrightBlue: '#D6ACFF',
  ansiBrightMagenta: '#FF92DF',
  ansiBrightCyan: '#A4FFFF',
  ansiBrightWhite: '#FFFFFF',
};

export const BUILTIN_THEMES: Theme[] = [
  {
    id: 'shelly-default',
    name: 'Shelly Default',
    type: 'dark',
    colors: {
      background: '#0A0A0A',
      surface: '#111111',
      surfaceAlt: '#1A1A1A',
      foreground: '#E8E8E8',
      muted: '#6B7280',
      accent: '#00D4AA',
      border: '#1E1E1E',
      success: '#4ADE80',
      warning: '#FBBF24',
      error: '#F87171',
      prompt: '#00D4AA',
      command: '#93C5FD',
      inactive: '#4B5563',
      ...DEFAULT_ANSI,
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    author: 'Zeno Rocha',
    type: 'dark',
    colors: {
      background: '#282A36',
      surface: '#2D2F3D',
      surfaceAlt: '#343746',
      foreground: '#F8F8F2',
      muted: '#6272A4',
      accent: '#BD93F9',
      border: '#44475A',
      success: '#50FA7B',
      warning: '#F1FA8C',
      error: '#FF5555',
      prompt: '#50FA7B',
      command: '#8BE9FD',
      inactive: '#6272A4',
      ansiBlack: '#21222C',
      ansiRed: '#FF5555',
      ansiGreen: '#50FA7B',
      ansiYellow: '#F1FA8C',
      ansiBlue: '#BD93F9',
      ansiMagenta: '#FF79C6',
      ansiCyan: '#8BE9FD',
      ansiWhite: '#F8F8F2',
      ansiBrightBlack: '#6272A4',
      ansiBrightRed: '#FF6E6E',
      ansiBrightGreen: '#69FF94',
      ansiBrightYellow: '#FFFFA5',
      ansiBrightBlue: '#D6ACFF',
      ansiBrightMagenta: '#FF92DF',
      ansiBrightCyan: '#A4FFFF',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    author: 'Ethan Schoonover',
    type: 'dark',
    colors: {
      background: '#002B36',
      surface: '#073642',
      surfaceAlt: '#0A3F4E',
      foreground: '#839496',
      muted: '#586E75',
      accent: '#2AA198',
      border: '#073642',
      success: '#859900',
      warning: '#B58900',
      error: '#DC322F',
      prompt: '#859900',
      command: '#268BD2',
      inactive: '#586E75',
      ansiBlack: '#073642',
      ansiRed: '#DC322F',
      ansiGreen: '#859900',
      ansiYellow: '#B58900',
      ansiBlue: '#268BD2',
      ansiMagenta: '#D33682',
      ansiCyan: '#2AA198',
      ansiWhite: '#EEE8D5',
      ansiBrightBlack: '#002B36',
      ansiBrightRed: '#CB4B16',
      ansiBrightGreen: '#586E75',
      ansiBrightYellow: '#657B83',
      ansiBrightBlue: '#839496',
      ansiBrightMagenta: '#6C71C4',
      ansiBrightCyan: '#93A1A1',
      ansiBrightWhite: '#FDF6E3',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    author: 'Arctic Ice Studio',
    type: 'dark',
    colors: {
      background: '#2E3440',
      surface: '#3B4252',
      surfaceAlt: '#434C5E',
      foreground: '#D8DEE9',
      muted: '#4C566A',
      accent: '#88C0D0',
      border: '#3B4252',
      success: '#A3BE8C',
      warning: '#EBCB8B',
      error: '#BF616A',
      prompt: '#A3BE8C',
      command: '#81A1C1',
      inactive: '#4C566A',
      ansiBlack: '#3B4252',
      ansiRed: '#BF616A',
      ansiGreen: '#A3BE8C',
      ansiYellow: '#EBCB8B',
      ansiBlue: '#81A1C1',
      ansiMagenta: '#B48EAD',
      ansiCyan: '#88C0D0',
      ansiWhite: '#E5E9F0',
      ansiBrightBlack: '#4C566A',
      ansiBrightRed: '#BF616A',
      ansiBrightGreen: '#A3BE8C',
      ansiBrightYellow: '#EBCB8B',
      ansiBrightBlue: '#81A1C1',
      ansiBrightMagenta: '#B48EAD',
      ansiBrightCyan: '#8FBCBB',
      ansiBrightWhite: '#ECEFF4',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    author: 'Catppuccin',
    type: 'dark',
    colors: {
      background: '#1E1E2E',
      surface: '#262637',
      surfaceAlt: '#313244',
      foreground: '#CDD6F4',
      muted: '#585B70',
      accent: '#CBA6F7',
      border: '#313244',
      success: '#A6E3A1',
      warning: '#F9E2AF',
      error: '#F38BA8',
      prompt: '#A6E3A1',
      command: '#89B4FA',
      inactive: '#585B70',
      ansiBlack: '#45475A',
      ansiRed: '#F38BA8',
      ansiGreen: '#A6E3A1',
      ansiYellow: '#F9E2AF',
      ansiBlue: '#89B4FA',
      ansiMagenta: '#F5C2E7',
      ansiCyan: '#94E2D5',
      ansiWhite: '#BAC2DE',
      ansiBrightBlack: '#585B70',
      ansiBrightRed: '#F38BA8',
      ansiBrightGreen: '#A6E3A1',
      ansiBrightYellow: '#F9E2AF',
      ansiBrightBlue: '#89B4FA',
      ansiBrightMagenta: '#F5C2E7',
      ansiBrightCyan: '#94E2D5',
      ansiBrightWhite: '#A6ADC8',
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    type: 'dark',
    colors: {
      background: '#000000',
      surface: '#0A0A0A',
      surfaceAlt: '#141414',
      foreground: '#FFFFFF',
      muted: '#999999',
      accent: '#00FF88',
      border: '#444444',
      success: '#00FF00',
      warning: '#FFFF00',
      error: '#FF0000',
      prompt: '#00FF88',
      command: '#00CCFF',
      inactive: '#666666',
      ansiBlack: '#000000',
      ansiRed: '#FF0000',
      ansiGreen: '#00FF00',
      ansiYellow: '#FFFF00',
      ansiBlue: '#0088FF',
      ansiMagenta: '#FF00FF',
      ansiCyan: '#00FFFF',
      ansiWhite: '#FFFFFF',
      ansiBrightBlack: '#555555',
      ansiBrightRed: '#FF5555',
      ansiBrightGreen: '#55FF55',
      ansiBrightYellow: '#FFFF55',
      ansiBrightBlue: '#5555FF',
      ansiBrightMagenta: '#FF55FF',
      ansiBrightCyan: '#55FFFF',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    author: 'Atom',
    type: 'dark',
    colors: {
      background: '#282C34',
      surface: '#2C313A',
      surfaceAlt: '#353B45',
      foreground: '#ABB2BF',
      muted: '#5C6370',
      accent: '#61AFEF',
      border: '#3E4451',
      success: '#98C379',
      warning: '#E5C07B',
      error: '#E06C75',
      prompt: '#98C379',
      command: '#61AFEF',
      inactive: '#5C6370',
      ansiBlack: '#282C34',
      ansiRed: '#E06C75',
      ansiGreen: '#98C379',
      ansiYellow: '#E5C07B',
      ansiBlue: '#61AFEF',
      ansiMagenta: '#C678DD',
      ansiCyan: '#56B6C2',
      ansiWhite: '#ABB2BF',
      ansiBrightBlack: '#5C6370',
      ansiBrightRed: '#BE5046',
      ansiBrightGreen: '#98C379',
      ansiBrightYellow: '#D19A66',
      ansiBrightBlue: '#61AFEF',
      ansiBrightMagenta: '#C678DD',
      ansiBrightCyan: '#56B6C2',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    author: 'morhetz',
    type: 'dark',
    colors: {
      background: '#282828',
      surface: '#3C3836',
      surfaceAlt: '#504945',
      foreground: '#EBDBB2',
      muted: '#928374',
      accent: '#FE8019',
      border: '#3C3836',
      success: '#B8BB26',
      warning: '#FABD2F',
      error: '#FB4934',
      prompt: '#B8BB26',
      command: '#83A598',
      inactive: '#928374',
      ansiBlack: '#282828',
      ansiRed: '#CC241D',
      ansiGreen: '#98971A',
      ansiYellow: '#D79921',
      ansiBlue: '#458588',
      ansiMagenta: '#B16286',
      ansiCyan: '#689D6A',
      ansiWhite: '#A89984',
      ansiBrightBlack: '#928374',
      ansiBrightRed: '#FB4934',
      ansiBrightGreen: '#B8BB26',
      ansiBrightYellow: '#FABD2F',
      ansiBrightBlue: '#83A598',
      ansiBrightMagenta: '#D3869B',
      ansiBrightCyan: '#8EC07C',
      ansiBrightWhite: '#EBDBB2',
    },
  },
  {
    id: 'tokyonight',
    name: 'Tokyo Night',
    author: 'folke',
    type: 'dark',
    colors: {
      background: '#1A1B26',
      surface: '#1F2335',
      surfaceAlt: '#292E42',
      foreground: '#C0CAF5',
      muted: '#565F89',
      accent: '#7AA2F7',
      border: '#292E42',
      success: '#9ECE6A',
      warning: '#E0AF68',
      error: '#F7768E',
      prompt: '#9ECE6A',
      command: '#7AA2F7',
      inactive: '#565F89',
      ansiBlack: '#15161E',
      ansiRed: '#F7768E',
      ansiGreen: '#9ECE6A',
      ansiYellow: '#E0AF68',
      ansiBlue: '#7AA2F7',
      ansiMagenta: '#BB9AF7',
      ansiCyan: '#7DCFFF',
      ansiWhite: '#A9B1D6',
      ansiBrightBlack: '#414868',
      ansiBrightRed: '#F7768E',
      ansiBrightGreen: '#9ECE6A',
      ansiBrightYellow: '#E0AF68',
      ansiBrightBlue: '#7AA2F7',
      ansiBrightMagenta: '#BB9AF7',
      ansiBrightCyan: '#7DCFFF',
      ansiBrightWhite: '#C0CAF5',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    author: 'Wimer Hazenberg',
    type: 'dark',
    colors: {
      background: '#272822',
      surface: '#2D2E27',
      surfaceAlt: '#383930',
      foreground: '#F8F8F2',
      muted: '#75715E',
      accent: '#A6E22E',
      border: '#3E3D32',
      success: '#A6E22E',
      warning: '#E6DB74',
      error: '#F92672',
      prompt: '#A6E22E',
      command: '#66D9EF',
      inactive: '#75715E',
      ansiBlack: '#272822',
      ansiRed: '#F92672',
      ansiGreen: '#A6E22E',
      ansiYellow: '#F4BF75',
      ansiBlue: '#66D9EF',
      ansiMagenta: '#AE81FF',
      ansiCyan: '#A1EFE4',
      ansiWhite: '#F8F8F2',
      ansiBrightBlack: '#75715E',
      ansiBrightRed: '#F92672',
      ansiBrightGreen: '#A6E22E',
      ansiBrightYellow: '#F4BF75',
      ansiBrightBlue: '#66D9EF',
      ansiBrightMagenta: '#AE81FF',
      ansiBrightCyan: '#A1EFE4',
      ansiBrightWhite: '#F9F8F5',
    },
  },
  {
    id: 'material-dark',
    name: 'Material Dark',
    author: 'Mattia Astorino',
    type: 'dark',
    colors: {
      background: '#212121',
      surface: '#292929',
      surfaceAlt: '#333333',
      foreground: '#EEFFFF',
      muted: '#545454',
      accent: '#89DDFF',
      border: '#2C2C2C',
      success: '#C3E88D',
      warning: '#FFCB6B',
      error: '#F07178',
      prompt: '#C3E88D',
      command: '#82AAFF',
      inactive: '#545454',
      ansiBlack: '#212121',
      ansiRed: '#F07178',
      ansiGreen: '#C3E88D',
      ansiYellow: '#FFCB6B',
      ansiBlue: '#82AAFF',
      ansiMagenta: '#C792EA',
      ansiCyan: '#89DDFF',
      ansiWhite: '#EEFFFF',
      ansiBrightBlack: '#545454',
      ansiBrightRed: '#F07178',
      ansiBrightGreen: '#C3E88D',
      ansiBrightYellow: '#FFCB6B',
      ansiBrightBlue: '#82AAFF',
      ansiBrightMagenta: '#C792EA',
      ansiBrightCyan: '#89DDFF',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    author: 'GitHub',
    type: 'dark',
    colors: {
      background: '#0D1117',
      surface: '#161B22',
      surfaceAlt: '#21262D',
      foreground: '#C9D1D9',
      muted: '#8B949E',
      accent: '#58A6FF',
      border: '#30363D',
      success: '#3FB950',
      warning: '#D29922',
      error: '#F85149',
      prompt: '#3FB950',
      command: '#58A6FF',
      inactive: '#484F58',
      ansiBlack: '#0D1117',
      ansiRed: '#FF7B72',
      ansiGreen: '#3FB950',
      ansiYellow: '#D29922',
      ansiBlue: '#58A6FF',
      ansiMagenta: '#BC8CFF',
      ansiCyan: '#39C5CF',
      ansiWhite: '#B1BAC4',
      ansiBrightBlack: '#6E7681',
      ansiBrightRed: '#FFA198',
      ansiBrightGreen: '#56D364',
      ansiBrightYellow: '#E3B341',
      ansiBrightBlue: '#79C0FF',
      ansiBrightMagenta: '#D2A8FF',
      ansiBrightCyan: '#56D4DD',
      ansiBrightWhite: '#F0F6FC',
    },
  },
  {
    id: 'ayu-dark',
    name: 'Ayu Dark',
    author: 'dempfi',
    type: 'dark',
    colors: {
      background: '#0A0E14',
      surface: '#0D1017',
      surfaceAlt: '#131721',
      foreground: '#B3B1AD',
      muted: '#5C6773',
      accent: '#E6B450',
      border: '#1D2433',
      success: '#AAD94C',
      warning: '#FFB454',
      error: '#D95757',
      prompt: '#AAD94C',
      command: '#59C2FF',
      inactive: '#5C6773',
      ansiBlack: '#0A0E14',
      ansiRed: '#D95757',
      ansiGreen: '#AAD94C',
      ansiYellow: '#FFB454',
      ansiBlue: '#59C2FF',
      ansiMagenta: '#D2A6FF',
      ansiCyan: '#95E6CB',
      ansiWhite: '#B3B1AD',
      ansiBrightBlack: '#5C6773',
      ansiBrightRed: '#F07178',
      ansiBrightGreen: '#C2D94C',
      ansiBrightYellow: '#FFD580',
      ansiBrightBlue: '#73D0FF',
      ansiBrightMagenta: '#D2A6FF',
      ansiBrightCyan: '#95E6CB',
      ansiBrightWhite: '#E6E1CF',
    },
  },
  {
    id: 'synthwave-84',
    name: 'SynthWave 84',
    author: 'Robb Owen',
    type: 'dark',
    colors: {
      background: '#262335',
      surface: '#2A2139',
      surfaceAlt: '#34294F',
      foreground: '#F0E3FF',
      muted: '#848BBD',
      accent: '#FF7EDB',
      border: '#34294F',
      success: '#72F1B8',
      warning: '#FEDE5D',
      error: '#FE4450',
      prompt: '#72F1B8',
      command: '#36F9F6',
      inactive: '#495495',
      ansiBlack: '#262335',
      ansiRed: '#FE4450',
      ansiGreen: '#72F1B8',
      ansiYellow: '#FEDE5D',
      ansiBlue: '#03AEFF',
      ansiMagenta: '#FF7EDB',
      ansiCyan: '#36F9F6',
      ansiWhite: '#F0E3FF',
      ansiBrightBlack: '#848BBD',
      ansiBrightRed: '#FE4450',
      ansiBrightGreen: '#72F1B8',
      ansiBrightYellow: '#FEDE5D',
      ansiBrightBlue: '#03AEFF',
      ansiBrightMagenta: '#FF7EDB',
      ansiBrightCyan: '#36F9F6',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'cobalt2',
    name: 'Cobalt2',
    author: 'Wes Bos',
    type: 'dark',
    colors: {
      background: '#193549',
      surface: '#1F4662',
      surfaceAlt: '#245578',
      foreground: '#FFFFFF',
      muted: '#6699CC',
      accent: '#FFC600',
      border: '#1F4662',
      success: '#3AD900',
      warning: '#FFC600',
      error: '#FF628C',
      prompt: '#3AD900',
      command: '#80FCFF',
      inactive: '#6699CC',
      ansiBlack: '#000000',
      ansiRed: '#FF628C',
      ansiGreen: '#3AD900',
      ansiYellow: '#FFC600',
      ansiBlue: '#0088FF',
      ansiMagenta: '#FF9D00',
      ansiCyan: '#80FCFF',
      ansiWhite: '#FFFFFF',
      ansiBrightBlack: '#6699CC',
      ansiBrightRed: '#FF9D00',
      ansiBrightGreen: '#A5FF90',
      ansiBrightYellow: '#FFFF00',
      ansiBrightBlue: '#9DF0FF',
      ansiBrightMagenta: '#FF2F92',
      ansiBrightCyan: '#80FCFF',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'tomorrow-night',
    name: 'Tomorrow Night',
    author: 'Chris Kempson',
    type: 'dark',
    colors: {
      background: '#1D1F21',
      surface: '#232527',
      surfaceAlt: '#2B2D2F',
      foreground: '#C5C8C6',
      muted: '#969896',
      accent: '#81A2BE',
      border: '#282A2E',
      success: '#B5BD68',
      warning: '#F0C674',
      error: '#CC6666',
      prompt: '#B5BD68',
      command: '#81A2BE',
      inactive: '#969896',
      ansiBlack: '#1D1F21',
      ansiRed: '#CC6666',
      ansiGreen: '#B5BD68',
      ansiYellow: '#F0C674',
      ansiBlue: '#81A2BE',
      ansiMagenta: '#B294BB',
      ansiCyan: '#8ABEB7',
      ansiWhite: '#C5C8C6',
      ansiBrightBlack: '#969896',
      ansiBrightRed: '#DE935F',
      ansiBrightGreen: '#B5BD68',
      ansiBrightYellow: '#F0C674',
      ansiBrightBlue: '#81A2BE',
      ansiBrightMagenta: '#B294BB',
      ansiBrightCyan: '#8ABEB7',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'palenight',
    name: 'Palenight',
    author: 'Mattia Astorino',
    type: 'dark',
    colors: {
      background: '#292D3E',
      surface: '#2F3344',
      surfaceAlt: '#373B4D',
      foreground: '#A6ACCD',
      muted: '#676E95',
      accent: '#82AAFF',
      border: '#3A3F58',
      success: '#C3E88D',
      warning: '#FFCB6B',
      error: '#F07178',
      prompt: '#C3E88D',
      command: '#82AAFF',
      inactive: '#676E95',
      ansiBlack: '#292D3E',
      ansiRed: '#F07178',
      ansiGreen: '#C3E88D',
      ansiYellow: '#FFCB6B',
      ansiBlue: '#82AAFF',
      ansiMagenta: '#C792EA',
      ansiCyan: '#89DDFF',
      ansiWhite: '#A6ACCD',
      ansiBrightBlack: '#676E95',
      ansiBrightRed: '#FF8B92',
      ansiBrightGreen: '#DDFFA7',
      ansiBrightYellow: '#FFE585',
      ansiBrightBlue: '#9CC4FF',
      ansiBrightMagenta: '#E1ACFF',
      ansiBrightCyan: '#A3F7FF',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'horizon',
    name: 'Horizon',
    author: 'jolaleye',
    type: 'dark',
    colors: {
      background: '#1C1E26',
      surface: '#232530',
      surfaceAlt: '#2E303E',
      foreground: '#D5D8DA',
      muted: '#6C6F93',
      accent: '#E95678',
      border: '#2E303E',
      success: '#29D398',
      warning: '#FAB795',
      error: '#E95678',
      prompt: '#29D398',
      command: '#26BBD9',
      inactive: '#6C6F93',
      ansiBlack: '#1C1E26',
      ansiRed: '#E95678',
      ansiGreen: '#29D398',
      ansiYellow: '#FAB795',
      ansiBlue: '#26BBD9',
      ansiMagenta: '#EE64AC',
      ansiCyan: '#59E3E3',
      ansiWhite: '#D5D8DA',
      ansiBrightBlack: '#6C6F93',
      ansiBrightRed: '#EC6A88',
      ansiBrightGreen: '#3FDAA4',
      ansiBrightYellow: '#FBC3A7',
      ansiBrightBlue: '#3FC6DE',
      ansiBrightMagenta: '#F075B7',
      ansiBrightCyan: '#6BE6E6',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'everforest-dark',
    name: 'Everforest Dark',
    author: 'sainnhe',
    type: 'dark',
    colors: {
      background: '#2D353B',
      surface: '#343F44',
      surfaceAlt: '#3D484D',
      foreground: '#D3C6AA',
      muted: '#859289',
      accent: '#A7C080',
      border: '#3D484D',
      success: '#A7C080',
      warning: '#DBBC7F',
      error: '#E67E80',
      prompt: '#A7C080',
      command: '#7FBBB3',
      inactive: '#859289',
      ansiBlack: '#2D353B',
      ansiRed: '#E67E80',
      ansiGreen: '#A7C080',
      ansiYellow: '#DBBC7F',
      ansiBlue: '#7FBBB3',
      ansiMagenta: '#D699B6',
      ansiCyan: '#83C092',
      ansiWhite: '#D3C6AA',
      ansiBrightBlack: '#859289',
      ansiBrightRed: '#E67E80',
      ansiBrightGreen: '#A7C080',
      ansiBrightYellow: '#DBBC7F',
      ansiBrightBlue: '#7FBBB3',
      ansiBrightMagenta: '#D699B6',
      ansiBrightCyan: '#83C092',
      ansiBrightWhite: '#E4DCC8',
    },
  },
  {
    id: 'kanagawa',
    name: 'Kanagawa',
    author: 'rebelot',
    type: 'dark',
    colors: {
      background: '#1F1F28',
      surface: '#2A2A37',
      surfaceAlt: '#363646',
      foreground: '#DCD7BA',
      muted: '#727169',
      accent: '#7E9CD8',
      border: '#2A2A37',
      success: '#76946A',
      warning: '#DCA561',
      error: '#C34043',
      prompt: '#76946A',
      command: '#7E9CD8',
      inactive: '#727169',
      ansiBlack: '#16161D',
      ansiRed: '#C34043',
      ansiGreen: '#76946A',
      ansiYellow: '#C0A36E',
      ansiBlue: '#7E9CD8',
      ansiMagenta: '#957FB8',
      ansiCyan: '#6A9589',
      ansiWhite: '#C8C093',
      ansiBrightBlack: '#727169',
      ansiBrightRed: '#E82424',
      ansiBrightGreen: '#98BB6C',
      ansiBrightYellow: '#E6C384',
      ansiBrightBlue: '#7FB4CA',
      ansiBrightMagenta: '#938AA9',
      ansiBrightCyan: '#7AA89F',
      ansiBrightWhite: '#DCD7BA',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rose Pine',
    author: 'Rose Pine',
    type: 'dark',
    colors: {
      background: '#191724',
      surface: '#1F1D2E',
      surfaceAlt: '#26233A',
      foreground: '#E0DEF4',
      muted: '#6E6A86',
      accent: '#C4A7E7',
      border: '#26233A',
      success: '#31748F',
      warning: '#F6C177',
      error: '#EB6F92',
      prompt: '#9CCFD8',
      command: '#C4A7E7',
      inactive: '#6E6A86',
      ansiBlack: '#191724',
      ansiRed: '#EB6F92',
      ansiGreen: '#31748F',
      ansiYellow: '#F6C177',
      ansiBlue: '#9CCFD8',
      ansiMagenta: '#C4A7E7',
      ansiCyan: '#EBBCBA',
      ansiWhite: '#E0DEF4',
      ansiBrightBlack: '#6E6A86',
      ansiBrightRed: '#EB6F92',
      ansiBrightGreen: '#31748F',
      ansiBrightYellow: '#F6C177',
      ansiBrightBlue: '#9CCFD8',
      ansiBrightMagenta: '#C4A7E7',
      ansiBrightCyan: '#EBBCBA',
      ansiBrightWhite: '#E0DEF4',
    },
  },
  {
    id: 'iceberg',
    name: 'Iceberg',
    author: 'cocopon',
    type: 'dark',
    colors: {
      background: '#161821',
      surface: '#1E2132',
      surfaceAlt: '#272B3F',
      foreground: '#C6C8D1',
      muted: '#6B7089',
      accent: '#84A0C6',
      border: '#272B3F',
      success: '#B4BE82',
      warning: '#E2A478',
      error: '#E27878',
      prompt: '#B4BE82',
      command: '#84A0C6',
      inactive: '#6B7089',
      ansiBlack: '#161821',
      ansiRed: '#E27878',
      ansiGreen: '#B4BE82',
      ansiYellow: '#E2A478',
      ansiBlue: '#84A0C6',
      ansiMagenta: '#A093C7',
      ansiCyan: '#89B8C2',
      ansiWhite: '#C6C8D1',
      ansiBrightBlack: '#6B7089',
      ansiBrightRed: '#E98989',
      ansiBrightGreen: '#C0CA8E',
      ansiBrightYellow: '#E9B189',
      ansiBrightBlue: '#91ACD1',
      ansiBrightMagenta: '#ADA0D3',
      ansiBrightCyan: '#95C4CE',
      ansiBrightWhite: '#D2D4DE',
    },
  },
  {
    id: 'nightfox',
    name: 'Nightfox',
    author: 'EdenEast',
    type: 'dark',
    colors: {
      background: '#192330',
      surface: '#212E3F',
      surfaceAlt: '#29394F',
      foreground: '#CDCECF',
      muted: '#71839B',
      accent: '#719CD6',
      border: '#29394F',
      success: '#81B29A',
      warning: '#DBC074',
      error: '#C94F6D',
      prompt: '#81B29A',
      command: '#719CD6',
      inactive: '#71839B',
      ansiBlack: '#393B44',
      ansiRed: '#C94F6D',
      ansiGreen: '#81B29A',
      ansiYellow: '#DBC074',
      ansiBlue: '#719CD6',
      ansiMagenta: '#9D79D6',
      ansiCyan: '#63CDCF',
      ansiWhite: '#DFDFE0',
      ansiBrightBlack: '#575860',
      ansiBrightRed: '#D16983',
      ansiBrightGreen: '#8EBAA4',
      ansiBrightYellow: '#E0C989',
      ansiBrightBlue: '#86ABDC',
      ansiBrightMagenta: '#BAA1E2',
      ansiBrightCyan: '#7AD5D6',
      ansiBrightWhite: '#E4E4E5',
    },
  },
  {
    id: 'carbonfox',
    name: 'Carbonfox',
    author: 'EdenEast',
    type: 'dark',
    colors: {
      background: '#161616',
      surface: '#1E1E1E',
      surfaceAlt: '#282828',
      foreground: '#F2F4F8',
      muted: '#7B7C7E',
      accent: '#78A9FF',
      border: '#282828',
      success: '#25BE6A',
      warning: '#08BDBA',
      error: '#EE5396',
      prompt: '#25BE6A',
      command: '#78A9FF',
      inactive: '#7B7C7E',
      ansiBlack: '#161616',
      ansiRed: '#EE5396',
      ansiGreen: '#25BE6A',
      ansiYellow: '#08BDBA',
      ansiBlue: '#78A9FF',
      ansiMagenta: '#BE95FF',
      ansiCyan: '#33B1FF',
      ansiWhite: '#DFDFE0',
      ansiBrightBlack: '#525252',
      ansiBrightRed: '#F16DA6',
      ansiBrightGreen: '#46C880',
      ansiBrightYellow: '#2DC7C4',
      ansiBrightBlue: '#8CB6FF',
      ansiBrightMagenta: '#C8A5FF',
      ansiBrightCyan: '#52BDFF',
      ansiBrightWhite: '#F2F4F8',
    },
  },
  {
    id: 'dawnfox',
    name: 'Dawnfox Dark',
    author: 'EdenEast',
    type: 'dark',
    colors: {
      background: '#1D2433',
      surface: '#252E3E',
      surfaceAlt: '#2D3748',
      foreground: '#CDCECF',
      muted: '#7E8A9E',
      accent: '#B4637A',
      border: '#2D3748',
      success: '#879A39',
      warning: '#EA9D34',
      error: '#B4637A',
      prompt: '#879A39',
      command: '#56949F',
      inactive: '#7E8A9E',
      ansiBlack: '#1D2433',
      ansiRed: '#B4637A',
      ansiGreen: '#879A39',
      ansiYellow: '#EA9D34',
      ansiBlue: '#286983',
      ansiMagenta: '#907AA9',
      ansiCyan: '#56949F',
      ansiWhite: '#CDCECF',
      ansiBrightBlack: '#7E8A9E',
      ansiBrightRed: '#C47A8D',
      ansiBrightGreen: '#9AAD4F',
      ansiBrightYellow: '#EDAB4D',
      ansiBrightBlue: '#3D7F96',
      ansiBrightMagenta: '#A18DB8',
      ansiBrightCyan: '#6AA7B0',
      ansiBrightWhite: '#E0E0E1',
    },
  },
  {
    id: 'terafox',
    name: 'Terafox',
    author: 'EdenEast',
    type: 'dark',
    colors: {
      background: '#152528',
      surface: '#1D3337',
      surfaceAlt: '#254147',
      foreground: '#E6EAEA',
      muted: '#6D7F8B',
      accent: '#5A93AA',
      border: '#254147',
      success: '#7AA4A1',
      warning: '#FFEBC6',
      error: '#E85C51',
      prompt: '#7AA4A1',
      command: '#5A93AA',
      inactive: '#6D7F8B',
      ansiBlack: '#152528',
      ansiRed: '#E85C51',
      ansiGreen: '#7AA4A1',
      ansiYellow: '#FFEBC6',
      ansiBlue: '#5A93AA',
      ansiMagenta: '#AD5C7C',
      ansiCyan: '#A1CDD8',
      ansiWhite: '#EBEBEB',
      ansiBrightBlack: '#4E5157',
      ansiBrightRed: '#EB746B',
      ansiBrightGreen: '#8EB2AF',
      ansiBrightYellow: '#FFF1D2',
      ansiBrightBlue: '#73A3B7',
      ansiBrightMagenta: '#B97490',
      ansiBrightCyan: '#AFD4DE',
      ansiBrightWhite: '#F0F0F0',
    },
  },
  {
    id: 'vitesse-dark',
    name: 'Vitesse Dark',
    author: 'Anthony Fu',
    type: 'dark',
    colors: {
      background: '#121212',
      surface: '#1A1A1A',
      surfaceAlt: '#222222',
      foreground: '#DBD7CA',
      muted: '#758575',
      accent: '#4D9375',
      border: '#222222',
      success: '#4D9375',
      warning: '#E6CC77',
      error: '#CB7676',
      prompt: '#4D9375',
      command: '#6394BF',
      inactive: '#758575',
      ansiBlack: '#121212',
      ansiRed: '#CB7676',
      ansiGreen: '#4D9375',
      ansiYellow: '#E6CC77',
      ansiBlue: '#6394BF',
      ansiMagenta: '#D9739F',
      ansiCyan: '#5EAAB5',
      ansiWhite: '#DBD7CA',
      ansiBrightBlack: '#758575',
      ansiBrightRed: '#D4888A',
      ansiBrightGreen: '#5DA985',
      ansiBrightYellow: '#EBD68D',
      ansiBrightBlue: '#7AA5CC',
      ansiBrightMagenta: '#E08BAF',
      ansiBrightCyan: '#6EBBC5',
      ansiBrightWhite: '#E5E1D8',
    },
  },
  {
    id: 'poimandres',
    name: 'Poimandres',
    author: 'drcmda',
    type: 'dark',
    colors: {
      background: '#1B1E28',
      surface: '#222534',
      surfaceAlt: '#2A2D3D',
      foreground: '#E4F0FB',
      muted: '#767C9D',
      accent: '#ADD7FF',
      border: '#2A2D3D',
      success: '#5DE4C7',
      warning: '#FFFAC2',
      error: '#D0679D',
      prompt: '#5DE4C7',
      command: '#ADD7FF',
      inactive: '#767C9D',
      ansiBlack: '#1B1E28',
      ansiRed: '#D0679D',
      ansiGreen: '#5DE4C7',
      ansiYellow: '#FFFAC2',
      ansiBlue: '#ADD7FF',
      ansiMagenta: '#FCC5E9',
      ansiCyan: '#89DDFF',
      ansiWhite: '#E4F0FB',
      ansiBrightBlack: '#767C9D',
      ansiBrightRed: '#D98DAF',
      ansiBrightGreen: '#7EECD3',
      ansiBrightYellow: '#FFFBD5',
      ansiBrightBlue: '#C1E1FF',
      ansiBrightMagenta: '#FDD5EF',
      ansiBrightCyan: '#A0E5FF',
      ansiBrightWhite: '#FFFFFF',
    },
  },
  {
    id: 'vesper',
    name: 'Vesper',
    author: 'raunofreiberg',
    type: 'dark',
    colors: {
      background: '#101010',
      surface: '#181818',
      surfaceAlt: '#1E1E1E',
      foreground: '#B7B7B7',
      muted: '#585858',
      accent: '#FFC799',
      border: '#1E1E1E',
      success: '#99FFE4',
      warning: '#FFC799',
      error: '#FF8080',
      prompt: '#99FFE4',
      command: '#A0D0FF',
      inactive: '#585858',
      ansiBlack: '#101010',
      ansiRed: '#FF8080',
      ansiGreen: '#99FFE4',
      ansiYellow: '#FFC799',
      ansiBlue: '#A0D0FF',
      ansiMagenta: '#FFAACE',
      ansiCyan: '#99FFE4',
      ansiWhite: '#B7B7B7',
      ansiBrightBlack: '#585858',
      ansiBrightRed: '#FF9999',
      ansiBrightGreen: '#B3FFE9',
      ansiBrightYellow: '#FFD4B3',
      ansiBrightBlue: '#B3DAFF',
      ansiBrightMagenta: '#FFBDD9',
      ansiBrightCyan: '#B3FFE9',
      ansiBrightWhite: '#D0D0D0',
    },
  },
  {
    id: 'moonlight',
    name: 'Moonlight',
    author: 'atomiks',
    type: 'dark',
    colors: {
      background: '#1E2030',
      surface: '#222436',
      surfaceAlt: '#2F334D',
      foreground: '#C8D3F5',
      muted: '#636DA6',
      accent: '#82AAFF',
      border: '#2F334D',
      success: '#C3E88D',
      warning: '#FFC777',
      error: '#FF757F',
      prompt: '#C3E88D',
      command: '#82AAFF',
      inactive: '#636DA6',
      ansiBlack: '#1E2030',
      ansiRed: '#FF757F',
      ansiGreen: '#C3E88D',
      ansiYellow: '#FFC777',
      ansiBlue: '#82AAFF',
      ansiMagenta: '#C099FF',
      ansiCyan: '#86E1FC',
      ansiWhite: '#C8D3F5',
      ansiBrightBlack: '#636DA6',
      ansiBrightRed: '#FF8D94',
      ansiBrightGreen: '#D1EEA1',
      ansiBrightYellow: '#FFD38B',
      ansiBrightBlue: '#96B8FF',
      ansiBrightMagenta: '#CEB0FF',
      ansiBrightCyan: '#9AE8FF',
      ansiBrightWhite: '#E2E8FA',
    },
  },
];

// ── Theme Store ──────────────────────────────────────────────────────────────

const STORAGE_KEY = '@shelly/theme';
const CUSTOM_THEMES_KEY = '@shelly/custom_themes';

type ThemeState = {
  currentThemeId: string;
  customThemes: Theme[];
  loadTheme: () => Promise<void>;
  setTheme: (id: string) => void;
  addCustomTheme: (theme: Theme) => void;
  removeCustomTheme: (id: string) => void;
  importThemeJson: (json: string) => Theme | null;
};

export const useThemeStore = create<ThemeState>((set, get) => ({
  currentThemeId: 'shelly-default',
  customThemes: [],

  loadTheme: async () => {
    const [savedId, customJson] = await Promise.all([
      AsyncStorage.getItem(STORAGE_KEY),
      AsyncStorage.getItem(CUSTOM_THEMES_KEY),
    ]);
    const updates: Partial<ThemeState> = {};
    if (savedId) updates.currentThemeId = savedId;
    if (customJson) {
      try { updates.customThemes = JSON.parse(customJson); } catch {}
    }
    set(updates);
  },

  setTheme: (id) => {
    set({ currentThemeId: id });
    AsyncStorage.setItem(STORAGE_KEY, id);
  },

  addCustomTheme: (theme) => {
    const updated = [...get().customThemes.filter((t) => t.id !== theme.id), theme];
    set({ customThemes: updated });
    AsyncStorage.setItem(CUSTOM_THEMES_KEY, JSON.stringify(updated));
  },

  removeCustomTheme: (id) => {
    const updated = get().customThemes.filter((t) => t.id !== id);
    set({ customThemes: updated });
    AsyncStorage.setItem(CUSTOM_THEMES_KEY, JSON.stringify(updated));
    if (get().currentThemeId === id) {
      set({ currentThemeId: 'shelly-default' });
      AsyncStorage.setItem(STORAGE_KEY, 'shelly-default');
    }
  },

  importThemeJson: (json) => {
    try {
      const parsed = JSON.parse(json);
      if (!parsed.id || !parsed.name || !parsed.colors) return null;
      const theme: Theme = {
        id: parsed.id,
        name: parsed.name,
        author: parsed.author,
        type: parsed.type || 'dark',
        colors: { ...BUILTIN_THEMES[0].colors, ...parsed.colors },
      };
      get().addCustomTheme(theme);
      return theme;
    } catch {
      return null;
    }
  },
}));

// ── Helper: Get current theme ────────────────────────────────────────────────

export function getCurrentTheme(): Theme {
  const { currentThemeId, customThemes } = useThemeStore.getState();
  return (
    BUILTIN_THEMES.find((t) => t.id === currentThemeId) ??
    customThemes.find((t) => t.id === currentThemeId) ??
    BUILTIN_THEMES[0]
  );
}

/**
 * React hook — re-renders when theme changes.
 */
export function useTheme(): Theme {
  const currentThemeId = useThemeStore((s) => s.currentThemeId);
  const customThemes = useThemeStore((s) => s.customThemes);
  return (
    BUILTIN_THEMES.find((t) => t.id === currentThemeId) ??
    customThemes.find((t) => t.id === currentThemeId) ??
    BUILTIN_THEMES[0]
  );
}

export function getAllThemes(): Theme[] {
  const { customThemes } = useThemeStore.getState();
  return [...BUILTIN_THEMES, ...customThemes];
}
