package expo.modules.terminalemulator

import android.content.Context
import java.io.File

object HomeInitializer {
    private val COREUTILS_APPLETS = listOf(
        "arch", "base32", "base64", "basename", "cat", "chgrp", "chmod", "chown",
        "cksum", "comm", "cp", "csplit", "cut", "date", "dd", "df", "dir", "dircolors",
        "dirname", "du", "echo", "env", "expand", "expr", "factor", "false", "fmt",
        "fold", "groups", "head", "hostid", "id", "install", "join", "kill", "link",
        "ln", "logname", "ls", "md5sum", "mkdir", "mkfifo", "mknod", "mktemp", "mv",
        "nice", "nl", "nohup", "nproc", "numfmt", "od", "paste", "pathchk", "pinky",
        "pr", "printenv", "printf", "pwd", "readlink", "realpath", "rm", "rmdir",
        "seq", "sha1sum", "sha224sum", "sha256sum", "sha384sum", "sha512sum",
        "shred", "shuf", "sleep", "sort", "split", "stat", "stty", "sum", "sync",
        "tac", "tail", "tee", "test", "timeout", "touch", "tr", "true", "truncate",
        "tsort", "tty", "uname", "unexpand", "uniq", "unlink", "users", "vdir",
        "wc", "who", "whoami", "yes"
    )

    // bug #96: the bundled coreutils single-binary has no `sed` applet, so
    // the post-install codex.js / gemini-cli rewrites in __shelly_bg_cli_update
    // were silently failing with "coreutils: unknown program 'sed'". Perform
    // the same textual rewrites through node instead, since node is already
    // a bundled linker64-shim'd binary. Idempotent (checks for "shelly-codex"
    // and the Termux error substring before writing).
    private val PATCHER_JS = """
// Generated by HomeInitializer.kt — do not edit by hand.
// Usage:
//   node shelly-patcher.js codex  <libDir> [<node_modules_root>]
//   node shelly-patcher.js gemini         [<node_modules_root>]
//   node shelly-patcher.js claude         [<node_modules_root>]
//
// node_modules_root defaults to ${'$'}HOME/.shelly-cli/node_modules so the
// patcher works against the live tree, but the update pipeline (v32+)
// passes a staging path so patches land in the staged tree before it's
// promoted.
const fs = require("fs");
const HOME = process.env.HOME;
const op = process.argv[2];
const libDir = (op === "codex") ? process.argv[3] : undefined;
const nmRoot = (op === "codex") ? process.argv[4] : process.argv[3];
const NM = nmRoot || (HOME + "/.shelly-cli/node_modules");

function patchCodex(libDir) {
  const p = NM + "/@openai/codex/bin/codex.js";
  if (!fs.existsSync(p)) { console.log("[patch] codex.js not found at " + p); return; }
  let s = fs.readFileSync(p, "utf8");
  if (s.includes("shelly-codex")) { console.log("[patch] codex.js already patched"); return; }
  const needle = "spawn(binaryPath, process.argv.slice(2)";
  if (!s.includes(needle)) { console.log("[patch] codex.js needle not found"); return; }
  // This patches the legacy 1-shot entry point used by npm `@openai/codex`.
  // Bash wrapper in .bashrc actually routes TUI vs exec itself (see the
  // `codex()` function generation below) — this patch just ensures that IF
  // somebody invokes codex.js directly (e.g. other tools that don't go
  // through bash), it still hits a working binary (codex_exec).
  const replacement = 'spawn("/system/bin/linker64", ["' + libDir + '/codex_exec", ...process.argv.slice(2)] /*shelly-codex*/';
  s = s.replace(needle, replacement);
  fs.writeFileSync(p, s);
  console.log("[patch] codex.js OK (at " + p + ")");
}

function patchGemini() {
  const d = NM + "/@google/gemini-cli/bundle";
  if (!fs.existsSync(d)) { console.log("[patch] gemini bundle not found at " + d); return; }
  // Widen the file glob from chunk-*.js to include the gemini-*.js
  // launchers — the shell:true patterns flagged by the 2026-04-24
  // subprocess audit live in BOTH chunk bundles and the top-level
  // gemini-*.js entry points.
  const files = fs.readdirSync(d).filter(f => (f.startsWith("chunk-") || f.startsWith("gemini-")) && f.endsWith(".js"));
  let termuxPatched = 0, shellPatched = 0, commandExistsPatched = 0;
  for (const f of files) {
    const p = d + "/" + f;
    let s = fs.readFileSync(p, "utf8");
    const before = s;
    // 1) Remove the Termux guard (original patch).
    const termuxRe = /throw new Error\("You need to install Termux[^"]*"\)/g;
    if (termuxRe.test(s)) {
      s = s.replace(termuxRe, "undefined");
      termuxPatched++;
    }
    // 2) Rewrite `shell: true` to the Android-bionic shell path. Covers
    //    three broken spawns: auto-update, GrepTool pre-flight, and the
    //    sandbox proxy. Match `shell:\s*true` only when followed by a
    //    comma or `}` (inside an options object) to avoid hitting string
    //    literals.
    s = s.replace(/shell:\s*true([,}])/g, 'shell:"/system/bin/sh"$1');
    // 3) Patch commandExists()'s bare execSync call so editor detection
    //    (vim/nano/cursor/vscode) actually works. Node's execSync(string)
    //    hardcodes /bin/sh on POSIX unless an options object with a
    //    shell field is supplied; the current `{ stdio: "ignore" }`
    //    misses that. Patch the exact literal emitted by the bundle.
    s = s.replace(
      /execSync\(getCommandExistsCmd\(cmd\),\s*\{\s*stdio:\s*"ignore"\s*\}\)/g,
      'execSync(getCommandExistsCmd(cmd),{stdio:"ignore",shell:"/system/bin/sh"})');
    if (s !== before) {
      // Reconcile counters after all three passes.
      if (s.length !== before.length || s.includes('/* shelly-gemini-shelltrue */') === false) {
        // We don't mark the file with a marker because the patterns
        // are self-idempotent (replacements no longer match after a run).
      }
      if (before.match(/shell:\s*true[,}]/)) shellPatched++;
      if (before.match(/execSync\(getCommandExistsCmd\(cmd\),\s*\{\s*stdio:\s*"ignore"\s*\}\)/)) commandExistsPatched++;
      fs.writeFileSync(p, s);
    }
  }
  console.log("[patch] gemini termux=" + termuxPatched + " shellTrue=" + shellPatched + " commandExists=" + commandExistsPatched + " /" + files.length + " files (at " + d + ")");
}

function patchClaude() {
  const p = NM + "/@anthropic-ai/claude-code/cli.js";
  if (!fs.existsSync(p)) { console.log("[patch] claude cli.js not found at " + p); return; }
  let s = fs.readFileSync(p, "utf8");
  if (s.includes("shelly-claude")) { console.log("[patch] claude cli.js already patched"); return; }
  // claude-code 2.1.112 spawns child processes with options.shell=true, which
  // Node.js maps to /bin/sh -c on POSIX. Android bionic has no /bin/sh, so
  // execve returns ENOENT and the Bash tool / MCP headersHelper / editor
  // spawns all exit 1 with empty stdout. Rewrite the minified literal
  // `shell:!0` to `shell:"/system/bin/sh"` so Node dispatches to the bionic
  // shell (mksh). Five call sites in 2.1.112; win32-guarded branches and
  // the sharp-installer helper are dead code on Android — still patched for
  // defence in depth.
  const needle = /shell:!0/g;
  const matches = s.match(needle);
  if (!matches) { console.log("[patch] claude cli.js needle not found"); return; }
  s = s.replace(needle, 'shell:"/system/bin/sh"');
  // Marker: idempotency check above matches this string. Must land in code,
  // not a leading comment block, so it survives any upstream header rewrites.
  s += "\n/* shelly-claude patched */\n";
  fs.writeFileSync(p, s);
  console.log("[patch] claude cli.js OK (" + matches.length + " call sites) at " + p);
}

if (op === "codex") patchCodex(libDir);
else if (op === "gemini") patchGemini();
else if (op === "claude") patchClaude();
else { console.error("usage: node shelly-patcher.js codex <libDir> [<nm>] | gemini [<nm>] | claude [<nm>]"); process.exit(1); }
""".trimIndent()

    /** Version counter — increment to force .bashrc regeneration.
     *  History:
     *    13: pre-OSC133 era
     *    14: drop OSC 133 from PS1 (0dff463b) — was forgotten to bump,
     *        which left users stuck on the broken phantom-prompt PS1 even
     *        after the code was fixed. Bumping now so the next launch
     *        regenerates .bashrc with the simple green-cwd-$ prompt.
     *    15: switch PS1 generation from $'...' ANSI-C quoting to
     *        `printf -v PS1 '\[\033[...\]...'`. The $'...' form turned
     *        \[ \] into literal backslash-bracket bytes, so bash never
     *        saw them as width hints and `echo "$PS1"` dumped ugly
     *        \[\]~\[\]\$. printf -v keeps \[ \] literal for bash while
     *        still expanding \033 into ESC.
     *    16: bug #76/#77 — pass --include=optional/--os=linux/--cpu=arm64
     *        to the npm install line so codex pulls its native binary, and
     *        sed-patch gemini-cli's hardcoded Termux check after install.
     *        Bumping resets the cached .bashrc and clears the daily update
     *        marker so the next bash launch re-runs the install with the
     *        new flags instead of waiting 24h.
     *    17: bug #80 — the CLI auto-update subshell used to run as a tracked
     *        background job and bash would dump a multi-line "[1]+ Done (...)"
     *        notification containing the whole install pipeline with
     *        unexpanded $__shelly_cli_dir literals the next time the user
     *        pressed Enter. Wrapped the body in a named function and
     *        launched via `( __shelly_bg_cli_update & )` so the job is
     *        orphaned and never enters the parent shell's job table.
     *    18: bug #76 final — ship Alpine minirootfs + rewrite the codex.js
     *        sed patch to remap the ET_EXEC binaryPath into proot's /root
     *        view so the binary actually loads. The previous marker was
     *        just "proot", so we switch to a "shelly-proot" tag to force
     *        the sed to re-run on installs that already went through the
     *        old marker.
     *    19: bug #93/#95 — add $HOME/bin/bash wrapper so `bash script.sh`
     *        works (previously only libbash.so via linker64 existed). Also
     *        add install.log for the CLI post-install pipeline so sed
     *        patch failures are visible, and verify the codex.js patch
     *        actually applied after sed runs.
     *    20: bug #91/#94 — enable readline bracketed-paste handling so
     *        that multi-line paste blocks from TerminalEmulator.paste()
     *        are consumed as a single input event instead of being
     *        executed line-by-line. The emulator always emits \e[200~ ..
     *        \e[201~ now (regardless of DECSET 2004), and readline parses
     *        it correctly as long as `set enable-bracketed-paste on` is
     *        bound. bash 4.4+ defaults to on but we bind explicitly so
     *        older builds and user overrides still get the behaviour.
     *    21: bug #74 — pre-create $HOME/.bash_history and export HISTFILE /
     *        HISTSIZE / HISTFILESIZE so the first ↑ press on a cold session
     *        doesn't silently do nothing (bash was defaulting to an empty
     *        in-memory history without persistence).
     *    22: bug #93 follow-up — the $HOME/bin/bash wrapper used
     *        #!/system/bin/sh as its shebang, but SELinux on Android 14+
     *        blocks execve of /system/bin/sh from app_data_file context.
     *        Replace the wrapper approach with a bash() shell function in
     *        .bashrc (same pattern as node/git/claude) so `bash -c '...'`
     *        and `bash script.sh` work. Also export -f bash so subshells
     *        inherit the function.
     *    23: bug #76 — libproot.so was missing from LibExtractor's LIBS
     *        map so it never got extracted to termux-libs/. Also the
     *        codex.js sed patch used spawn("proot",...) which hits SELinux
     *        — changed to spawn("/system/bin/linker64", [libproot.so, ...])
     *        with full proot args (rootfs, bind mounts, -0).
     *    24: bug #76 final — abandon proot approach entirely. Bundle the
     *        codex-termux Android-native binary (ET_DYN, bionic-linked)
     *        as libcodex_exec.so in jniLibs. The sed patch now replaces
     *        the upstream musl binaryPath with the bundled codex_exec
     *        via linker64 — same as node/git/bash. No proot, no rootfs.
     *    25: bug #96 — `coreutils --coreutils-prog=sed` silently fails
     *        because the bundled coreutils single-binary has no sed applet.
     *        That left every v0.1.0 install with an unpatched codex.js
     *        (upstream ET_EXEC path) and unpatched gemini bundle chunks
     *        (Termux check still throws). Replace both sed calls with a
     *        small node patcher (shelly-patcher.js) written to $HOME on
     *        every regen — node is guaranteed bundled and already works
     *        through the linker64 shim.
     *    26: bug — python3 bailed at bootstrap with "No module named
     *        'encodings'" because the bundled tar.gz layout puts the
     *        stdlib flat under $libDir/python3.13/ instead of the
     *        $PYTHONHOME/lib/python3.13/ path CPython's init code
     *        expects. Add PYTHONPATH=$libDir/python3.13 so the module
     *        lookup finds encodings/ during early import.
     *    27: bug #97 follow-up — bash 5.3 on bionic silently drops the
     *        ESC in the \e[200~ keyseq during readline dispatch, so the
     *        standard bracketed-paste BEGIN marker leaked `[200~` as
     *        literal text and broke every multi-line paste. Bind an
     *        ESC-free trigger (\C-x\C-b) to bracketed-paste-begin in the
     *        emacs, vi-insert, and vi-command keymaps so paste works in
     *        either editing mode; once inside the function, bytes are
     *        read directly (no dispatch) until the \e[201~ END marker,
     *        so that ESC is preserved. TerminalEmulator.paste() now
     *        gates the wrap on DECSET 2004; later builds keep this
     *        readline-only trigger for the normal prompt but send the
     *        standard bracketed-paste markers to TUI/CLI apps.
     *    28: @anthropic-ai/claude-code ≥ 2026-04 restructured its package
     *        layout: the top-level `cli.js` entry disappeared and the
     *        shipped binary moved to `bin/claude.exe` per package.json's
     *        new `bin` field. The pre-existing `claude()` shell function
     *        still pointed at the old `cli.js` path and every invocation
     *        failed with MODULE_NOT_FOUND. Rewrite the function to prefer
     *        `bin/claude.exe` when present and fall back to `cli.js`
     *        only as a compat layer for older pinned installs.
     *    29: @anthropic-ai/claude-code ≥ 2.0.0 (2025-09-29) ships Bun-compiled
     *        SEA binaries. The top-level `bin/claude.exe` is a 500-byte
     *        *placeholder stub* — the real executable lives in the
     *        platform-specific optional sub-package
     *        `@anthropic-ai/claude-code-linux-arm64-musl` (~100 MiB ET_EXEC
     *        linked against musl). On the first live-device trace
     *        (2026-04-18) we discovered:
     *          1. npm refuses to install the sub-package on Android because
     *             its package.json has `"os":"linux","libc":"glibc|musl"`
     *             and Android reports `os=android, libc=undefined`. The
     *             `--os=linux --cpu=arm64` flags weren't enough; we also
     *             need `--libc=musl --force` to bypass the filter.
     *          2. The install.cjs postinstall is Android-unaware (its
     *             PLATFORMS map has darwin/linux/win32 only) so even when
     *             the sub-package is manually installed, postinstall skips
     *             copying the binary over bin/claude.exe.
     *          3. The extracted sub-package binary is an ET_EXEC that
     *             declares `/lib/ld-musl-aarch64.so.1` as its interpreter.
     *             Android bionic doesn't have this path, but Shelly already
     *             bundles an Alpine minirootfs (for codex) which contains
     *             `ld-musl-aarch64.so.1` at
     *             `$HOME/.shelly-rootfs/lib/ld-musl-aarch64.so.1`.
     *        Solution: install the `-musl` sub-package by name with
     *        `--force --libc=musl`, then invoke it via explicit linker
     *        dispatch (same linker64-shim pattern we use for codex, but
     *        targeting the musl ld instead of /system/bin/linker64). On
     *        Termux this was validated end-to-end with `2.1.114 (Claude
     *        Code)` printing successfully. LD_PRELOAD must be unset at
     *        launch because Termux's own libtermux-exec-ld-preload.so is
     *        bionic-specific and the musl ld chokes on its relocations; on
     *        Shelly this isn't strictly needed (we don't set that preload)
     *        but we unset it defensively so that if the user runs Shelly's
     *        bash inside a Termux-inherited env the binary still launches.
     *        This path obviates the pre-2.0 JS pin entirely — we stay on
     *        `@latest` and get every upstream feature (/rewind, /bashes,
     *        skills hot reload, Sonnet 4.5 default).
     *    30: v29's musl-linker-via-linker64 approach failed on-device with
     *        `Could not find a PHDR: broken executable?` — bionic's
     *        /system/bin/linker64 refuses to load the Alpine musl
     *        `ld-musl-aarch64.so.1` because its ELF program header layout
     *        isn't what bionic's loader expects. On Termux the same
     *        binary worked because Termux's shell does a real execve
     *        (which on Termux's SELinux domain is permitted); on Shelly
     *        untrusted_app blocks direct execve of app_data_file so we
     *        have to go through a shim, and linker64 won't accept a
     *        non-bionic ELF. Switch to the existing proot wrapper
     *        (`$HOME/bin/proot`) which chroots into the bundled Alpine
     *        minirootfs; inside the chroot `/lib/ld-musl-aarch64.so.1`
     *        resolves naturally from PT_INTERP and proot's ptrace-based
     *        loader handles the ET_EXEC layout without hitting
     *        mmap_min_addr. The `$HOME:/root` bind mount in the proot
     *        wrapper exposes the musl sub-package install path as
     *        `/root/.shelly-cli/node_modules/.../claude` inside the
     *        chroot. Same pattern we considered for codex before switching
     *        to the codex-termux ET_DYN build; for claude we have no
     *        bionic-compatible build so proot is the only viable path.
     *    38: `gemini` interactive mode was throwing
     *        `error: expected absolute path: "--max-old-space-size=5557"`
     *        followed by `has bad ELF magic: 23212f75` on a fresh shell.
     *        Root cause: gemini-cli 0.38+ relaunches itself with a bigger
     *        heap via `spawn2(process.execPath, ['--max-old-space-size=5557',
     *        gemini.js])`. On Shelly, `process.execPath` is \$libDir/node
     *        (a shared library invoked through /system/bin/linker64), so
     *        the child execve ends up passing gemini.js to linker64 as its
     *        binary — not valid ELF.
     *
     *        Fix: set `GEMINI_CLI_NO_RELAUNCH=true` (gemini-cli honours it
     *        at bundle/gemini.js:14445 as a relaunch kill-switch) and pass
     *        `--max-old-space-size=5557` in the initial `_run` so the
     *        heap-size check (target > current) short-circuits before the
     *        respawn anyway. Two fences because the relaunch code path is
     *        upstream-maintained and may introduce new code paths between
     *        versions.
     *
     *        `--version` kept working because it short-circuits before the
     *        relaunch check, which is why the issue only surfaced in
     *        interactive invocations.
     *    37: Phase 1.5 UX polish — two small adds on the shelly-cs auth
     *        flow:
     *        (a) Clipboard auto-copy: cmdAuth now fires a
     *            shelly://clipboard?text=<code> deep link alongside
     *            displaying the device code, so users can paste directly
     *            into the browser instead of retyping the 8-char pair.
     *            app/_layout.tsx handles the clipboard scheme via
     *            expo-clipboard (already a project dep). Silent fail
     *            is accepted — the code is always on screen too.
     *        (b) Auth UX copy: explicit "any device works — github.com/
     *            login/device on your PC is fine too" hint (from
     *            observed user confusion when the Android VIEW intent
     *            didn't hit an installed browser) and a "Ctrl+C to
     *            cancel" line so the polling loop feels escapable.
     *        Non-goals for v37: detached/async polling, SSH tunneling,
     *        SecureStore bridge. Those are the heavier v38+ items.
     *    36: shelly-cs convenience layer — zero-arg `cs` opens the
     *        user's default codespace in the Browser Pane. Adds
     *        `shelly-cs use <name>` to persist the default, changes
     *        `shelly-cs open` to fall back to the default (or the only
     *        running codespace when no default is set), marks the
     *        default with ★ in `shelly-cs list`, surfaces it in
     *        `shelly-cs doctor`, and aliases `cs` → `shelly-cs` in
     *        .bashrc so typing two letters is enough once the default
     *        is remembered. Rounds out the Phase 1 UX target: from a
     *        fresh shell in any cwd, `cs` → Codespace + claude-code
     *        ready in Shelly's in-app Browser Pane.
     *    35: shelly-cs openUrl() prefers the `shelly://browser?url=...`
     *        deep link so codespace web URLs land in Shelly's in-app
     *        Browser Pane (WebView) instead of kicking to Chrome /
     *        Samsung Internet. app/_layout.tsx registers a Linking
     *        listener that parses the URL, calls
     *        useMultiPaneStore.addPane('browser') to ensure the pane
     *        exists, and useBrowserStore.openUrl(target) to navigate.
     *        Falls back to the raw VIEW intent (OS browser) if the deep
     *        link fails — so older APK installs that haven't regenerated
     *        their shelly-cs.js yet still reach the destination.
     *    34: ship shelly-cs — GitHub Codespaces CLI (pure Node, REST API
     *        direct, no gh-CLI dependency). Script lives in APK assets at
     *        modules/.../assets/shelly-cs.js (so it edits as normal JS
     *        without Kotlin escaping), extracted on every launch into
     *        $HOME/.shelly-cs/shelly-cs.js. Invoked via the `shelly-cs`
     *        shell function which routes through the bundled bionic node.
     *
     *        Implements OAuth device flow against the Shelly OAuth App
     *        (Client ID: Ov23liLDXUTGYlzzhlLG, override via
     *        SHELLY_OAUTH_CLIENT_ID env for dev/staging), plus Codespaces
     *        list/create/open/stop/delete/doctor. SSH tunneling is a
     *        Phase 1.5 placeholder — for now `shelly-cs open <name>`
     *        opens the codespace web URL via android VIEW intent, which
     *        gives users the codespace's web terminal + claude-code
     *        pre-installed (per the devcontainer template).
     *
     *        Strategic context: claude-code 2.1.113+ dropped cli.js in
     *        favour of a Bun SEA binary that can't run on Android bionic.
     *        Shelly's local CLI pin (2.1.112 via v33) keeps users on the
     *        last mobile-native release; Codespaces integration is the
     *        sustainable path to always-latest claude-code on mobile.
     *    33: claude-code pinned to 2.1.112 (last cli.js-shipping release).
     *        2.1.113 renamed the bin entry from `cli.js` to `bin/claude.exe`
     *        (Bun-compiled SEA) and dropped the cli.js file from the tarball
     *        entirely. cli-wrapper.cjs is just a platform-detect + spawn
     *        launcher with no JS fallback, so there's nothing to patch.
     *        Without cli.js the `_run node cli.js` dispatch in claude() has
     *        no entry point on any version >= 2.1.113, so we pin to the
     *        highest version it can still execute. Also fixes the cp -al
     *        nesting bug in __shelly_bg_cli_update staging clone: the
     *        `cp -al $src $dest` form created a nested .shelly-cli.staging/
     *        .shelly-cli/ tree when dest pre-existed (stale from a prior
     *        aborted run). Switched to `cp -al $src/. $dest/` so the copy
     *        lands flat regardless of whether dest was already a directory.
     *    32: MAJOR COURSE CORRECTION. 5-agent survey of GitHub issues
     *        (#45541 et al.), Ishabdullah/claude-code-termux, Reddit,
     *        Qiita/Zenn, LINUX DO, skeptrune blog confirmed that the
     *        Bun-binary-via-proot path (v28–v30) was over-engineered.
     *        The npm tarball for @anthropic-ai/claude-code@<=2.1.112
     *        still ships a plain-JS `cli.js` that works end-to-end with
     *        the bundled bionic node — no musl, no proot, no chroot, no
     *        CA bundle, no machine-id. The user's own device was running
     *        claude 2.1.112 fine via the v26 `_run node cli.js` pattern.
     *        Revert to that approach with three hardening additions:
     *        (a) 3-tier fallback in claude(): auto-updated / snapshot
     *            (.shelly-cli.prev) / APK-bundled golden.
     *        (b) Health-check-gated update: install into .shelly-cli.staging,
     *            timeout-guarded `node cli.js --version` probe, rotate to
     *            .prev only if the probe succeeds, else discard staging
     *            without touching the live tree.
     *        (c) `--os=linux --cpu=arm64` (not --libc=musl) on the install
     *            so Anthropic's Android-blocking postinstall in install.cjs
     *            is tricked into the happy path. We DROP --libc=musl and
     *            the separate sub-package install — those were required
     *            only for the Bun binary, which we no longer use.
     *        Future risk: v2.1.114 has been observed to drop cli.js on
     *        fresh `npm install -g` in plain Termux. If the same regression
     *        hits our `--os=linux` override, the health check fails and
     *        we stay on the prior working tree — no fleet breakage.
     *    39: ship Mozilla CA bundle (~/.shelly-ssl/ca-certificates.crt,
     *        extracted from APK asset on every launch) and wire
     *        SSL_CERT_FILE / SSL_CERT_DIR / CURL_CA_BUNDLE /
     *        NODE_EXTRA_CA_CERTS / REQUESTS_CA_BUNDLE so bundled
     *        curl/node/codex_exec/python stop failing HTTPS because
     *        Android's system trust store is in a location openssl/rustls
     *        don't probe. Prerequisite for Track 1 codex native login
     *        (rustls was bailing with "no native root CA certificates
     *        found" during 2026-04-19 smoke test). Also fixes a class of
     *        silent HTTPS failures across any bundled TLS client —
     *        tested curl, node fetch, python requests.
     *    40: __shelly_bg_cli_update auto-subshells when invoked from an
     *        interactive shell. Previously, running the function directly
     *        to force-upgrade claude-code exec'd `</dev/null` over the
     *        main shell's stdin → bash hit EOF → exited with
     *        "[Process completed - press Enter]". Now the function re-
     *        invokes itself as a detached `( __SHELLY_CLI_UPDATE_SUBSHELL=1
     *        ... & )` when called interactively, leaving the user's main
     *        shell untouched. Observed 2026-04-19 v39 smoke test —
     *        user typed __shelly_bg_cli_update, shell died. */
    // v41 bump covers several pipeline / bashrc changes that already landed
    // in the code but never triggered a regeneration because v40 stayed put:
    //   - commit ec19fa07: npm_config_os/cpu/libc + --force + --omit=optional
    //     in __shelly_bg_cli_update so npm's platform check truly yields.
    //   - commit d613f78c: CLAUDE_CODE_TMPDIR export + mkdir so Claude's
    //     OAuth PKCE state persists (bug #102 mitigation).
    //   - 2026-04-20 pass: TMPDIR/TMP/TEMP aliases on top of
    //     CLAUDE_CODE_TMPDIR so every Node.js os.tmpdir() consumer (MCP
    //     subprocesses, future claude internal paths) lands in the same
    //     writable dir (bug #102 belt-and-suspenders).
    //   - 2026-04-20 pass: codex-vendor shim (mkdir + ln -sfn in
    //     __shelly_bg_cli_update) so codex.js stops throwing "Missing
    //     optional dependency @openai/codex-linux-arm64" before the
    //     shelly-patcher spawn rewrite can run (bug #105).
    //   - 2026-04-20 pass: default `git config --global user.email/name`
    //     on shell start if the user hasn't set their own, so
    //     auto-savepoint commits stop failing with "Author identity
    //     unknown" (bug #100).
    //  42: codex TUI wiring — codex() bash function routes bare/free-form
    //     invocation to `codex_tui` (new LibExtractor entry, upstream
    //     ratatui-based REPL) and known subcommands (exec/resume/review/
    //     help/mcp/completion/login/logout) to `codex_exec` for 1-shot
    //     execution. Fixes bug #114 "codex-termux has no interactive mode"
    //     — the TUI binary was always shipped in the npm tarball but CI
    //     was only copying codex-exec.bin into jniLibs.
    //  43: drop dead TMPDIR/TMP/TEMP exports (cli.js never calls os.tmpdir;
    //     verified via grep — see #102 investigation in
    //     specs/2026-04-20-overnight-fix-handoff.md). Add explicit
    //     PS2='> ' to neutralise the "<` line-prefix" hypothesis raised in
    //     the #106 paste-display review (one of the surviving symptoms is a
    //     literal `<` showing up at column 0; if PS2 was ever overridden by
    //     something to that, this hardcodes the bash default). Add
    //     DISABLE_AUTOUPDATER=1 to claude's environment as recommended by
    //     issue #50270 — the 2.1.112 pin is fragile because the bundled
    //     auto-updater can silently fetch a 2.1.113+ Bun SEA tarball that
    //     bricks Android. The chmod a-w on the cli dir is the second half
    //     of that defense and lives in __shelly_bg_cli_update below.
    // v44 (2026-04-21): bug #117 Path C-bis — claude() prefers the
    //     APK-bundled musl claude-code 2.1.113+ Bun SEA binary loaded via
    //     the Shelly-patched ld-musl-aarch64.so.1. resolv.conf is seeded
    //     at ~/.shelly-ssl/ on demand so musl's hardcoded DNS lookup
    //     works on bionic (which has no /etc/resolv.conf).
    // v45 (2026-04-21): bug #117 trampoline — claude() now routes Path C-bis
    //     via shelly_musl_exec (kernel-like stack/auxv bootstrap for ld-musl)
    //     and only falls through to legacy cli.js tiers when the musl path
    //     crashes with a signal-style exit status.
    // v46 (2026-04-21): bug #117 on-device smoke — Path C-bis inherited
    //     the PTY-wide bionic LD_PRELOAD=libexec_wrapper.so. musl tried to
    //     relocate that bionic preload and failed on __register_atfork,
    //     __open_2, and __errno before falling back to 2.1.112. Clear
    //     LD_PRELOAD for the musl claude launch only.
    // v47 (2026-04-21): Shelly-managed runtime updater — claude/codex prefer
    //     ~/.shelly-runtime/<tool>/current after staged download, integrity
    //     verification, and --version smoke test. APK binaries remain the
    //     known-good fallback.
    // v48 (2026-04-21): shelly-doctor — read-only CLI diagnostics for
    //     runtime updater state, CLI versions, and auth file presence.
    // v49 (2026-04-23): point $SHELL at the native shell launcher so
    //     Claude Code's Bash tool can spawn a working shell outside
    //     Shelly's interactive bash functions.
    // v50 (2026-04-23): expose the same native shell launcher as
    //     $HOME/bin/bash for Node-based CLIs such as Gemini that call
    //     spawn("bash", ...) and cannot see exported bash functions.
    // v51 (2026-04-23): add PATH-visible env/sh compatibility links and
    //     always append Android system bins so Codex/Gemini child process
    //     lookup does not fall into dead /usr/bin or /bin entries.
    // v52 (2026-04-24): re-point $SHELL at $HOME/bin/bash after the symlink
    //     is created so Claude Code CLI's basename($SHELL) shell validation
    //     accepts it. The .so target rejected basename check "bash" passes.
    // v53 (2026-04-24): move $SHELL from $nativeLibDir/libshelly_shell.so to
    //     $libDir/shelly_shell. The nativeLibDir path is empty on zero-copy
    //     installs and changes on every APK reinstall, leaving $HOME/bin/bash
    //     as a dangling symlink that Node/Bun child_process.spawn("bash")
    //     can't resolve (Claude Code, Gemini, Codex all affected). LibExtractor
    //     now unpacks libshelly_shell.so to $libDir alongside node/git/bash.
    // v54 (2026-04-24): three-part polish pass on CLI tool integration.
    //     a) export TMPDIR=$HOME/tmp (+ mkdir) so Gemini CLI's
    //        os.tmpdir()-based pgrep tracker lands in a writable dir
    //        instead of the baked-in `/data/data/com.termux/...` fallback.
    //     b) gate the "[shelly] background CLI update started" notice on
    //        `[ -t 2 ]` so it doesn't surface as tool output when Codex /
    //        Gemini / Claude capture stderr.
    //     c) bug #117 Option B: shelly-patcher.js now has a claude op that
    //        rewrites cli.js `shell:!0` → `shell:"/system/bin/sh"` on the
    //        staged tree. The CI workflow applies the same sed to the
    //        APK-bundled cli.js so the fix is live on first launch.
    private const val BASHRC_VERSION = 54

    fun getHomeDir(context: Context): File =
        File(context.filesDir, "home").also { it.mkdirs() }

    fun initialize(context: Context): File {
        val home = getHomeDir(context)
        val libDir = LibExtractor.getLibDir(context).absolutePath
        val nativeLibDir = context.applicationInfo.nativeLibraryDir

        File(home, "projects").mkdirs()

        // bug #76 final fix: extract Alpine minirootfs so proot has a real
        // rootfs to mount. Without one, `proot /path/to/static-binary` fails
        // with "unexpected e_type: 2" because ET_EXEC needs a libc that
        // proot can mmap through its own loader, and the only way to give
        // proot a libc is to hand it a rootfs via -r. The rootfs is ~8 MiB
        // unpacked, shipped as a 3.7 MiB .tar.gz asset.
        val rootfsDir = File(home, ".shelly-rootfs")
        val rootfsMarker = File(rootfsDir, "etc/alpine-release")
        if (!rootfsMarker.exists()) {
            try {
                rootfsDir.mkdirs()
                val assetName = try {
                    context.assets.open("alpine-rootfs.tar").close(); "alpine-rootfs.tar"
                } catch (_: Exception) {
                    "alpine-rootfs.tar.gz"
                }
                val isGz = assetName.endsWith(".gz")
                val tempTar = File(context.cacheDir, assetName)
                context.assets.open(assetName).use { input ->
                    tempTar.outputStream().use { output -> input.copyTo(output) }
                }
                val pb = ProcessBuilder(
                    "/system/bin/tar",
                    if (isGz) "xzf" else "xf",
                    tempTar.absolutePath,
                    "-C", rootfsDir.absolutePath,
                )
                pb.redirectErrorStream(true)
                val proc = pb.start()
                val out = proc.inputStream.bufferedReader().readText()
                val code = proc.waitFor()
                tempTar.delete()
                if (code != 0) {
                    android.util.Log.e("HomeInitializer", "rootfs tar failed (exit $code): $out")
                }
                // Make sure the proot-writable subdirs the wrapper binds into
                // actually exist; Alpine minirootfs leaves /root and /tmp in
                // place but we explicitly mkdir them so the bind mount can
                // land even on stripped rootfs builds.
                File(rootfsDir, "root").mkdirs()
                File(rootfsDir, "tmp").mkdirs()
                File(rootfsDir, "usr/local/bin").mkdirs()
            } catch (e: Exception) {
                android.util.Log.e("HomeInitializer", "rootfs extraction failed: ${e.message}")
            }
        }

        // bug #76: proot wrapper. The earlier version passed the binary
        // through as the only argument, which made proot try to load the
        // ET_EXEC static binary straight into the host address space. That
        // fails on Android because the binary's LOAD segment at 0x400000
        // collides with mmap_min_addr, and proot reports it as
        // "unexpected e_type: 2". The fix is to give proot a rootfs with -r
        // plus the usual bind mounts so it re-maps the load segments
        // through its own ptrace-based loader.
        //
        // BASHRC_VERSION v30: additional binds for claude interactive mode.
        // Claude Code v2.x's Bun-compiled musl binary internally spawns
        // `node /path/to/cli.js` for its interactive REPL, and that node is
        // our bundled bionic node at $libDir/node. Without the following
        // bind mounts, the chroot would lack:
        //   - /system/bin/linker64 (bionic node's PT_INTERP)
        //   - /apex/com.android.runtime/lib64/bionic/* (Android 10+ bionic
        //     libs moved out of /system into /apex)
        //   - /linkerconfig/ld.config.txt (Android 10+ linker config)
        //   - $libDir itself (where node and its node_modules live)
        // so the spawned node fails to launch and interactive mode crashes
        // with MODULE_NOT_FOUND for cli.js (or even before). We also bind
        // $libDir onto a fixed path /shelly-bin so cli.js shims can refer
        // to it by an absolute in-chroot path without guessing $libDir.
        //
        //   -0               fake uid 0 (required because musl's geteuid
        //                    check refuses to run otherwise)
        //   --kill-on-exit   send SIGKILL to the tracee on proot exit
        //   -r rootfs        use the bundled Alpine minirootfs
        //   -b /dev          pass through real /dev (ttys, null, urandom)
        //   -b /proc         pass through real /proc
        //   -b /sys          pass through real /sys
        //   -b /system       expose bionic linker64 + libs for spawned node
        //   -b /apex         expose Android 10+ bionic libc / libm / libdl
        //   -b /linkerconfig expose Android 10+ dynamic linker config
        //   -b $libDir:/shelly-bin bind Shelly's jniLibs so node/git/etc
        //                    are reachable via /shelly-bin inside chroot
        //   -b $HOME:/root   bind Shelly HOME into /root so the user's
        //                    files and .shelly-cli tree are visible
        //   -w /root         start in /root
        val binDir = File(home, "bin")
        binDir.mkdirs()
        val prootWrapper = File(binDir, "proot")
        prootWrapper.writeText(
            "#!/system/bin/sh\n" +
            "exec /system/bin/linker64 $libDir/libproot.so " +
            "-0 --kill-on-exit " +
            "-r ${rootfsDir.absolutePath} " +
            "-b /dev -b /proc -b /sys " +
            "-b /system " +
            "-b /apex " +
            "-b /linkerconfig " +
            "-b $libDir:/shelly-bin " +
            "-b ${home.absolutePath}:/root " +
            "-w /root " +
            "\"\$@\"\n"
        )
        prootWrapper.setExecutable(true, false)

        // bug #93 v2: removed the shebang-based $HOME/bin/bash wrapper — SELinux
        // blocks #!/system/bin/sh from app_data_file context. bash is now a shell
        // function in .bashrc instead (same pattern as node/git/claude). Clean up
        // the old wrapper if it exists so PATH doesn't find it first.
        val oldBashWrapper = File(binDir, "bash")
        if (oldBashWrapper.exists()) oldBashWrapper.delete()

        // bug #96: write the node-based patcher that replaces the broken
        // `coreutils --coreutils-prog=sed` calls used for codex.js and
        // gemini-cli bundle rewrites. Always overwrite so bumps to the
        // patcher logic ship with the bashrc regen.
        File(home, ".shelly-patcher.js").writeText(PATCHER_JS)

        // v34: ship shelly-cs — the GitHub Codespaces CLI for Shelly
        // (standalone, pure Node, no gh-CLI dependency). The script lives
        // as an APK asset (modules/.../assets/shelly-cs.js) so it can be
        // edited as normal JS without Kotlin string escaping, and is
        // re-extracted on every launch so bashrc-version bumps include the
        // latest script.
        //
        // Invoked via the `shelly-cs` shell function defined later in
        // .bashrc, which routes through the bundled bionic node (same
        // pattern as claude/gemini/codex).
        val shellyCsDir = File(home, ".shelly-cs")
        shellyCsDir.mkdirs()
        val shellyCsScript = File(shellyCsDir, "shelly-cs.js")
        try {
            context.assets.open("shelly-cs.js").use { input ->
                shellyCsScript.outputStream().use { output -> input.copyTo(output) }
            }
            shellyCsScript.setExecutable(true, false)
        } catch (e: Exception) {
            android.util.Log.e("HomeInitializer", "shelly-cs.js extract failed: ${e.message}")
        }

        // Phase 1.5 Day 2: ship shelly-cs-tunnel.js alongside the main
        // script. shelly-cs.js lazy-require's this library only when the
        // user runs `shelly-cs ssh <name> --probe-tunnel`, so it doesn't
        // run at all on a plain `shelly-cs open` path (no @microsoft/
        // dev-tunnels-connections cost for users who don't use SSH).
        // Refresh on every launch so APK upgrades that change the tunnel
        // protocol (new API version, new tunnel relay hosts, etc.)
        // propagate without the user deleting ~/.shelly-cs/.
        val shellyCsTunnelScript = File(shellyCsDir, "shelly-cs-tunnel.js")
        try {
            context.assets.open("shelly-cs-tunnel.js").use { input ->
                shellyCsTunnelScript.outputStream().use { output -> input.copyTo(output) }
            }
        } catch (e: Exception) {
            android.util.Log.e("HomeInitializer", "shelly-cs-tunnel.js extract failed: ${e.message}")
        }

        // v39: shelly-codex-auth — pure-JS ChatGPT subscription device-auth
        // for the Codex CLI. Upstream codex-rs ships `codex login
        // --device-auth` but codex-termux (the community rebuild we bundle
        // for the Android native binary path) has the login subcommand
        // compiled out. Rather than re-compile codex-termux with login
        // re-enabled, we drive the exact same HTTPS flow in JavaScript:
        //
        //   1. POST /api/accounts/deviceauth/usercode
        //   2. poll /api/accounts/deviceauth/token
        //   3. POST /oauth/token                  (form-encoded)
        //   4. write ~/.codex/auth.json (mode 0600, auth_mode="chatgpt")
        //
        // The script needs the v39 CA bundle wiring (NODE_EXTRA_CA_CERTS)
        // to negotiate TLS with auth.openai.com; see the ca-certificates
        // extraction below.
        val codexAuthScript = File(home, ".shelly-codex-auth.js")
        try {
            context.assets.open("shelly-codex-auth.js").use { input ->
                codexAuthScript.outputStream().use { output -> input.copyTo(output) }
            }
        } catch (e: Exception) {
            android.util.Log.e("HomeInitializer", "shelly-codex-auth.js extract failed: ${e.message}")
        }

        // v47: Shelly-managed runtime updater for Claude Code and Codex.
        // Extract every launch so updater fixes ship without relying on an
        // existing .bashrc regeneration.
        val runtimeUpdateScript = File(home, ".shelly-runtime-update.js")
        try {
            context.assets.open("shelly-runtime-update.js").use { input ->
                runtimeUpdateScript.outputStream().use { output -> input.copyTo(output) }
            }
        } catch (e: Exception) {
            android.util.Log.e("HomeInitializer", "shelly-runtime-update.js extract failed: ${e.message}")
        }

        val doctorScript = File(home, ".shelly-doctor.js")
        try {
            context.assets.open("shelly-doctor.js").use { input ->
                doctorScript.outputStream().use { output -> input.copyTo(output) }
            }
        } catch (e: Exception) {
            android.util.Log.e("HomeInitializer", "shelly-doctor.js extract failed: ${e.message}")
        }

        // v39: Mozilla CA bundle for TLS clients that don't consult the
        // Android system trust store. Three classes of clients need this:
        //   1. Bundled bionic `curl` — built without an embedded bundle,
        //      fails with "SSL certificate problem: unable to get local
        //      issuer certificate" against any HTTPS endpoint unless
        //      CURL_CA_BUNDLE points at a PEM list.
        //   2. Bundled bionic `node` — its built-in TLS pulls from
        //      openssl's compiled-in default path, which on Android
        //      resolves to /system/etc/security/cacerts.d that doesn't
        //      exist. Affects fetch(), https module, undici, anything
        //      TLS-using. `NODE_EXTRA_CA_CERTS` augments the empty
        //      default set.
        //   3. Bundled bionic `codex_exec` (ChatGPT subscription auth via
        //      rustls) — Rust's native-tls sees zero roots on Android,
        //      fails login with "no native root CA certificates found"
        //      observed during smoke test 2026-04-19. SSL_CERT_FILE is
        //      the standard rustls/openssl override.
        //
        // The bundle is the Mozilla cacert.pem snapshot bundled in the
        // APK (assets/ca-certificates.crt, 226 KiB). Refresh on every
        // launch — rewrite is cheap and APK upgrades need to propagate
        // updated roots (expired certs retired, new ones issued).
        val sslDir = File(home, ".shelly-ssl")
        sslDir.mkdirs()
        val caBundle = File(sslDir, "ca-certificates.crt")
        try {
            context.assets.open("ca-certificates.crt").use { input ->
                caBundle.outputStream().use { output -> input.copyTo(output) }
            }
        } catch (e: Exception) {
            android.util.Log.e("HomeInitializer", "ca-certificates.crt extract failed: ${e.message}")
        }

        // Regenerate .bashrc if version changed
        val bashrc = File(home, ".bashrc")
        val versionFile = File(home, ".bashrc_version")
        val currentVersion = try { versionFile.readText().trim().toInt() } catch (_: Exception) { 0 }

        // bug #91 follow-up: trace version bump decisions so it's obvious
        // from logcat whether a launched session is on a stale .bashrc
        // (e.g. the update logic ran but the file write was blocked, or
        // BASHRC_VERSION didn't bump). Without this, diagnosing "feature
        // X was merged but still not in the shell" requires manually
        // cat'ing ~/.bashrc_version.
        android.util.Log.i(
            "HomeInitializer",
            "bashrc version check: current=$currentVersion target=$BASHRC_VERSION " +
                "regenerate=${!bashrc.exists() || currentVersion < BASHRC_VERSION}"
        )

        if (!bashrc.exists() || currentVersion < BASHRC_VERSION) {
            // bug #76/#77: when the bashrc version bumps because the install
            // script changed, force the next bash launch to re-run the npm
            // install instead of waiting for the daily update window. The
            // simplest knob is to delete the timestamp marker — the install
            // block treats a missing marker as "older than the interval" and
            // re-runs.
            try { File(home, ".shelly_last_update").delete() } catch (_: Exception) {}

            val sb = StringBuilder()

            // Environment — preserve PATH/LD_LIBRARY_PATH if already set by
            // shelly-pty.c (which includes lib dir, npm bins, etc.)
            sb.appendLine("export HOME=\"${home.absolutePath}\"")
            sb.appendLine("export TERM=xterm-256color")
            sb.appendLine("export COLORTERM=truecolor")
            sb.appendLine("export LANG=en_US.UTF-8")
            sb.appendLine("export SHELLY_LIB_DIR=\"$libDir\"")
            // v53: point $SHELL at the LibExtractor-extracted shelly_shell
            // binary in $libDir. Using nativeLibraryDir (v49) doesn't work on
            // zero-copy-packaged installs where that directory is empty, and
            // its obfuscated path changes on every APK reinstall, leaving
            // $HOME/bin/bash as a dangling symlink. $libDir is stable across
            // upgrades (filesDir), and libexec_wrapper.so's LD_PRELOAD still
            // routes the execve through /system/bin/linker64 for SELinux.
            sb.appendLine("export SHELL=\"$libDir/shelly_shell\"")
            sb.appendLine("export BASH=\"\$SHELL\"")
            sb.appendLine("export PATH=\"${home.absolutePath}/bin:\${PATH:-$libDir}:/system/bin:/vendor/bin\"")
            sb.appendLine("export LD_LIBRARY_PATH=\"\${LD_LIBRARY_PATH:-$libDir}\"")
            // v39: point every bundled TLS client at the Mozilla CA bundle
            // we extract to ~/.shelly-ssl/. Without these exports curl/node/
            // codex_exec all fail HTTPS because Android's system trust
            // store is not in any of the locations openssl/rustls probe by
            // default. See HomeInitializer.initialize() above for the
            // extraction step and BASHRC_VERSION 39 comment for rationale.
            sb.appendLine("export SSL_CERT_FILE=\"\$HOME/.shelly-ssl/ca-certificates.crt\"")
            sb.appendLine("export SSL_CERT_DIR=\"\$HOME/.shelly-ssl\"")
            sb.appendLine("export CURL_CA_BUNDLE=\"\$HOME/.shelly-ssl/ca-certificates.crt\"")
            sb.appendLine("export NODE_EXTRA_CA_CERTS=\"\$HOME/.shelly-ssl/ca-certificates.crt\"")
            sb.appendLine("export REQUESTS_CA_BUNDLE=\"\$HOME/.shelly-ssl/ca-certificates.crt\"")
            // v41 Claude Code OAuth 400 fix. Claude Code writes OAuth PKCE
            // state (code_verifier, state nonce) into a tmp dir it
            // hardcodes to /tmp/claude. On Android /tmp is not writable
            // from an app sandbox ("Permission denied" confirmed on-device
            // 2026-04-19 for ls/mkdir/touch under /tmp), so the write
            // silently no-ops. On the second leg of the OAuth flow (token
            // exchange) the PKCE verifier is missing and Anthropic's OAuth
            // server responds with "Request failed with status code 400".
            // Claude Code 2.1.5+ honours CLAUDE_CODE_TMPDIR as an override;
            // point it at a writable dir inside HOME. Pre-create the dir
            // at bash startup so the very first `claude /login` works
            // without the user needing to mkdir manually.
            sb.appendLine("export CLAUDE_CODE_TMPDIR=\"\$HOME/.claude-tmp\"")
            sb.appendLine("mkdir -p \"\$CLAUDE_CODE_TMPDIR\" 2>/dev/null")
            // v43: TMPDIR/TMP/TEMP exports REMOVED. The 2026-04-20 #102
            // investigation grep'd cli.js for `os.tmpdir` / `process.env.TMPDIR`
            // and found 0 hits — claude-code 2.1.112 does not consult Node's
            // tmpdir at all. The exports were dead code. Keeping them risked
            // silently retargeting unrelated tools (npm cache, etc.) at
            // ~/.claude-tmp on a fresh install where the dir didn't exist
            // yet. Removed.
            //
            // v54 (2026-04-24): TMPDIR re-added, now pointing at a generic
            // $HOME/tmp. Gemini CLI's shell tool calls os.tmpdir() to place
            // its `shell_pgrep_*.tmp` tracker, and our bundled libnode.so
            // (Termux source) hardcodes `/data/data/com.termux/files/usr/tmp`
            // as the fallback — which doesn't exist in Shelly's sandbox, so
            // the pgrep redirect surfaces "No such file or directory" on
            // every Gemini shell execution. Setting TMPDIR to a writable
            // dir inside HOME overrides the Termux default. The v43 "npm
            // cache silently retargets" risk does not apply because we
            // mkdir the dir unconditionally and it's a generic tmp, not
            // tied to any specific tool's data.
            sb.appendLine("export TMPDIR=\"\$HOME/tmp\"")
            sb.appendLine("mkdir -p \"\$TMPDIR\" 2>/dev/null")
            // bug #106 part B: explicit PS2 so a wrapped or unclosed paste
            // never confuses the user with a non-default continuation
            // prompt. The literal `<` line-prefix observed during
            // multi-line paste display corruption is most likely bash's
            // continuation-prompt rendering of an unclosed quote — pinning
            // PS2 to the canonical `> ` makes that diagnosis verifiable.
            sb.appendLine("export PS2='> '")
            // [#50270](https://github.com/anthropics/claude-code/issues/50270):
            // claude-code 2.1.113+ ships a Bun SEA binary that does not
            // run on Android bionic. The bundled auto-updater would
            // happily fetch a 2.1.113+ tarball mid-session and brick the
            // CLI. Setting DISABLE_AUTOUPDATER=1 stops that. The chmod
            // a-w on the cli dir (in __shelly_bg_cli_update) is the
            // second half of the same defense.
            sb.appendLine("export DISABLE_AUTOUPDATER=1")
            // bug #100 seed is emitted AFTER the git() shell function is
            // defined (near line 739 — search for `git() {`) so that plain
            // `git config ...` resolves to the function and reaches the
            // bundled libgit.so via linker64. Writing it here would have
            // used `command git`, which bypasses the function on purpose
            // and then fails because $libDir/git is an ET_DYN .so and not
            // directly executable — the seed would silently no-op.
            // bug #77: gemini-cli bundles a hardcoded check that throws if
            // process.env.TERMUX_VERSION is undefined on Android, even though
            // it never actually needs Termux for the chat path. Setting any
            // value satisfies the check and lets the bundle load. We pair this
            // with the post-install sed below so a future gemini release that
            // moves to a different gating mechanism still gets neutralised.
            sb.appendLine("export TERMUX_VERSION=shelly")
            // bug #74: explicit HISTFILE so `↑` works out of the box on a
            // cold session. Without this, bash defaults HISTFILE to ~/.bash_history
            // but only if `$HOME` is writable at startup — and on a fresh Shelly
            // install the file doesn't exist yet, so the very first ↑ finds an
            // empty history list and does nothing. Creating the file up front
            // turns the "did the button break?" confusion into the expected
            // "no history yet" beep behaviour.
            sb.appendLine("export HISTFILE=\"\$HOME/.bash_history\"")
            sb.appendLine("export HISTSIZE=10000")
            sb.appendLine("export HISTFILESIZE=20000")
            sb.appendLine("[ -f \"\$HISTFILE\" ] || touch \"\$HISTFILE\"")
            sb.appendLine()

            // bug #91/#94: enable readline bracketed-paste handling so that
            // `bracketed-paste-begin` is registered as a function (the
            // standard `\e[200~` binding is also set, which is harmless on
            // bionic and necessary on sane guests).
            //
            // bug #97 follow-up: the ESC in `\e[200~` gets swallowed during
            // readline dispatch on bionic bash, so TerminalEmulator.paste()
            // no longer sends that keyseq. Instead it sends `\C-x\C-b`
            // (0x18 0x02) as the paste trigger — we bind that keyseq to
            // bracketed-paste-begin here so the function is entered without
            // any ESC bytes in the dispatch path. Once inside the function,
            // readline reads bytes directly (bypassing dispatch) until the
            // `\e[201~` END marker, so the ESC there is preserved and the
            // payload is inserted atomically as one edit event.
            sb.appendLine("# bug #91/#97: enable bracketed-paste + ESC-free trigger for Shelly's paste")
            sb.appendLine("bind 'set enable-bracketed-paste on' 2>/dev/null")
            // Bind in all three keymaps (emacs is default; vi-insert and
            // vi-command fire when the user flips editing-mode via `set -o vi`
            // or .inputrc). Without the vi-mode binds, `\C-x\C-b` stays
            // unbound in vi mode and the paste prefix beeps / streams the
            // payload through dispatch (= bug #91 re-introduced).
            sb.appendLine("bind '\"\\C-x\\C-b\": bracketed-paste-begin' 2>/dev/null")
            sb.appendLine("bind -m vi-insert '\"\\C-x\\C-b\": bracketed-paste-begin' 2>/dev/null")
            sb.appendLine("bind -m vi-command '\"\\C-x\\C-b\": bracketed-paste-begin' 2>/dev/null")
            sb.appendLine()

            // Linker64 helper function
            sb.appendLine("# Run binary via linker64 (SELinux blocks direct execve on app_data_file)")
            sb.appendLine("_run() { /system/bin/linker64 \"\$@\"; }")
            sb.appendLine()

            // Tool functions
            sb.appendLine("# v51: PATH-visible Android-compatible shell/env for AI CLIs")
            sb.appendLine("if [ ! -e \"\$HOME/bin/bash\" ] || [ \"\$(readlink \"\$HOME/bin/bash\" 2>/dev/null)\" != \"\$SHELL\" ]; then")
            sb.appendLine("  rm -f \"\$HOME/bin/bash\" 2>/dev/null")
            sb.appendLine("  ln -s \"\$SHELL\" \"\$HOME/bin/bash\" 2>/dev/null || true")
            sb.appendLine("fi")
            // v52: re-point $SHELL at $HOME/bin/bash so tools that validate
            // basename($SHELL) against {sh,bash,zsh,...} (e.g. Claude Code
            // CLI's Bash tool) accept it. The symlink target is the same
            // libshelly_shell.so, but basename=bash passes shell detection.
            sb.appendLine("export SHELL=\"\$HOME/bin/bash\"")
            sb.appendLine("if [ ! -e \"\$HOME/bin/sh\" ] || [ \"\$(readlink \"\$HOME/bin/sh\" 2>/dev/null)\" != \"/system/bin/sh\" ]; then")
            sb.appendLine("  rm -f \"\$HOME/bin/sh\" 2>/dev/null")
            sb.appendLine("  ln -s \"/system/bin/sh\" \"\$HOME/bin/sh\" 2>/dev/null || true")
            sb.appendLine("fi")
            sb.appendLine("if [ ! -e \"\$HOME/bin/env\" ] || [ \"\$(readlink \"\$HOME/bin/env\" 2>/dev/null)\" != \"/system/bin/env\" ]; then")
            sb.appendLine("  rm -f \"\$HOME/bin/env\" 2>/dev/null")
            sb.appendLine("  ln -s \"/system/bin/env\" \"\$HOME/bin/env\" 2>/dev/null || true")
            sb.appendLine("fi")
            sb.appendLine("bash() { _run $libDir/libbash.so \"\$@\"; }")
            sb.appendLine("node() { _run $libDir/node \"\$@\"; }")
            sb.appendLine("git() { _run $libDir/git \"\$@\"; }")
            // bug #100: seed default identity for auto-savepoint. Runs now
            // (AFTER git() is defined) so bare `git config` resolves to the
            // shell function -> _run linker64 $libDir/git. User-set values
            // take precedence because we only write when the config key is
            // unset. Redirect all output so a fresh shell doesn't print a
            // git error line on every prompt if libgit init has a hiccup.
            sb.appendLine("[ -z \"\$(git config --global user.email 2>/dev/null)\" ] && git config --global user.email 'shelly@localhost' >/dev/null 2>&1")
            sb.appendLine("[ -z \"\$(git config --global user.name  2>/dev/null)\" ] && git config --global user.name  'Shelly User'       >/dev/null 2>&1")
            sb.appendLine("npm() { _run $libDir/node $libDir/node_modules/npm/bin/npm-cli.js \"\$@\"; }")
            sb.appendLine("npx() { _run $libDir/node $libDir/node_modules/npm/bin/npx-cli.js \"\$@\"; }")
            // bug: the bundled python3.tar.gz extracts to $libDir/python3.13/
            // with the stdlib directly at that level (e.g. python3.13/encodings/),
            // not at python3.13/lib/python3.13/encodings/ as CPython expects
            // when PYTHONHOME is set. Python bails during bootstrap with
            // "ModuleNotFoundError: No module named 'encodings'" before it
            // even evaluates user code. Setting PYTHONPATH to the same prefix
            // is respected during bootstrap and unblocks the import lookup.
            sb.appendLine("python3() { PYTHONHOME=$libDir/python3.13 PYTHONPATH=$libDir/python3.13 _run $libDir/python3 \"\$@\"; }")
            sb.appendLine("python() { python3 \"\$@\"; }")
            sb.appendLine("pip() { python3 -m pip \"\$@\"; }")
            sb.appendLine("pip3() { pip \"\$@\"; }")
            sb.appendLine("curl() { _run $libDir/curl \"\$@\"; }")
            sb.appendLine("ssh() { _run $libDir/ssh \"\$@\"; }")
            sb.appendLine("rg() { _run $libDir/rg \"\$@\"; }")
            sb.appendLine("jq() { _run $libDir/jq \"\$@\"; }")
            sb.appendLine("sqlite3() { _run $libDir/sqlite3 \"\$@\"; }")
            sb.appendLine()

            // AI CLI tools — use updated CLIs ($HOME/.shelly-cli) if available, else bundled
            sb.appendLine("# AI CLI tools (with auto-update support)")
            sb.appendLine("__shelly_cli_dir=\"\$HOME/.shelly-cli\"")
            sb.appendLine("if [ -d \"\$__shelly_cli_dir/node_modules\" ]; then")
            sb.appendLine("  __cli_dir=\"\$__shelly_cli_dir/node_modules\"")
            sb.appendLine("else")
            sb.appendLine("  __cli_dir=\"$libDir/node_modules\"")
            sb.appendLine("fi")
            // @anthropic-ai/claude-code dispatch — BASHRC_VERSION v32 rewrite.
            //
            // The v28–v30 detour (Bun binary + proot + Alpine chroot + musl
            // sub-package + CA bundle + /etc/* population) was based on a
            // misreading of the v2.x packaging layout. The npm tarball for
            // @anthropic-ai/claude-code actually ships a pure-JS `cli.js`
            // that runs fine under our bundled bionic node. Issue #45541,
            // Ishabdullah/claude-code-termux, Qiita/Zenn/LINUX DO community
            // guides — they all converge on the same one-line dispatch:
            //   claude() { node node_modules/@anthropic-ai/claude-code/cli.js "$@"; }
            //
            // This function adds a three-tier fallback so that a broken
            // @latest upstream (observed on Termux with v2.1.114 — postinstall
            // bails with "Unsupported platform: android arm64" and leaves the
            // tree without a usable cli.js) doesn't kill the CLI:
            //   Tier 1: \$__shelly_cli_dir/node_modules/... (auto-updated)
            //   Tier 2: \$HOME/.shelly-cli.prev/node_modules/... (last-known-good snapshot)
            //   Tier 3: \$libDir/node_modules/... (APK-bundled golden fallback)
            //
            // The staging/verify/rollback pipeline in __shelly_bg_cli_update
            // guarantees Tier 2 is always known-good: a failing install
            // never reaches the live tree, so Tier 1 either works or falls
            // through to Tier 2/3 on the next invocation.
            // bug #117 Path C-bis: primary tier is the APK-bundled Bun SEA
            // binary + Shelly-patched musl loader. Legacy cli.js chain
            // (auto/prev/bundled) survives as a fallback so an older APK
            // whose build predates Path C-bis still boots a working claude.
            sb.appendLine("claude() {")
            sb.appendLine("  local __trampoline=\"$libDir/shelly_musl_exec\"")
            sb.appendLine("  local __musl_claude=\"$libDir/claude\"")
            sb.appendLine("  local __musl_ld=\"$libDir/ld-musl-aarch64.so.1\"")
            sb.appendLine("  local __runtime_claude=\"\$HOME/.shelly-runtime/claude/current/claude\"")
            sb.appendLine("  if [ \"\${SHELLY_FORCE_LEGACY_CLAUDE:-0}\" != \"1\" ] && [ -x \"\$__trampoline\" ] && [ -x \"\$__musl_claude\" ] && [ -x \"\$__musl_ld\" ]; then")
            // Seed resolv.conf on first use. The musl libc shipped here
            // has /etc/resolv.conf rewritten to this exact path at build
            // time — bionic has no /etc/resolv.conf so without this seed
            // musl falls back to 127.0.0.1:53 and the API call hangs.
            sb.appendLine("    if [ ! -s \"\$HOME/.shelly-ssl/resolv.conf\" ]; then")
            sb.appendLine("      mkdir -p \"\$HOME/.shelly-ssl\"")
            sb.appendLine("      printf 'nameserver 8.8.8.8\\nnameserver 1.1.1.1\\n' > \"\$HOME/.shelly-ssl/resolv.conf\"")
            sb.appendLine("    fi")
            sb.appendLine("    if [ -x \"\$__runtime_claude\" ]; then")
            sb.appendLine("      if [ -z \"\$SHELLY_SILENT_CLI_TIER\" ] && [ -z \"\$SHELLY_CLAUDE_TIER_ANNOUNCED\" ]; then")
            sb.appendLine("        export SHELLY_CLAUDE_TIER_ANNOUNCED=1")
            sb.appendLine("        echo '[shelly] claude: runtime latest (musl Bun SEA)' >&2")
            sb.appendLine("      fi")
            sb.appendLine("      LD_PRELOAD= _run \"\$__trampoline\" \"\$__musl_ld\" \"\$__runtime_claude\" \"\$@\"")
            sb.appendLine("      local __runtime_rc=$?")
            sb.appendLine("      case \"\$__runtime_rc\" in")
            sb.appendLine("        0)")
            sb.appendLine("          return 0")
            sb.appendLine("          ;;")
            sb.appendLine("        126|127|132|133|134|135|136|137|138|139|159)")
            sb.appendLine("          if [ -z \"\$SHELLY_SILENT_CLI_TIER\" ]; then")
            sb.appendLine("            echo \"[shelly] claude: runtime latest failed (exit \$__runtime_rc), falling back to APK musl\" >&2")
            sb.appendLine("          fi")
            sb.appendLine("          ;;")
            sb.appendLine("        *)")
            sb.appendLine("          return \"\$__runtime_rc\"")
            sb.appendLine("          ;;")
            sb.appendLine("      esac")
            sb.appendLine("    fi")
            sb.appendLine("    if [ -z \"\$SHELLY_SILENT_CLI_TIER\" ] && [ -z \"\$SHELLY_CLAUDE_TIER_ANNOUNCED\" ]; then")
            sb.appendLine("      export SHELLY_CLAUDE_TIER_ANNOUNCED=1")
            sb.appendLine("      echo '[shelly] claude: Path C-bis (musl Bun SEA)' >&2")
            sb.appendLine("    fi")
            sb.appendLine("    LD_PRELOAD= _run \"\$__trampoline\" \"\$__musl_ld\" \"\$__musl_claude\" \"\$@\"")
            sb.appendLine("    local __musl_rc=$?")
            sb.appendLine("    case \"\$__musl_rc\" in")
            sb.appendLine("      0)")
            sb.appendLine("        return 0")
            sb.appendLine("        ;;")
            sb.appendLine("      126|127|132|133|134|135|136|137|138|139|159)")
            sb.appendLine("        if [ -z \"\$SHELLY_SILENT_CLI_TIER\" ]; then")
            sb.appendLine("          echo \"[shelly] claude: Path C-bis failed (exit \$__musl_rc), falling back to cli.js tiers\" >&2")
            sb.appendLine("        fi")
            sb.appendLine("        ;;")
            sb.appendLine("      *)")
            sb.appendLine("        return \"\$__musl_rc\"")
            sb.appendLine("        ;;")
            sb.appendLine("    esac")
            sb.appendLine("  fi")
            sb.appendLine("  # Legacy fallback: pre-2.1.113 cli.js three-tier chain")
            sb.appendLine("  local __cli_js=\"\"")
            sb.appendLine("  local __tier=\"\"")
            sb.appendLine("  for __pair in \\")
            sb.appendLine("    \"\$HOME/.shelly-cli/node_modules/@anthropic-ai/claude-code/cli.js|auto\" \\")
            sb.appendLine("    \"\$HOME/.shelly-cli.prev/node_modules/@anthropic-ai/claude-code/cli.js|prev\" \\")
            sb.appendLine("    \"$libDir/node_modules/@anthropic-ai/claude-code/cli.js|bundled\"; do")
            sb.appendLine("    local __path=\"\${__pair%|*}\"")
            sb.appendLine("    local __tname=\"\${__pair##*|}\"")
            sb.appendLine("    if [ -f \"\$__path\" ]; then")
            sb.appendLine("      __cli_js=\"\$__path\"")
            sb.appendLine("      __tier=\"\$__tname\"")
            sb.appendLine("      break")
            sb.appendLine("    fi")
            sb.appendLine("  done")
            sb.appendLine("  if [ -z \"\$__cli_js\" ]; then")
            sb.appendLine("    echo 'claude CLI not installed — run __shelly_bg_cli_update and retry' >&2")
            sb.appendLine("    return 1")
            sb.appendLine("  fi")
            sb.appendLine("  if [ \"\$__tier\" != 'auto' ] && [ -z \"\$SHELLY_SILENT_CLI_TIER\" ]; then")
            sb.appendLine("    echo \"[shelly] claude: using \$__tier tier (\$__cli_js)\" >&2")
            sb.appendLine("  fi")
            sb.appendLine("  _run $libDir/node \"\$__cli_js\" \"\$@\"")
            sb.appendLine("}")
            // Gemini CLI 0.38+ relaunches itself with a bigger heap
            // (--max-old-space-size=5557) via `spawn2(process.execPath, ...)`.
            // On Shelly, process.execPath is \$libDir/node which is a shared
            // library accessed through /system/bin/linker64, so the child
            // exec gets linker64 with gemini.js as the binary and dies with
            // "has bad ELF magic: 23212f75" (hex for `#!/u`).
            //
            // Mitigation: set GEMINI_CLI_NO_RELAUNCH=true (gemini-cli honours
            // it as a kill-switch for the relaunch, see bundle/gemini.js
            // line 14445: `if (process.env["GEMINI_CLI_NO_RELAUNCH"])`) and
            // pass --max-old-space-size=5557 up front so the initial node
            // already has the heap the relaunch would have given it —
            // gemini-cli's heap-size check (target > current) then stays
            // false and the no-op guard holds. Belt + suspenders.
            sb.appendLine("gemini() { GEMINI_CLI_NO_RELAUNCH=true _run $libDir/node --max-old-space-size=5557 \"\$__cli_dir/@google/gemini-cli/bundle/gemini.js\" \"\$@\"; }")
            // codex: route `codex` (no args / options / bare prompt) to the
            // full ratatui TUI binary, and known `exec/resume/review/help`
            // subcommands to the lighter 1-shot exec binary. Both ship in the
            // codex-termux tarball (latest release in CI) but Shelly historically
            // only extracted codex_exec; codex_tui is added in v42+.
            // Errors out with guidance if a required binary is missing rather
            // than silently routing to the other one.
            sb.appendLine("codex() {")
            sb.appendLine("  local __tui=\"$libDir/codex_tui\"")
            sb.appendLine("  local __exec=\"$libDir/codex_exec\"")
            sb.appendLine("  local __runtime_tui=\"\$HOME/.shelly-runtime/codex/current/codex_tui\"")
            sb.appendLine("  local __runtime_exec=\"\$HOME/.shelly-runtime/codex/current/codex_exec\"")
            sb.appendLine("  local __first=\"\${1:-}\"")
            sb.appendLine("  # Known codex subcommands handled by the 1-shot exec binary.")
            sb.appendLine("  # (login/logout are intentionally NOT listed — Shelly implements")
            sb.appendLine("  # auth via the separate codex-login pure-JS helper since the fork")
            sb.appendLine("  # compiled out device-auth. mcp/completion are hit through TUI")
            sb.appendLine("  # too since the fork's help output only exposes exec/resume/review.)")
            sb.appendLine("  # _run already invokes /system/bin/linker64 \"\$@\", so we pass the")
            sb.appendLine("  # binary path as first arg (NOT prepending linker64 again).")
            sb.appendLine("  case \"\$__first\" in")
            sb.appendLine("    exec|resume|review|help)")
            sb.appendLine("      local __chosen_exec=\"\$__exec\"")
            sb.appendLine("      [ -x \"\$__runtime_exec\" ] && __chosen_exec=\"\$__runtime_exec\"")
            sb.appendLine("      if [ -x \"\$__chosen_exec\" ]; then")
            sb.appendLine("        _run \"\$__chosen_exec\" \"\$@\"")
            sb.appendLine("        return \$?")
            sb.appendLine("      else")
            sb.appendLine("        echo \"codex: codex_exec binary missing at \$__exec — rebuild Shelly or run __shelly_bg_cli_update\" >&2")
            sb.appendLine("        return 127")
            sb.appendLine("      fi")
            sb.appendLine("      ;;")
            sb.appendLine("  esac")
            sb.appendLine("  # Bare invocation / option flag / free-form prompt → TUI.")
            sb.appendLine("  local __chosen_tui=\"\$__tui\"")
            sb.appendLine("  [ -x \"\$__runtime_tui\" ] && __chosen_tui=\"\$__runtime_tui\"")
            sb.appendLine("  if [ -x \"\$__chosen_tui\" ]; then")
            sb.appendLine("    _run \"\$__chosen_tui\" \"\$@\"")
            sb.appendLine("    return \$?")
            sb.appendLine("  fi")
            sb.appendLine("  echo \"codex: codex_tui binary missing at \$__tui — upgrade to APK v42+ or reinstall\" >&2")
            sb.appendLine("  return 127")
            sb.appendLine("}")
            // v39: codex-login — ChatGPT subscription device-auth via
            // pure-JS helper extracted from assets/shelly-codex-auth.js.
            // Upstream codex-rs ships `codex login --device-auth`; the
            // community codex-termux rebuild we bundle has that compiled
            // out, so we re-implement the HTTPS flow in JavaScript.
            // `--open` asks the Shelly Browser Pane to load the
            // verification URL via the shelly://browser deep link instead
            // of requiring the user to switch apps manually.
            sb.appendLine("codex-login() { _run $libDir/node \"\$HOME/.shelly-codex-auth.js\" \"\$@\"; }")
            // v34: shelly-cs — GitHub Codespaces helper CLI (pure Node, REST API).
            // Invokes the extracted script at ~/.shelly-cs/shelly-cs.js via the
            // bundled bionic node. See HomeInitializer.initialize() where the
            // script is copied from assets/shelly-cs.js on every launch.
            sb.appendLine("shelly-cs() { _run $libDir/node \"\$HOME/.shelly-cs/shelly-cs.js\" \"\$@\"; }")
            // `cs` shortcut — v36 convenience. Lets the user get from any cwd
            // to their default codespace with a single two-letter command:
            //   cs use <name>    (first time)
            //   cs               (every subsequent time — opens default in
            //                     Browser Pane, claude pre-installed there)
            sb.appendLine("cs() { shelly-cs \"\$@\"; }")
            sb.appendLine("export -f bash claude gemini codex codex-login shelly-cs cs")
            sb.appendLine()

            // Coreutils: use --coreutils-prog=NAME to select applet
            // Skip bash builtins — overriding them breaks ANSI escapes in printf/echo
            val bashBuiltins = setOf("echo", "printf", "pwd", "test", "true", "false", "kill")
            sb.appendLine("# Coreutils applets (bash builtins excluded)")
            for (applet in COREUTILS_APPLETS) {
                if (applet in bashBuiltins) continue
                sb.appendLine("$applet() { _run $libDir/coreutils --coreutils-prog=$applet \"\$@\"; }")
            }
            sb.appendLine()

            // v47: Shelly-managed native CLI runtime updater. This updates the
            // Android-executable Claude Code musl binary and codex-termux
            // binaries without requiring a new APK. The updater stages,
            // verifies, smoke-tests, then flips ~/.shelly-runtime/*/current.
            sb.appendLine("# Shelly-managed native CLI runtime update (background, once per day)")
            sb.appendLine("shelly-update-clis() { SHELLY_LIB_DIR=\"$libDir\" _run $libDir/node \"\$HOME/.shelly-runtime-update.js\" \"\$@\"; }")
            sb.appendLine("shelly-doctor() { SHELLY_LIB_DIR=\"$libDir\" _run $libDir/node \"\$HOME/.shelly-doctor.js\" \"\$@\"; }")
            sb.appendLine("__shelly_runtime_update_marker=\"\$HOME/.shelly-runtime/.last_update\"")
            sb.appendLine("__shelly_runtime_update_interval=86400")
            sb.appendLine("__shelly_runtime_now=\$(date +%s 2>/dev/null || printf '%(%s)T' -1 2>/dev/null || echo 0)")
            sb.appendLine("__shelly_runtime_last_update=\$(cat \"\$__shelly_runtime_update_marker\" 2>/dev/null || echo 0)")
            sb.appendLine("__shelly_bg_runtime_update() {")
            sb.appendLine("  if [ -z \"\$__SHELLY_RUNTIME_UPDATE_SUBSHELL\" ]; then")
            sb.appendLine("    ( __SHELLY_RUNTIME_UPDATE_SUBSHELL=1 __shelly_bg_runtime_update </dev/null >/dev/null 2>&1 & )")
            sb.appendLine("    return 0")
            sb.appendLine("  fi")
            sb.appendLine("  mkdir -p \"\$HOME/.shelly-runtime\"")
            sb.appendLine("  if shelly-update-clis; then")
            sb.appendLine("    echo \"\$__shelly_runtime_now\" > \"\$__shelly_runtime_update_marker\"")
            sb.appendLine("  fi")
            sb.appendLine("}")
            sb.appendLine("if [ \$(( __shelly_runtime_now - __shelly_runtime_last_update )) -ge \$__shelly_runtime_update_interval ]; then")
            sb.appendLine("  ( __shelly_bg_runtime_update & )")
            sb.appendLine("fi")
            sb.appendLine()

            // CLI auto-update (background, once per day)
            // Placed after coreutils so date/cat functions are available.
            //
            // bug #80: previously this used `( ... ) &>/dev/null &` which ran
            // the update as a tracked background job. Bash's job control
            // still prints a multi-line "[1]+ Done (...)" notification with
            // the entire subshell body the next time the user presses Enter,
            // and variable names like $__shelly_cli_dir show up unexpanded
            // because bash stores the pre-expansion command string. We now
            // wrap the whole thing in a named function, redirect inside the
            // function so bash never sees any output, and launch via an
            // outer subshell `( fn & )` so the job is orphaned and never
            // enters the parent shell's job table — no Done line at all.
            sb.appendLine("# Auto-update CLI tools (background, once per day)")
            sb.appendLine("__shelly_update_marker=\"\$HOME/.shelly_last_update\"")
            sb.appendLine("__shelly_update_interval=86400")
            sb.appendLine("__shelly_now=\$(date +%s 2>/dev/null || printf '%(%s)T' -1 2>/dev/null || echo 0)")
            sb.appendLine("__shelly_last_update=\$(cat \"\$__shelly_update_marker\" 2>/dev/null || echo 0)")
            sb.appendLine("__shelly_bg_cli_update() {")
            // If the user invoked us directly from an interactive shell
            // (e.g. to force-upgrade claude-code), the exec redirection
            // below would close the main shell's stdin (→ EOF → bash
            // exits → "[Process completed - press Enter]"). Re-invoke
            // ourselves as a detached subshell so the main shell is
            // unaffected. The env-var guard prevents infinite recursion.
            sb.appendLine("  if [ -z \"\$__SHELLY_CLI_UPDATE_SUBSHELL\" ]; then")
            sb.appendLine("    ( __SHELLY_CLI_UPDATE_SUBSHELL=1 __shelly_bg_cli_update </dev/null >/dev/null 2>&1 & )")
            // Only surface the "update started" notice when stderr is a
            // terminal (the user's Shelly session). Gemini/Codex/Claude
            // shell tools capture stderr and would otherwise surface this
            // line as tool output, making the CLI look noisy. [ -t 2 ]
            // evaluates true only on attached TTYs.
            sb.appendLine("    [ -t 2 ] && echo '[shelly] background CLI update started. tail -f ~/.shelly-cli/install.log for progress' >&2")
            sb.appendLine("    return 0")
            sb.appendLine("  fi")
            sb.appendLine("  local __log=\"\$HOME/.shelly-cli/install.log\"")
            sb.appendLine("  local __staging=\"\$HOME/.shelly-cli.staging\"")
            sb.appendLine("  local __prev=\"\$HOME/.shelly-cli.prev\"")
            sb.appendLine("  mkdir -p \"\$__shelly_cli_dir\"")
            sb.appendLine("  exec </dev/null >>\"\$__log\" 2>&1")
            sb.appendLine("  echo \"--- \$(date) ---\"")
            // v32 pipeline: stage → install → health-check → promote (or discard).
            //
            // 1. Prepare staging — start from a copy of the current live tree
            //    so unchanged packages don't need to be re-downloaded. We use
            //    cp -al (hardlink) when available, falling back to a plain
            //    copy if coreutils' cp refuses --archive-links on this
            //    target filesystem.
            sb.appendLine("  rm -rf \"\$__staging\"")
            sb.appendLine("  mkdir -p \"\$__staging\"")
            sb.appendLine("  if [ -d \"\$__shelly_cli_dir/node_modules\" ]; then")
            sb.appendLine("    echo '[stage] cloning live tree → staging (flat copy)'")
            // Use `<src>/. <dest>/` form so the copy lands flat in $__staging
            // whether or not $__staging already exists as a directory. The
            // previous `cp -al $src $dest` form nested the tree as
            // $__staging/.shelly-cli/... when rm -rf left a stub behind
            // (observed in install.log from v32 builds).
            sb.appendLine("    cp -al \"\$__shelly_cli_dir/.\" \"\$__staging/\" 2>/dev/null || \\")
            sb.appendLine("      cp -r \"\$__shelly_cli_dir/.\" \"\$__staging/\"")
            sb.appendLine("  fi")
            // 2. Install into staging. --os=linux --cpu=arm64 tricks
            //    Anthropic's install.cjs postinstall out of its "Unsupported
            //    platform: android arm64" early-return (observed on fresh
            //    Termux installs since v2.1.114). --include=optional pulls
            //    the codex native binary so its optional dep resolves.
            //
            //    @anthropic-ai/claude-code is pinned to 2.1.112 — the final
            //    release that shipped cli.js as a pure-JS entry point. From
            //    2.1.113 the package dropped cli.js entirely in favour of a
            //    Bun-compiled native binary (bin/claude.exe) that requires a
            //    glibc/musl runtime our bundled bionic node can't load. We
            //    investigated cli-wrapper.cjs — it's a thin launcher that
            //    unconditionally spawns the native binary, so there's no JS
            //    fallback we could patch into. Until we ship Codespace
            //    integration (remote Linux executes claude-code) or revive
            //    the proot-chroot strategy (abandoned after v28–v31 churn)
            //    we pin to the last version that Shelly's `_run node
            //    cli.js` dispatch in claude() can execute natively.
            //
            //    Gemini and Codex remain @latest: gemini-cli is pure JS and
            //    Shelly patches the Termux guard via shelly-patcher.js; codex
            //    is dispatched through the bundled codex-termux native binary
            //    (libcodex_exec.so) via the codex.js sed patch.
            //
            //    We DO NOT pass --libc=musl or force-install the claude-code
            //    -musl sub-package; we don't use the Bun ET_EXEC anymore.
            sb.appendLine("  echo '[install] npm install start (claude-code pinned to 2.1.112, last cli.js release)'")
            // v41 smoke test: --libc=musl alone was not enough. npm's
            // platform detection kept reporting "Actual os: android"
            // regardless of the --os flag, rejecting claude-code's
            // required sub-package @anthropic-ai/claude-code-linux-arm64-
            // musl@2.1.114 with EBADPLATFORM. Three things combined to
            // finally bypass the check cleanly:
            //   1. npm_config_os=linux / npm_config_cpu=arm64 /
            //      npm_config_libc=musl env vars (the CLI --os/--cpu/
            //      --libc flags alone turned out not to be honoured for
            //      transitive platform checks in this npm version)
            //   2. --force (tells npm to install even when platform
            //      check fails — the sub-package binary goes into
            //      node_modules but we never invoke it, so the "wrong"
            //      libc is immaterial)
            //   3. --omit=optional (skip optional platform-specific
            //      binaries; with --force they'd get extracted anyway
            //      but --omit keeps the tree smaller)
            // Manually verified 2026-04-19: install produces a working
            // Tier 1 tree with claude-code 2.1.112 cli.js.
            sb.appendLine("  npm_config_os=linux npm_config_cpu=arm64 npm_config_libc=musl _run $libDir/node $libDir/node_modules/npm/bin/npm-cli.js install --prefix \"\$__staging\" --force --omit=optional --no-save @anthropic-ai/claude-code@2.1.112 @google/gemini-cli@latest @openai/codex@latest")
            sb.appendLine("  echo \"[install] npm install exit=\$?\"")
            // 3. Apply codex / gemini source patches to the staged tree
            //    (bug #76, #77, #96 — see earlier BASHRC_VERSION entries).
            //    Both are idempotent: safe to re-run on already-patched files.
            sb.appendLine("  _run $libDir/node \"\$HOME/.shelly-patcher.js\" codex \"$libDir\" \"\$__staging/node_modules\" || true")
            sb.appendLine("  _run $libDir/node \"\$HOME/.shelly-patcher.js\" gemini \"\$__staging/node_modules\" || true")
            // Bug #117 Option B: rewrite `shell:!0` → `shell:"/system/bin/sh"`
            // in claude-code's cli.js so the Bash tool can spawn a shell that
            // exists on Android bionic. Applied here (staging) so the fix is
            // in place before the tree gets chmod a-w'd below.
            sb.appendLine("  _run $libDir/node \"\$HOME/.shelly-patcher.js\" claude \"\$__staging/node_modules\" || true")
            // bug #105 (codex vendor shim): codex.js 0.121.0 has an
            //   if (!existsSync(path.join(..., 'vendor', 'aarch64-unknown-
            //   linux-musl', 'codex', 'codex'))) throw new Error('Missing
            //   optional dependency @openai/codex-linux-arm64')
            // guard that fires BEFORE the shelly-patcher's spawn rewrite
            // runs. Symlinking our bundled codex_exec into the expected
            // vendor path lets existsSync pass. The symlink's TARGET is
            // never actually spawned — the patched spawn goes straight to
            // linker64 + codex_exec — so any mismatch in ET_EXEC class or
            // libc is immaterial. Run after patching so we're guaranteed
            // to have the @openai/codex directory tree on disk.
            sb.appendLine("  local __codex_vendor=\"\$__staging/node_modules/@openai/codex/vendor/aarch64-unknown-linux-musl/codex\"")
            sb.appendLine("  mkdir -p \"\$__codex_vendor\" 2>/dev/null && ln -sfn \"$libDir/codex_exec\" \"\$__codex_vendor/codex\" && echo \"[install] codex-vendor shim OK\" || echo \"[install] codex-vendor shim FAILED\"")
            // 4. Health check: the new claude cli.js must exist AND print a
            //    recognisable version string within 15s. Anthropic's v2.1.114
            //    regression (missing cli.js after postinstall bails) fails
            //    this test and triggers rollback.
            sb.appendLine("  local __new_cli=\"\$__staging/node_modules/@anthropic-ai/claude-code/cli.js\"")
            sb.appendLine("  local __healthy=0")
            sb.appendLine("  if [ -f \"\$__new_cli\" ]; then")
            sb.appendLine("    if timeout 15 _run $libDir/node \"\$__new_cli\" --version 2>&1 | grep -Eq '^[0-9]+\\.[0-9]+\\.[0-9]+'; then")
            sb.appendLine("      __healthy=1")
            sb.appendLine("    fi")
            sb.appendLine("  fi")
            // 5. Promote or discard staging. On success we rotate the old
            //    live tree into .shelly-cli.prev (last-known-good snapshot)
            //    and promote staging to the live path. On failure we delete
            //    staging without touching the live tree, and skip the
            //    update marker so the next shell launch retries.
            sb.appendLine("  if [ \$__healthy -eq 1 ]; then")
            sb.appendLine("    echo '[install] health check OK, promoting staging'")
            sb.appendLine("    rm -rf \"\$__prev\"")
            sb.appendLine("    if [ -d \"\$__shelly_cli_dir\" ] && [ -d \"\$__shelly_cli_dir/node_modules\" ]; then")
            sb.appendLine("      mv \"\$__shelly_cli_dir\" \"\$__prev\"")
            sb.appendLine("    fi")
            sb.appendLine("    mkdir -p \"\$__shelly_cli_dir\"")
            sb.appendLine("    mv \"\$__staging\" \"\$__shelly_cli_dir\"")
            // [#50270](https://github.com/anthropics/claude-code/issues/50270)
            // belt + suspenders alongside DISABLE_AUTOUPDATER=1: drop write
            // permission on the claude-code module dir so even if the env
            // var is dropped the bundled updater can't replace cli.js with
            // a 2.1.113+ Bun SEA blob. `2>/dev/null` because chmod can fail
            // on filesystems that don't honour the bits — that's fine, the
            // env var still does the job.
            sb.appendLine("    chmod -R a-w \"\$__shelly_cli_dir/node_modules/@anthropic-ai/claude-code\" 2>/dev/null || true")
            sb.appendLine("    echo \"\$__shelly_now\" > \"\$__shelly_update_marker\"")
            sb.appendLine("    echo '[install] committed — live tree updated, .prev snapshot refreshed'")
            sb.appendLine("  else")
            sb.appendLine("    echo '[install] HEALTH CHECK FAILED — discarding staging, live tree untouched' >&2")
            sb.appendLine("    rm -rf \"\$__staging\"")
            sb.appendLine("    echo '[install] will retry next shell launch (marker NOT updated)'")
            sb.appendLine("  fi")
            sb.appendLine("  echo '[install] done'")
            sb.appendLine("}")
            sb.appendLine("if [ \$(( __shelly_now - __shelly_last_update )) -ge \$__shelly_update_interval ]; then")
            sb.appendLine("  ( __shelly_bg_cli_update & )")
            sb.appendLine("fi")
            sb.appendLine()

            // Prompt: PROMPT_COMMAND dynamically builds PS1 with HOME→~ replacement.
            // bash's \w doesn't shorten HOME when launched via linker64, so we do it
            // manually. We previously embedded OSC 133 (shell-integration) markers
            // here, but the bundled TerminalView didn't strip them and they leaked
            // into the visible buffer (\[\e]133;A\a\] showed up literally),
            // throwing off cursor column math and producing the "phantom prompt"
            // bug. Drop OSC 133 entirely — it's only useful to terminals that
            // understand it (Warp, WezTerm) and we don't.
            sb.appendLine("# Prompt with dynamic HOME shortening")
            sb.appendLine("# Resolve real HOME path once (symlink: /data/user/0 vs /data/data)")
            sb.appendLine("SHELLY_HOME_REAL=\$(cd \"\$HOME\" 2>/dev/null && pwd -P)")
            sb.appendLine("[ -z \"\$SHELLY_HOME_REAL\" ] && SHELLY_HOME_REAL=\"\$HOME\"")
            sb.appendLine("__shelly_prompt() {")
            sb.appendLine("  local d")
            sb.appendLine("  d=\"\$(pwd -P 2>/dev/null || pwd)\"")
            sb.appendLine("  printf '%s' \"\$d\" > \"\$HOME/.shelly_cwd\" 2>/dev/null")
            sb.appendLine("  # Replace home path with ~ (\\~ prevents tilde expansion in replacement)")
            sb.appendLine("  d=\"\${d/#\$SHELLY_HOME_REAL/\\~}\"")
            sb.appendLine("  d=\"\${d/#\$HOME/\\~}\"")
            sb.appendLine("  # printf -v assigns to PS1 directly; \\[ \\] stay literal so bash treats")
            sb.appendLine("  # them as PS1 width-hint markers, and \\033 expands to ESC for color.")
            sb.appendLine("  printf -v PS1 '\\[\\033[1;32m\\]%s\\[\\033[0m\\]\\$ ' \"\$d\"")
            sb.appendLine("}")
            sb.appendLine("PROMPT_COMMAND=__shelly_prompt")

            // MOTD — displayed once on first login, then flag file prevents repeat
            sb.appendLine()
            sb.appendLine("# Welcome MOTD (first launch only)")
            sb.appendLine("if [ ! -f \"\$HOME/.shelly_motd_shown\" ]; then")
            sb.appendLine("  printf '\\n'")
            sb.appendLine("  printf '\\033[36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\\033[0m\\n'")
            sb.appendLine("  printf '\\033[1;32m  Shelly へようこそ\\033[0m\\n'")
            sb.appendLine("  printf '\\033[36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\\033[0m\\n'")
            sb.appendLine("  printf '\\n'")
            sb.appendLine("  printf '  以下のCLIツールがインストール済みです:\\n'")
            sb.appendLine("  printf '\\n'")
            sb.appendLine("  printf '    \\033[33mclaude\\033[0m    — Claude Code (Anthropic)\\n'")
            sb.appendLine("  printf '    \\033[33mgemini\\033[0m    — Gemini CLI  (Google)\\n'")
            sb.appendLine("  printf '    \\033[33mcodex\\033[0m     — Codex CLI   (OpenAI)\\n'")
            sb.appendLine("  printf '\\n'")
            sb.appendLine("  printf '  お持ちのアカウントでログインしてください:\\n'")
            sb.appendLine("  printf '\\n'")
            // v39: corrected login hints.
            //   - `claude auth login` is wrong — Claude Code doesn't have a
            //     standalone auth subcommand. Users launch `claude` and
            //     type `/login` inside the REPL.
            //   - `codex-login` is Shelly's new JS helper (v39) that drives
            //     the ChatGPT subscription device-auth flow and writes
            //     ~/.codex/auth.json. Previously there was no way to
            //     authenticate codex on-device because codex-termux has
            //     the login subcommand compiled out.
            sb.appendLine("  printf '    \\033[90m\$\\033[0m claude           \\033[90m(then type /login)\\033[0m\\n'")
            sb.appendLine("  printf '    \\033[90m\$\\033[0m gemini           \\033[90m(then /auth)\\033[0m\\n'")
            sb.appendLine("  printf '    \\033[90m\$\\033[0m codex-login      \\033[90m(ChatGPT subscription)\\033[0m\\n'")
            sb.appendLine("  printf '\\n'")
            sb.appendLine("  printf '\\033[36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\\033[0m\\n'")
            sb.appendLine("  printf '\\n'")
            sb.appendLine("  touch \"\$HOME/.shelly_motd_shown\"")
            sb.appendLine("fi")

            bashrc.writeText(sb.toString())
            versionFile.writeText(BASHRC_VERSION.toString())
        }

        // Create .profile
        val profile = File(home, ".profile")
        if (!profile.exists()) {
            profile.writeText("[ -f ~/.bashrc ] && . ~/.bashrc\n")
        }

        return home
    }
}
